### ISSUE TITLE
Is there a way to handle subdomain routing, like <param>.example.com

### ISSUE THREAD

**Issue by lucasrg** [rackt/react-router#1005]
Our project requires routing based on the subdomain, more precisely: username.example.com

We can easily handle the request and redirect the path before reaching the Router, but the problem is to use the Router.Link component, which reasonably complains that the path is not mapped:

`<Router.Link to="http://username.example.com/">`
causes
`Invariant Violation: Cannot find a route named "http://username.example.com/"`

Is there a solution already, or any plans to solve this kind of routing?

**Comment by ryanflorence** [comment]
Nope. This isn't a limitation of the router but of the browser APIs it uses like hashchange and HTML history, they don't work on subdomains. You'll just need to do a normal href.

> The new URL must be of the same origin as the current URL; otherwise, pushState() will throw an exception. This parameter is optional; if it isn't specified, it's set to the document's current URL.

https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history

**Comment by davidfurlong** [comment]
I understand that this task is beyond the scope and capability of react router.

I have a certain use case where it would be most convenient to be able to define a `match.params` `key` based on the subdomain. The reason I want to use react-router for this is because I want to use the same components with different routes, with the route `params` being determined by multiple methods. For instance `charityName.deedmob.com` and `www.deedmob.com/charityName` would both inject the same `match.params.organizationSlug` and the components could be agnostic as to how this route param was determined
