### ISSUE TITLE
Getter in TestLocation breaks IE8 support

### ISSUE THREAD

**Issue by dittos** [rackt/react-router#1022]
It seems that you've changed JS transpiler from jstransform to babel since 0.12.3. However Babel doesn't support class inheritance in IE8 (see babel/babel#703).

Any suggestions?

**Comment by taurose** [comment]
The way I read this, inheritance actually works in IE8 and the culprit was es5-shim.
Getters and setters would break compatibility, but we don't use them as far as I can tell.

**Comment by dittos** [comment]
Okay, inheritance or Babel was not the cause. But [locations/TestLocation.js](https://github.com/rackt/react-router/blob/master/modules/locations/TestLocation.js) is using getter and imported by default.

**Comment by vladimir-rovensky** [comment]
Is there any progress on this issue? It seems that this completely breaks IE8 support, right? 
Did you manage to find some workaround for this by any chance?  
Alternatively, do you think there's a version of react-router compatible with React 0.13 that doesn't have this issue?

Unfortunately we need to support IE8 and this effectively prevents us from updating the library :-(

**Comment by pkese** [comment]
Couldn't TestLocation.js be changed to not use ES6 getters?

**Comment by vladimir-rovensky** [comment]
I tried removing the TestLocation import from index.js, but still couldn't get it to work, now I get the following error: Unhandled rejection Error: Invariant Violation: ReactCompositeComponent.getChildContext(): childContextTypes must be defined in order to use getChildContext().
This most likely originates from RouteHandler and I have no idea how to fix it. 
Seems to me like IE8 support is completely broken right now.

**Comment by codeuniquely** [comment]
IE8 is broken +1

**Comment by damassi** [comment]
Oh no this is big trouble!  Any word on how to fix this other than downgrading?  Just went through quite the process bringing all of our libs up to date and after booting the VM found that our application has broken.

**Comment by ryanflorence** [comment]
we don't have anymore getters
