### ISSUE TITLE
<Redirect> to route with additional (not replacement) params

### ISSUE THREAD

**Issue by benjie** [rackt/react-router#1034]
Imagine we have the following tree and we want to make it so if you visit `/foo/:id` you're redirected to `/foo/:id/awesome`:

```
<Route name="foo" path="/foo/:id" handler=...>
  <Route name="foo_bar" path=":type" handler=...>
    <DefaultRoute handler=... />
    ...
  </Route>
</Route>
```

A guess might have you do:

```
<Redirect from="/foo/:id" to="foo_bar" params={{type: "awesome"}} />
```

However, due to [how Redirect is implemented](https://github.com/rackt/react-router/blob/06c15c5b616140589ed56ccc00be84bcbd3de543/build/npm/lib/Route.js#L197) the params aren't added to the existing params, but instead replaced, meaning the `:id` param is dropped. 

Is there a way to both pass through the dynamic `:id` param and add an additional static `:type` param? If not, would you accept a pull request changing `options.params || params` to something like `Object.assign({}, params, options.params)`? 

---

In case anyone else is struggling with this, a hack that seems to work (react-router 0.12.4) is defining an unreachable route **after** the route you want to point to with the path you want, like so:

```
<Redirect from="/foo/:id" to="foo_bar_HACK_awesome" />
<Route name="foo" path="/foo/:id" handler=...>
  <Route name="foo_bar" path=":type" handler=...>
    <DefaultRoute handler=... />
    ...
  </Route>
  <Route name="foo_bar_HACK_awesome" path="awesome" />
</Route>
```

**Comment by mgan59** [comment]
yeah just ran into a similar issue, wanted a catch all nested route to take the existing params and redirect to the same params but specify a default tab to load.  Realized that based on the code in [Route]
(https://github.com/rackt/react-router/blob/master/modules/Route.js#L170) by passing in values into `params={{...}}` it replaces the dynamic values.  I was sorta expecting this to merge my params and keep the ones already in existence.  

Granted I could maybe restructure all my urls to avoid this issue, but on a tight deadline and I'm porting my app from `react-router-component` to this router so have to find the least-change-path for migration and this <Redirect /> not providing this functionality is a bummer.

**Comment by mgan59** [comment]
Also, the [example provided](http://rackt.github.io/react-router/#Redirect) should be a little clearer in explaining what happens when you use the `param`.  And the `SESSION.USER_ID` is slightly misleading as there is no context explaining that it is totally overwriting the params

**Comment by mgan59** [comment]
Happy to work on a pull-request, let me know if there are any issues/items to be concerned with?  Or is this something that is not welcome?

**Comment by mgan59** [comment]
@benjie originally skimmed, had a chance to read your response, thanks for the hack looks like it will help move me forward for the time being.

But happy to work on this feature to make our url/routes cleaner.

**Comment by benjie** [comment]
No worries; I think the fix is just the one line change I outlined above.

**Comment by ryanflorence** [comment]
would love if somebody can check on master if this is still a problem

**Comment by mjackson** [comment]
I think the way we handle `<Redirect>` on current master (rewrite for version 1.0) makes this a non-issue because we don't ever ask you for a hash of params (i.e. `<Redirect params>` is not a thing). Instead, you just give us the destination URL pattern and we interpolate any existing params into it (for convenience). So in your case @benjie, you could use:

```xml
<Redirect from="/foo/:id" to="/awesome"/>
```

If you wanted to re-use the existing `id` param, you can.

```xml
<Redirect from="/foo/:id" to="/bar/:id"/>
```

**Comment by benjie** [comment]
@mjackson I'd love to be able to supplement the params, e.g. in my case I want to redirect to a named route (rather than an absolute path) and merge `{type: awesome}` with the params.

**Comment by mattnorris** [comment]
@mjackson `Redirect` does not seem to work the way you describe. When redirecting, using your example, my route has the literal string `:id` instead of using its value. 

[I posted a question to StackOverflow](http://stackoverflow.com/questions/43399740/react-router-redirect-drops-param), but it hasn't gotten much love.

**Comment by mattnorris** [comment]
@mjackson `Redirect` doesn't seem to work as you described above. Instead of the `id` being preserved to the `to` route, the literal string `:id` is placed in the route instead. 

[I posted the same to StackOverflow](http://stackoverflow.com/questions/43399740/react-router-redirect-drops-param), but haven't gotten any love.
