### ISSUE TITLE
ReactCSSTransitionGroup breaks transition hooks

### ISSUE THREAD

**Issue by dwick** [rackt/react-router#1046]
Wrapping `RouteHandler` with a `ReactCSSTransitionGroup` causes `Router.setRouteComponentAtDepth` to be called with `null` from the outgoing `RouteHandler`'s `componentWillUnmount` life cycle method.

This breaks transition hooks, since they're static and rely on the component being passed in.

Here's an example: http://codepen.io/anon/pen/azxrVX (navigate to page 2, back to 1, and then to 2 again).

gist: https://gist.github.com/anonymous/504ec95a7a37250e1de8

**Comment by jedverity** [comment]
+1

**Comment by rmoorman** [comment]
+1

**Comment by cateland** [comment]
+1

**Comment by rmoorman** [comment]
Possibly related, a call to `router.transitionTo` within `willTransitionFrom` (due to authentication checking) breaks the ReactCSSTransitionGroup functionality too. In case the [auth-flow example](https://github.com/rackt/react-router/tree/master/examples/auth-flow) is combined with the [animations example](https://github.com/rackt/react-router/tree/master/examples/animations) the transitions break. Calling the dashboard using the url only causes a transition to the login form (using the `willTransitionFrom` hook) and will transition back on success. But then when you click another link within the app, the Routehandler which we transitioning from is not removed.

Furthermore there is a ReactCSSTransitionGroup warning when requesting the dashboard of the example initially like this. The warning seems to suggest that the item the transitiongroup is watching did not disappear within 5 seconds.

**Comment by idolizesc** [comment]
+1 getting `null` for component argument. Not using CSSTransitionGroup, however...

**Comment by iggyfisk** [comment]
+1, are there any reasonable workarounds for now?

**Comment by ryanflorence** [comment]
1.0 uses `this.props.children` so it shouldn't work any differently than anything else now :)
