### ISSUE TITLE
React.render <Handler /> inside Router.run is slow.

### ISSUE THREAD

**Issue by steida** [rackt/react-router#1057]
Or it somehow resets app component, so everything is rerendered from scratch. Whenever I change url, immutable === check is ignored and whole app is rerendered. It is bug or feature?

**Comment by kilometers** [comment]
Are you doing server-side rendering as well?

**Comment by steida** [comment]
Yes please: github.com/steida/este

**Comment by taurose** [comment]
Rerendering `<Handler />` is supposed to cause a full "rerender" of your react tree, i.e. it should call componentWillReceiveProps, shouldComponentUpdate, render etc from top to bottom, while unmounting old components, and mounting new components.

It is not supposed to replace your whole react tree (unmount all previous components, then mount the current ones), or even replace the whole DOM. 

So you should have some control over rendering using `shouldComponentUpdate`, but you need to make sure that all `<RouteHandler>`s and `<Link>`s (with active class) are rerendered after changing the path and rerendering `<Handler>`.

**Comment by steida** [comment]
So it's obvious that context was misused (I knew that context is something like ng scope). It's possible to just project router state somewhere?

**Comment by rgrwkmn** [comment]
@steida check out the [Router Context docs](https://github.com/rackt/react-router/blob/master/docs/api/RouterContext.md). I personally pass some of the router state stuff into my primary route handler as props from Router.run and then continue passing those to nested route handlers. Here's an example:

```javascript
Router.run(routes, Router.HashLocation, function(Handler, state) {
  React.render(<Handler pathParams={state.params}/>, document.body);
});

// Base has a pure render function and uses shouldComponentUpdate to
// only render when props and state change.
class Route extends Base {
  renderRouteHandler(props) {
    if (!props) {
      props = {};
    }
    props.pathParams = this.props.pathParams;
    return (<RouteHandler {...props}/>);
  }
  render() {
    return (<div>{this.renderRouteHandler()}</div>
  }
}
```

So instead of using <RouteHandler/> I always use the renderRouteHandler function so all my route handlers have access to the same router state stuff and will re-render if there are changes.
