### ISSUE TITLE
Redirecting to external site?

### ISSUE THREAD

**Issue by kjs3** [rackt/react-router#1062]
transition.redirect('http://news.ycombinator.com'); didn't do what I thought it would.

**Comment by kilometers** [comment]
transition.redirect()'s `to` parameter is designed for other react-router routes, not URLs... no?

**Comment by kilometers** [comment]
In your transition hook, use a standard redirect method if going to a different site. e.g. `window.location`

**Comment by kjs3** [comment]
Ok cool. I was just messing around. I don't actually have a real use-case for this.
I am curious what other people think though. Having to use window.location means it won't just work server-side.

**Comment by kilometers** [comment]
Ah ha! Well I've never had to do that, so I'm curious as well.

**Comment by wmira** [comment]
doing a window.location is at runtime/event..shouldn't it be fine even if the page is initially rendered on the server?

**Comment by filod** [comment]
why is this closed? i get into the same problem...

**Comment by ktamas77** [comment]
i'd like to see what is the proper way to do it as well.

**Comment by mmahalwy** [comment]
+1 to that. `window.location` is not a good solution and cannot be tested...

**Comment by taion** [comment]
Thanks for your question!

We want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router, and per the issue template, we are not handling support requests here.

If you have a question or otherwise need help, please post on Stack Overflow with the #react-router tag at https://stackoverflow.com/questions/ask?tags=react-router, or drop in on the #react-router room on Reactiflux at https://discord.gg/0ZcbPKXt5bYaNQ46.
