### ISSUE TITLE
state lost when going back

### ISSUE THREAD

**Issue by tcurdt** [rackt/react-router#1094]
I am using `this.context.router.transitionTo('search', { q: "query" }, { q: "query" });` to submit a form to a new route. But when I then press the back button all components on the original page have lost their state.

Is that expected?
How can I keep the state?

**Comment by srph** [comment]
Yep, because they are unmounted the moment you switched to another route (a sibling or a parent route).

1. You can try to save it through localStorage (I don't find this reasonable);
2. Maybe through **Flux** *Store*s?
3. Instead of route changes, you might wanna try to have a parent component to handle the form and the next route you are describing here. This way, you can save the data somewhere without worrying about it getting lost.

**Comment by ryanflorence** [comment]
if you have persistent state you need to save it somewhere other than your component's `state`. the router isn't involved in this.
