### ISSUE TITLE
Warning in jest: You should not use a static location...

### ISSUE THREAD

**Issue by totopia** [rackt/react-router#1106]
I am trying to follow the new update on how to test router from https://github.com/rackt/react-router/wiki/Announcements
My code is
````
Router.run(routes, '/testPage/1', function(Handler, state) {}
````

It triggered a warning on 
````
Warning: You should not use a static location in a DOM environment because the router will not be kept in sync with the current URL
````

How do I resolve this warning?

I believe this is blocking me from using click simulation to test if the router works.  (I am trying to simulate a next button so the router will go from testPath/1 to testPath/2)

**Comment by Nic128** [comment]
I am getting this warning when doing server-side rendering. I don't know why.

**Comment by ryanflorence** [comment]
if you give it a string url like `/testPage/1` instead of a location (in v0.13) you only get one shot at rendering, there are no transitions with a static location. Use TestLocation instead (you can look our tests to see how, make sure you're not on master, since its all changed)

You can use MemoryHistory on master.
