### ISSUE TITLE
Is there a way to test if a route exists?

### ISSUE THREAD

**Issue by jackmoore** [rackt/react-router#1207]
Is there a way to test if a URL matches an existing route?  Instead of using the `<Link>` component, I want to be able to use regular anchor elements and only cancel the default behavior and transitionTo if a given URL matches a route.

**Comment by taurose** [comment]
You should be able to use [router.match(path)](https://github.com/rackt/react-router/blob/master/modules/createRouter.js#L207). You can get the router instance from context (like `Link` does) or as the return value of `Router.run` or `Router.create` and then pass it via props or globals.

**Comment by jackmoore** [comment]
Thanks!

**Comment by tjgupta** [comment]
It seems like the router object no longer has a match() method with react-router 2.0. Is there a new way to do this? I would like to do a similar thing - show a specific piece of UI only if the current route matches a certain route pattern.

**Comment by timdorr** [comment]
You're looking for [`this.context.router.isActive()`](https://github.com/reactjs/react-router/blob/master/docs/API.md#isactivepathorloc-indexonly)

**Comment by tjgupta** [comment]
Thanks @timdorr for the quick reply, but `isActive` doesn't work the way I had thought, and doesn't seem to work for my purpose. In fact, I submitted a [patch](https://github.com/reactjs/react-router/pull/3135) yesterday assuming `isActive` was broken, but apparently I was just misunderstanding its API.

I'm trying to match based on a pattern that may or may not include route params, like `/items/:itemId`. On the other hand, `isActive` assumes you're passing in a path rather than a path pattern, i.e. `/items/1`.

I'm trying to determine if a route pattern is currently active, not whether a particular URL is active (which I can already determine with location.pathname).

Am I approaching this incorrectly?

**Comment by inkybutton** [comment]
To reiterate the original question for the new release, is there a way to test if an arbitrary route exists in react-router 2 now? My use case is pretty much the same as @jackmoore 's - I am passed a link in a component that I can assume is valid, and I would like to determine whether the link is a route within react-router or not, so I can either render it as a <Link> or <a>.

Complicating this might be the new way to declare a not found page, which is to match all routes. This might mean a function for testing match may always return true with the not found route.

**Comment by inkybutton** [comment]
Thanks @taion. I tried `match` and indeed I had to pass a callback in to get the result, which complicates rendering a bit. It also matched external URLs with the not found page I set up in routes (currently the index page.) So I would have to test whether the matched URL and its components is the same as the one I passed in to determine whether the route exists.
I'm not too familiar with react-router and the async routes stuff, so just wondering could there be a simpler and synchronous way, perhaps a builtin function on `props.router` given by `withRouter`? I guess this is more of a feature request now!

**Comment by tikotzky** [comment]
@taion won't `match`ing using the server-side rendering API cause any Component that should be lazy loaded via code splitting to be loaded at match time? 
That would mean that by just rendering a link to a route you would end up fetching the components even though they're not needed yet...

**Comment by taion** [comment]
`match` is async only when the routes are async. If the routes are all sync, then it will return synchronously. It should be straightforward to wrap this in a synchronous function if those conditions are satisfied in your app, but this is specific enough that we don't want to include it in React Router. You can also add a property on your "not found" route and test against that to determine whether you matched it.

`match` will indeed do all the async loading if there is any, but it has to – otherwise how would it know if the match succeeds or not?

**Comment by tikotzky** [comment]
I understand that `match` need to async load all the routes in order to test if the routes match. The issue is that `match` will load both the routes and the components (via `getComponents()`) ideally there would be an api to be able to `match` without loading the components to be able to test if a path is a valid route.

**Comment by devinivy** [comment]
I agree with @tikotzky– I would also like to see such a feature.  My use-case is to use the `setRouteLeaveHook()` to check if the next route is "valid" (e.g., per some authentication).  But to do that I need to lookup which route the user is trying to go to.
