### ISSUE TITLE
Should getQuery() return a clone?

### ISSUE THREAD

**Issue by kjs3** [rackt/react-router#1231]
I was storing/manipulating the return value of `getQuery()` from the Navigation mixin to generate pagination links. I had some weird behavior with other components using `getQuery()` and it took me awhile to realize I was manipulating the routers canonical query params.

What are use cases where you need the router's actual query object and not just the values?

**Comment by tmcw** [comment]
:+1: I'd support a clone, or `Object.freeze` on the results of both `getQuery()` and `getParams()` - it's unfortunately pretty easy to accidentally modify them in-place.

**Comment by cesarandreu** [comment]
+1 on this, it's already caused me to have one bug, since it was unexpected

**Comment by gyzerok** [comment]
+1

**Comment by mjackson** [comment]
`getQuery` is removed from the `State` mixin in the 1.0 API. Instead, your route components (previously called "handlers") receive a `location` prop with a `query` property. It should be a little more obvious that this object does not change, since it's on a `Location` instance instead of returned from a mixin method.

Try `npm install react-router@1.0.0-beta2` to try it out.
