### ISSUE TITLE
Bug in transition.abort

### ISSUE THREAD

**Issue by deezahyn** [rackt/react-router#1246]
Hi,

I made a bin to illustrate the bug:
http://jsbin.com/joqujo/8/

if you click pageA, pageB, and final and then click any page, it will force you to final since I did a `transition.abort`

However if instead of clicking any links you use the back button.  It short-circuits the router removing all your history.

I tried transition.redirect however it seems it just replacing your current history.  So if I only have 3 states to look back and the user hits 4x it will transition out from that final page.

**Comment by mjackson** [comment]
I think this happens because we try to go back to the last URL you visited when you abort a transition. This behavior is consistent with [current master](https://github.com/rackt/react-router/blob/5d674c9515aa628b644c223b2e3f43bb28ac24bc/modules/Router.js#L176-L180). There's a big scary comment there that explains why.

I've wondered for a while now if we shouldn't just hook into the `window`'s `beforeunload` event to trigger 'willTransitionFrom`/`onLeave` hooks. This would force them to be synchronous, but the only use case I've ever seen for asynchronous transition hooks is persisting data on the server side.

@ryanflorence What do you think?

**Comment by deezahyn** [comment]
@mjackson so you're saying 'this.props.onAbort' is becoming falsy?  Because for some reason, when I think of abort transition I never think of using goBack().  Which is what's on that else clause.

**Comment by AlexGalays** [comment]
Last time I played with it, the ember router also had bugs relating to transition aborting originating from one of the browser history buttons (or keyboard shortcut of course). Chrome/Firefox also allow you to jump a few history entries at a time if you hold left click for a bit, so a simple go(-1) won't do the job.
To be honest this is a can of worms and that's why I removed that very feature from my own router; I'm curious about whether you will find a solution :)

**Comment by ryanflorence** [comment]
transitions are completely different now built on top of `history`
