### ISSUE TITLE
Allow semicolon in urls

### ISSUE THREAD

**Issue by torarnek** [rackt/react-router#1288]
In our solution we sometimes get session variables appended to the URL like this:

/item/123;SESSION_ID=3525

Is there a way to ignore the SESSION_ID part of the URL?

Apparently semicolons are allowed as part of URLs:
http://stackoverflow.com/questions/1178024/can-a-url-contain-a-semi-colon

**Comment by fson** [comment]
@torarnek You can ignore the part after the semicolor like this:
```js
<Route path="item/:id;*" component={Item} />
```
Making that part optional (you mentioned the variable is appended *sometimes*) seems a bit trickier, since if you to use `item/:id(;*)` that makes the route regex consume it as a part of the previous param instead and it doesn't get ignored.

I think you could work around that problem by defining two routes:
```js
<Route path="item/:id" component={Item} />
<Route path="item/:id;*" component={Item} />
```

**Comment by mjackson** [comment]
Thanks @fson

**Comment by torarnek** [comment]
@fson Thanks for your response.
This solution would require a lot of duplicated routes, however, I have now solved it with
Router.HistoryLocation.replace() with the semicolon-part removed.

**Comment by TashaRolland92** [comment]
Does anyone have a solution for this but with the ( . ) character?
Not one of the solutions I have found have been lucky enough to work :-(
I just simply would like to redirect /test-page.aspx to /test-page but ReactJS bombs out at the dot...
Anyone... PLEASE ;)
