### ISSUE TITLE
Injecting contexts to components

### ISSUE THREAD

**Issue by asaf** [rackt/react-router#1352]
Hey,

I'm using Alt as Flux impl,

I'd like all my route's components to have some reference to the `alt` instance,

Preferably, i'd like to pass the `alt` instance to the top level Component (Router? or per route's component) but I couldn't find an elegant way to do that,

What would be the appropriate way to achieve that?

I assume I can implement the `createElement` hook and define the `alt` as a component property, but it seems like `context` is more appropriate as all components should have the same `alt` instance.

Thanks

**Comment by ryanflorence** [comment]
You can render a `Router` inside another component.

```js
var App = React.createClass({
  // do your context stuff or whatever you want here.
  render() {
    return <Router .../>
  }
});
```

**Comment by asaf** [comment]
@ryanflorence Are you sure ? I tried that already, Im getting

`
Potentially unhandled rejection [2] SyntaxError: Invalid regular expression: /^/*(.*?)$/: Stack overflow
    at String.match (native)
    at matchPattern (http://localhost:8080/jspm_packages/npm/react-router@1.0.0-beta2/lib/URLUtils.js:143:24)
`

It seems like URLs breaks when `Router` is not the first component.

Thanks

**Comment by asaf** [comment]
@ryanflorence Awesome, thanks.

**Comment by lzrski** [comment]
Nice. I like how the Router is a component itself.

Can this be done with server side rendering as well?

We build an isomorphic app using react-router 1.0.0-beta2 and would like to share some context between parent and child components. Both are rendered by Router with routes like this:

```coffee-script
routes = 
  path        : '/'
  name        : 'Parent'
  component   : require './components/Parent'
  childRoutes : [
    name        : 'Child'
    path        : '/child'
    component   : require './components/Child'
```

If I understood [react docs on  children ownership](http://facebook.github.io/react/docs/multiple-components.html#ownership) correctly, then rendered instances of my components are owned by the instance of Router.

Now the child context we set in parent is undefined in children, and I get warnings like this:

```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `3`) for key (test) while mounting Child (see: http://fb.me/react-context-by-parent)
```
After reading [this gist](https://gist.github.com/jimfb/0eb6e61f300a8c1b2ce7) I guess it's because in current version of React the context is passed from owner to owned (*not from parent to child, as names of properties would suggest*). In my setup parent doesn't own a child - they are both owned by router. Am I right?

Then @ryanflorence answer would solve our problem if only I could apply it server-side.
