### ISSUE TITLE
willTransitionTo replacement in 1.x

### ISSUE THREAD

**Issue by johann-sonntagbauer** [rackt/react-router#1388]
The current stable release 0.13.3 has a very convenient way to intercept routing transitions and do additional prevalidation. One can simply define a willTransitionTo hook and implement the validation logic and trigger a redirect if needed.

```javascript
var Settings = React.createClass({
  statics: {
    willTransitionTo: function (transition, params, query, callback) {
      auth.isLoggedIn((isLoggedIn) => {
        transition.abort();
        callback();
      });
    }
});
```

The current 1.x beta releases removed that feature. The transition hooks are now only available on the Router and on the Routes itself but not on the components. So it is not possible to implement such a cross cutting concern by simply decorating the component. 
For now I use following workaround which is not very nice.

```javascript
// decorate Component with onEnter hook.

function authenticated(Component) {
  const wrappedComponent = React.createClass({
    statics: {
      onEnter(next, transition) {
        if (!state.get('session.authenticated')) {
          transition.to('/login');
        }
      }
    },
    render() {
      return <Component {...this.props} {...this.state} />;
    }
  });

  return wrappedComponent;
}


// decorate the notAllowed Component
const decorated = authenticated(notAllowed);

// workaround onEnter delegates to statics onEnter of the component
<Route path="/notAllowed" component={decorated} onEnter={decorated.onEnter}/>
```

Another way to implement this would be to have own derived Route implementations like `AuthRoute` or so.

**Comment by wmyers** [comment]
I share your pain on the loss of `willTransitionTo`. In `0.13.3` I was using a [promise-returning util function](https://github.com/rackt/react-router/issues/530#issuecomment-111337459) to check if my user data had been returned post-auth. This seemed to work well with the `callback` param in `willTransitionTo`. But the `onEnter` hook in `1.0.0-beta2` only seems to work in a synchronous way unless I'm missing something.

On the brighter side, could this change be so that routing authentication can now occur before the auth-decorated component is instantiated? If so that is a good thing.

Also I found your workaround isn't too bad, thanks. I was doing something similar based on [this example](https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L117). But your approach is more like how I had it in `0.13.3`.

**Comment by vladap** [comment]
It might help:

https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L117

**Comment by johann-sonntagbauer** [comment]
@vladap thx for the hint, but the main question is what is the recommended way to handle transition hooks with now in 1.x. Hopefully some core contributor finds some time to clear that issue and tell us whats there plan here.
According the code and the discussion for now on that topic i think they will move hooks in general onto the route itself. But that is only my impression.

**Comment by wmyers** [comment]
@johann-sonntagbauer agree it is hooks on the route itself:
[http://rackt.github.io/react-router/tags/v1.0.0-beta2.html#Route](http://rackt.github.io/react-router/tags/v1.0.0-beta2.html#Route)

One other thing is that the first transition in the app (passed in via a hook) cannot be aborted (you get a warning if you try to do this). Not sure if this was the case in `0.13.3`. So if you are deep-linking into an authenticated page and want to stop and do some login stuff first, then it's a bit of a problem.

@vladap the auth-flow example relies on a synchronous check if you are logged in, by just checking for the existence of a token in localStorage. I'm using JWT tokens which can expire and only contain a hashed key. Once I retrieve the token I still have to send it off to the server before I know whether I'm logged in.

I'm currently achieving an async auto login process in `1.0.0-beta2` with a hacky 'shim' page component. I can only get access to the first transition in the `onEnter` hooks (when refreshing the app). So I redirect to the empty shim and then retrieve the `context.router` in the component constructor, I can then use this to kick off a new transition with `this.context.transitionTo()` rather than `transition.to()` in the hook.

It all seems too complicated, and I get the feeling there should be an easier way to interrupt a transition at the start of the app, but it works for now.

**Comment by johann-sonntagbauer** [comment]
@wmyers thx for the details. Very interesting fact that you can not abort the first transition.

Hope we will get some answers and some idea in which direction the react-router team is heading for. Hope that I can catch one of them during ReactEurope.

**Comment by wmyers** [comment]
No worries, hope you get some answers in Paris - nice place to have a conf :)

I've put up a post of how I'm currently dealing with async auth [here](http://wmyers.github.io/technical/react-flux/Async-authentication-with-React-Router-1.0.0-beta2/).

**Comment by epeli** [comment]
It seems that in beta3 you can return a promise from `onEnter`.

**Comment by epeli** [comment]
Oops. Not a promise but a callback as the third argument. See:

https://github.com/rackt/react-router/blob/v1.0.0-beta1/modules/RoutingUtils.js#L192

**Comment by wmyers** [comment]
Thanks @epeli that's good to know, I'll make some adjustments

**Comment by iam4x** [comment]
@johann-sonntagbauer Nice workaround, but this doesn't work on the server side:

```
Error: Invariant Violation: Server-side <Router>s need location, branch, params, and components props. Try using Router.run to get all the props you need
```

I'm stuck, hope some contributor will help us on this...

**Comment by mjackson** [comment]
The replacement for `willTransitionTo` in the 1.0 API is `<Route onEnter>`. See [the auth-flow example](https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L130) for an example of how to use this hook.

Transition hooks have moved from route handler components up to the route objects themselves to give developers greater flexibility. Now, you don't need a component class just to define a transition hook. Instead, you can just use a prop and a function.

**Comment by wbecker** [comment]
Can you still do this in an async manner though? With `willTransitionTo`, you had a callback. 

With `onEnter`, you have a transition, but with [`wait()` being removed in 0.12](https://github.com/rackt/react-router/blame/master/UPGRADE_GUIDE.md#L107), what can you do instead? In that example in the upgrade, @ryanflorence uses the callback on willTransitionTo, but that's gone :cry:

**Comment by johann-sonntagbauer** [comment]
Yes it is possible to do async operations. The onEnter hooks get a callback if you define it in your API. 

following onEnter hook will delay the navigation to your route for 5 seconds.Hope that helps-
```javascript
 onEnter: (nextState, transition, callback) => {
            setTimeout(callback, 5000);
          },
```

**Comment by wbecker** [comment]
Sweet, thanks! It doesn't seem to be documented here: http://rackt.github.io/react-router/tags/v1.0.0-beta3.html

It's not going to get taken away, I trust?

**Comment by johann-sonntagbauer** [comment]
nope its documented in code :)

**Comment by mjackson** [comment]
It's almost always a bad idea to have an async `onEnter` because the router will wait to do the transition until the callback is called.

**Comment by wbecker** [comment]
My use case is: on page load, when a user has asked to go to a route, I am
not sure whether they have permission to go there until a request verifying
this has been performed. I was going to have onEnter wait until this
request has come back, and if they lack permission redirect them.

Is there a better solution to perform this logic?

I guess I could render the page and only transition them away afterwards if
the state updates in such a way that they are not allowed ... But then
everything would be flickering about.

**Comment by wmyers** [comment]
As per my link above [here](http://wmyers.github.io/technical/react-flux/Async-authentication-with-React-Router-1.0.0-beta2/), I'm re-directing to a blank 'shim' page while waiting for async authentication. Fairly basic concept, and not the most elegant, but it works. Also for when deep-linking straight to an authenticated page.

**Comment by epeli** [comment]
> It's almost always a bad idea to have an async onEnter because the router will wait to do the transition until the callback is called.

On the server side think it makes a lot sense because you do not want to render your components before you have all the data. Also I don't see it being too bad on the client neither because you can always render a spinner or something to inform the user that the next view is loading. Or was there some other reason to avoid it?

**Comment by almccann** [comment]
@wmyers Did you make any progress on the shim page approach?  Am hoping to do async auth more elegantly.

Any other approaches been successful?

**Comment by wmyers** [comment]
@almccann I'm still using the shim with a project that still uses react-router@1.0.0-beta2. Am about to start a new React project with the latest rc - will update if things improve

**Comment by kidwm** [comment]
@mjackson How to do `transition.abort()` in 1.0.0 ? I want to do this with `replaceState`, but how to get current path in onEnter() ?
```js
replaceState({nextPathname: nextState.location.pathname}, CURRENT_PATHNAME);
```

**Comment by taion** [comment]
Thanks for your question!

We want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router.

Questions like yours deserve a purpose-built Q&A forum. Would you like to post this question to Stack Overflow with the tag #react-router? https://stackoverflow.com/questions/ask?tags=react-router.

We also have an active and helpful React Router community on Reactiflux, which is a great place to get fast help with React Router and with the rest of the React ecosystem. You can join at https://discord.gg/0ZcbPKXt5bYaNQ46.

**Comment by CraigDMcKenna** [comment]
@almcann @wmyers  Are either of you successfully using something besides @wmyers shim approach at this point? 

I suppose one could use async functions but I'm not really keen on the idea until the spec is finalized.

**Comment by anonymosh** [comment]
What were the reasons for this change? I really liked the way the components were responsible for handling / reacting on transition changes. It kept special handling in the context of the respective component.

Now i need to push this everything to the top Route configuration which seems to be an awful way of cluttering the file containing the config with unnecessary functions and imports. 

The current auth example seems to simplified for the means of the example. Is there still a way to encapsulate the route transition hooks into a HoC?

**Comment by taion** [comment]
Not well. More importantly, you can't bind to context in static methods – in `onEnter` you can e.g. close over a store.
