### ISSUE TITLE
getQuery returns old query object when clicking browser's back button

### ISSUE THREAD

**Issue by salarkhan** [rackt/react-router#1393]
```
componentDidMount: function() {
  window.onpopstate = this.handleBackButtonEvent;
},

handleBackButtonEvent: function() {
  this.getQuery() // returns the query string of the url BEFORE back is clicked
}
```

I'm using HashLocation, maybe that's part of the issue?

**Comment by taurose** [comment]
You're not supposed to use the browser API. Use the run callback or componentWillReceiveProps for that.

**Comment by salarkhan** [comment]
Whoops, didn't realize that. Got the idea from [this issue](https://github.com/rackt/react-router/issues/967). 

Not sure I follow what you're saying though:

```
Router.run(routes, function(Handler) {
      React.render(<Handler/>, document.getElementById('main'));
 });
```

How am I supposed to know if the back button was hit in the run callback? Most examples I've been looking at use `BrowserHistory` instead of `Handler`, so I'm kind of lost as to which direction to go in here.

Note: The above code exists in my `App.jsx`, and I want back button behavior for a specific component. Will that change implementation?

**Comment by taurose** [comment]
Use the second parameter (`state`) of `Router.run`:

```js
Router.run(routes, function(Handler, state) {
      if(state.action === 'pop') {
        // back / forward button, or window.history.go/back/forward
      }

      React.render(<Handler/>, document.getElementById('main'));
 });
```

I'm kinda surprised that `State` (Mixin) doesn't offer `getCurrentAction` (I guess because it's barely used), so you have to manually pass that information down via props to the component that needs it.

`BrowserHistory` is for the upcoming 1.0 release. For 0.13, see
* source code: https://github.com/rackt/react-router/tree/v0.13.3
* docs: http://rackt.github.io/react-router/tags/v0.13.3.html
