### ISSUE TITLE
transitionTo() does not mount component.

### ISSUE THREAD

**Issue by hackingbeauty** [rackt/react-router#1412]
Hi,

I have the following route:

```javascript
var routes = (
  <Route handler={Main} >
    <Route path="/tasks" handler={TaskList} />
  </Route>
);

Router.run(routes, Router.HistoryLocation, function (Handler) {
  React.render(
  	<div>
	  	<App />
	  	<Handler/>
  	</div>, 
  	document.getElementById('main')
  );
});
```

However, when I transition to http://localhost/#/tasks, my TaskList component never mounts nor does it render.  Also, componentDidMount() never gets called.

What am I doing wrong?

**Comment by taurose** [comment]
Do you use `<Link>` for navigation? You're using `BrowserHistory`, so you should get URLs like `http://localhost/tasks` without the hash.

Also, the fact that you're rendering an `<App />` component besides `<Handler />` seems a bit suspicious. I don't think it's necessarily wrong to render other things there, but you'd usually have your app contained within `<Handler />` since you want your whole app driven by the router and you can't use `<Link>` outside of it.

**Comment by hackingbeauty** [comment]
Hey, I just started to use <Link>, but that didn't fix the issue.  Taking <App> and placing it some where else fixed the issue.  Thank you!
