### ISSUE TITLE
No way of handling static page

### ISSUE THREAD

**Issue by yniche** [rackt/react-router#1464]
I have problem handling static pages like about us, contact, the landing page etc. These are just blob of text stored in `dist/content/*.html`, but they are still handled by React, so I get the layout and everything.

I have the following code:

```html
<Route name="/" handler={Static} />
<Route name="about" path="/about" handler={Static} />
```

```javascript
'use strict';

import React from 'react';
import request from 'superagent';

export default class Static extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  contentFilePath () {
    var path = window.location.pathname;
    var basename = path.slice(1, path.length) || 'index';
    return `/content/${basename}.html`;
  }

  componentDidMount() {
    request.get(this.contentFilePath()).
    end(this.callback.bind(this));
  }

  callback(error, response) {
    this.setState({body: response.text});
  }

  render() {
    return (
      <div dangerouslySetInnerHTML={{__html: this.state.body}} />
    );
  }
}
```

This doesn't work. I go to the landing page, all is fine, but when I click the about us link, the handler is the same and hence it doesn't get instantiated again.

I think this is a fairly standard requirement, but I haven't been able to find a way of doing so in the docs.

Is there a workaround?

# Bonus: static params

I still don't like the solution above since it depends on window and because it's trying to determine the path which I don't think should be its responsibility.

This is how I think it should really be solved (but again, I haven't found an option to do it, unless I'm missing something):

```html
<Route name="/" handler={Static} slug="landing-page" />
<Route name="about" path="/about" handler={Static} slug="about" />
```

```javascript
export default class Static extends React.Component {
  contentFilePath () {
    return `/content/${this.props.params.slug}.html`;
  }
}
```

**Comment by taurose** [comment]
First off, you should use [State mixin's](https://rackt.github.io/react-router/tags/v0.13.3.html#State) `getPathname` over `window.location.pathname`.

The problem I see with your code is that it only refreshes when mounting, not when the location changes. To get there, I think you can do one of the following:

* change `Static` to also refresh its content on `componentWillReceiveProps`. The hook will be called on every location change (unless a parent handler implements `shouldComponentUpdate`  to returns false)
* replace `Static` with a wrapper class that merely renders `<Static key={this.getPathname()} pathname={this.getPathname()} />`. By using `key`, the component will be re-initialized whenever the pathname changes. `pathname` is also passed as a normal prop, so `Static` just needs to use `this.props.pathname` instead of router methods or `window.location`
* use a component factory for your route config. This way, React will treat them as different classes and not reuse them

    ```js
    var createStaticHandler = (pathname) => class StaticHandler extends React.Component {
      render() {
        return <Static pathname={pathname} />;
      }
    }

    <Route name="/" handler={createStaticHandler('/')} slug="landing-page" />
    <Route name="about" path="/about" handler={createStaticHandler('/about')} slug="about" />
    ```




> This is how I think it should really be solved

I agree, although you'd still have to rewrite your component to react to `componentWillReceiveProps`. I think in 1.0.x you'll be able to use `this.props.route.slug`.

**Comment by yniche** [comment]
Thank you very much Alexander! I had no idea about `componentWillReceiveProps`, I'm really new to React, so my apologies for silly question. I reckon I can't use the State mixin though if I'm using the ES6 classes declaration introduced in 0.13 (which abandoned mixins altogether)?

**Comment by srph** [comment]
If I'm right, you should get the router instance through context (`this.context.router`), and you should be able to use it as ```this.state.context.router.getPathname```.

**Comment by yniche** [comment]
@srph is that assuming that the mixin is present? (I cannot use it with the ES6 class syntax.) Without the mixin `this.context.router` is `undefined` and so is `this.state.context`.

**Comment by taurose** [comment]
You need to add `contextTypes`, which is similar to `propTypes`, but mandatory for React to pass the context to the component.

```js
class Handler extends React.Component {
  render() {
    var pathname = this.context.router.getCurrentPathname();
  }
}

Handler.contextTypes = {
  router: React.PropTypes.func.isRequired
};
```

With ES7 (babel stage 0) you can write it a little nicer:

```js
class Handler extends React.Component {
  static contextTypes = {
    router: React.PropTypes.func.isRequired
  }

  render() {
    var pathname = this.context.router.getCurrentPathname();
  }
}
```

Also note that the method names are slightly different from the mixin. Not sure if they're documented somewhere, but it should be obvious when looking at the [source code of the mixin](https://github.com/rackt/react-router/blob/v0.13.3/modules/State.js).

**Comment by yniche** [comment]
@taurose that did the trick! Thank you so much!
