### ISSUE TITLE
Warning: is being rendered by both [Unknown] and Router using the same key (null) in the same place.

### ISSUE THREAD

**Issue by goncalvesjoao** [rackt/react-router#1474]
Hi guys!

Thanks for the great work on react-router!

I've been using the beta3 version on my app and stumbled upon a warning. I decided to strip my app of all things and build rather [small and concise app](https://github.com/goncalvesjoao/react-lazy-routes-example) to see if the warning still appeared, and it does.

The app loads two other simple apps according to selected routes:
route: /marvel* loads the marvel app
route: /account* loads the account app

The readme on the [repository](https://github.com/goncalvesjoao/react-lazy-routes-example) explains how to replicate the warning:
>Go to http://localhost:3000 click on Marvel link and click on any of the Show links.

>A warning will appear in the Chrome's javascript console:

>>Warning: is being rendered by both [Unknown] and Router using the same key (null) in the same place. Currently, this means that they don't preserve state. This behavior should be very rare so we're considering deprecating it. Please contact the React team and explain your use case so that we can take that into consideration."

I can live with the warning, this is not breaking my app but the fact that I can't find the root of the problem is bugging me...

Do you guys have an ideia what it might be?
Thanks in advance!

**Comment by taurose** [comment]
Thanks for putting up the repo :)

As far as I can tell, the warning is due to what you do [here](https://github.com/goncalvesjoao/react-lazy-routes-example/blob/master/app/js/marvel/components/index.jsx#L11). As long as you're at `/marvel`, the `MarvelIndex` component will create the element and be the owner, but when you navigate to `/marvel/heroes/*`, the router will create the element and pass it as `props.children`.

I would try to avoid rendering a route component inside another route component, i.e. either pass a component to the router, or render it yourself, but don't do both.

**Comment by goncalvesjoao** [comment]
I see, thanks @taurose .

The 0.13 version had a DefaultRoute component that we could use when defining routes.

But from what I can find in the beta version's example, either I do
> {this.props.children || \<DefaultComponent />} # like you mentioned in [here](https://github.com/goncalvesjoao/react-lazy-routes-example/blob/master/app/js/marvel/components/index.jsx#L11)

or something like:
> { path: '/', component: Home } # as seed in [here](https://github.com/goncalvesjoao/react-lazy-routes-example/blob/master/app/js/main_app/routes.jsx#L9)

my problem with the second approach is that it only works with absolute paths, right?

What would you suggest me to do in this example [here](https://github.com/goncalvesjoao/react-lazy-routes-example/blob/master/app/js/marvel/index.jsx):
```
module.exports = {
  component: require('./components'),
  routes: [
    {
      path: 'heroes',
      component: require('./components/heroes'),
      childRoutes: [
        { path: ':id', component: require('./components/heroes/show') }
      ]
    }
  ]
};
```
in order for me to render the "marvel/components/heroes/list" when the route 'marvel/heroes' is reached
and how to render "marvel/components/heroes/show" when the "marvel/heroes/:id" is reached?

Thanks again!

**Comment by taurose** [comment]
Not sure about `DefaultRoute` either. 

Looking at your route config, it seems like you're essentially rendering the same components for `/marvel` and `/marvel/heroes`. So you could change your router config to render no extra component for `marvel/heroes` by removing the `component` property, and have `marvel/components/index.jsx` render `<Heroes>{this.props.children}</Heroes>` instead of `{this.props.children || <Heroes />}`. Or you could setup a redirect.

**Comment by goncalvesjoao** [comment]
Cool works for me, it would be nice to the a default route option but this also works.

I updated the repo with a "solution" branch in case someone else is interested.

Thanks again @taurose !
