### ISSUE TITLE
Is the this.context.router in 0.13.2 deprecated?

### ISSUE THREAD

**Issue by jiyinyiyong** [rackt/react-router#1491]
Back 0.13.2 there was
https://github.com/rackt/react-router/blob/57543eb41ce45b994a29792d77c86cc10b51eac9/UPGRADE_GUIDE.md#012x---013x

```js
// 0.13.x w/o ES6 fanciness
var Foo = React.createClass({
  contextTypes: {
    router: React.PropTypes.func
  },

  render: function () {
    var router = this.context.router;
    var id = router.getCurrentParams().id;
    var searchTerm = router.getCurrentQuery().searchTerm;
    // etc.
  }
});
```
And now in 0.13.3 nothing is about `this.context`:
http://rackt.github.io/react-router/#State

In changelog there's no details on such huge change:
https://github.com/rackt/react-router/blob/master/CHANGELOG.md

Just want to know details on that change. Thanks.

**Comment by taurose** [comment]
The context approach was suggested back then because the mixins can't be used with ES6 classes, and so the plan was to deprecate mixins and make everyone use context instead. If you look at the mixins source code, you'll see that these are only proxies for context. 

Too many people didn't like using context, and lots of people are still using `React.createClass` instead of ES6, so the suggestion of using context was removed, and mixins weren't deprecated.

Using context directly won't be deprecated (https://github.com/rackt/react-router/issues/1405) since the mixins (and `<Link>`) need it. There will be probably be ES7 decorators that work like the mixins and can be used with classes as an alternative to using context (https://github.com/rackt/react-router/issues/1173).

**Comment by jiyinyiyong** [comment]
@taurose Thanks. I actually like the mixin way better :)
