### ISSUE TITLE
set target='_blank'

### ISSUE THREAD

**Issue by leishman** [rackt/react-router#1510]
Is there an easy way to set target='_blank' using the `Link` helper? It seems that this attribute does not get rendered.

The only way I've been able to set this attribute on a link was to create an anchor tag myself and use `makeHref` to set the href attribute.

**Comment by psawaya** [comment]
+1, this would be incredibly useful for my work.

**Comment by taurose** [comment]
It does get rendered since `<Link>` transfers all props to `<a>`. However, `<Link>` needs to do handle the navigation using JS and prevent browser navigation. I guess there's an argument for making `<Link>` respect the target attribute, but the direction has been to keep `<Link>` minimal and sparse in features.


> The only way I've been able to set this attribute on a link was to create an anchor tag myself and use makeHref to set the href attribute.

Another solution could be to use the `onClick` handler:

```js
<Link to="route" target="_blank" onClick={(event) => {
  event.preventDefault();
  window.open(this.makeHref("route"));
}} />
```

**Comment by ryanflorence** [comment]
seems like a good idea that if there's a `target=_blank` to skip our work and let the browser do its thing, then you still get `isActive` functionality

**Comment by arasmussen** [comment]
FYI this feature is supported in 1.0!

**Comment by jcalfee** [comment]
fyi:https://mathiasbynens.github.io/rel-noopener/
