### ISSUE TITLE
Is anyone working on 1.0.0beta3 nested routes not working problem?

### ISSUE THREAD

**Issue by JoeGrasso** [rackt/react-router#1674]
I cannot use example route as a subroute.
This becoming pathetic, this does not work. WHY?!?!?!?!?!

 <Router history={history}>
            <Route path="/" component={Main}>
                <Route path="/example" component={Example}></Route>
        </Route>
        </Router>

**Comment by antipin** [comment]
Come on, don' be so hysterical, it's open source project and it's beta. You can use stable version. Or you could try to fix it yourself or at least contribute tests on this case. Why do you think anyone here owes you something?

P.s. It's beta than nothing!

**Comment by DenisIzmaylov** [comment]
I realize @JoeGrasso, it's looks little bit strange. We used to active community in open-source projects. React Team, @gaearon and others shows us what is "[re]active" development and great real-time support in open-source projects. But it was not always. For open source projects it's normal to be inactive some time because people which are contribute to community as usual make it in free time, spending they own personal life to it. With no fee and real big thanks to all contributors.

**Comment by mjackson** [comment]
Thanks, @DenisIzmaylov :)

@JoeGrasso You're going to have to be more specific than that if you'd like some help.
