### ISSUE TITLE
1.0.0-beta3 Nested route with params(and without) issue

### ISSUE THREAD

**Issue by zoilorys** [rackt/react-router#1682]
I use route setup like this 
```javascript
<Route component={CoreLayout}>
    <Route name='home' path='/' component={HomeView} />

    <Route name='user-info' path='user/:id' component={Profile} />
    <Route name='about' path='about' component={AboutView} />

    <Route name='dashboard' path='dashboard' component={DashboardView} />
    <Redirect from='/admin' to='dashboard' />
  </Route>
```

Everything works fine except 'user/:id' path, and just any route like 'path/path' (when there is slash in path string). Server always returns 404. 
Tried without params, just something like path='/user/profile', still no result.
Tried nesting them like 
```javascript
 <Route name='user-info' path='user' component={UsersView}>
     <Route path='profile' component={Profile} />
</Route>
```
Where users view was just a container that rendered {this.props.children}.

Maybe anyone have some tips about what might be the problem? Or maybe i'm missing the point?

**Comment by davezuko** [comment]
This issue stemmed from use with my react-redux-starter-kit, and I believe it was just caused by the webpack dev server not handling the routes correctly, and has been fixed here: https://github.com/davezuko/react-redux-starter-kit/commit/e29692c33871e9339834308fcdc9af6ded88a203.

Hopefully that clarifies things for the react-router authors, as it's probably just a non-issue.

**Comment by ryanflorence** [comment]
sounds like its not us, let me know if otherwise
