### ISSUE TITLE
This example is really missing in the docs

### ISSUE THREAD

**Issue by darreng** [rackt/react-router#1683]
http://stackoverflow.com/questions/31889051/react-router-dynamic-routing-instead-of-pattern-matching/

Is this a good approach (the given answer)?

**Comment by taurose** [comment]
I'd say it depends on your use case which isn't very clear to me after reading your SO question. In my opinion, it's often a bad idea to construct routes dynamically because you can't easily look up and understand your route setup anymore, and it could lead to inconsistent URLs (e.g. if you used different URLs for different user agents). That said, I imagine it could sometimes be the most pragmatic approach.

Also, keep in mind that you can also reuse components by rendering them inside multiple route handlers. You don't have to reuse the route handlers themselves (e.g. if you wanted the same thing on /a and /b, you don't have to use the same handler; you could also just render the same thing from the two handlers).

**Comment by darreng** [comment]
The use case is for when routes are coming from the server DB. So there's a
Javascript array with the required information to create the routes, as in
RouteTable in the Stackoverflow answer.
