### ISSUE TITLE
1.0.0-beta3: routerWillLeave does not fire on page refresh.

### ISSUE THREAD

**Issue by aphillipo** [rackt/react-router#1701]
Clearly refreshing the browser (or clicking a 'real' link) should count as a transition if ever I saw one and the application should be allowed to decide what to do with that situation.

Maybe it's intended to do this but my implementation is wrong.  Sorry if that's the case!

**Comment by taurose** [comment]
> the application should be allowed to decide what to do with that situation

I don't think it's technically possible to do that (say cancelling or delaying a browser refresh). There is [beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) though, which will probably be used by the router soon. However, it merely allows passing a confirmation message string to the browser in order to abort the transition if the user agrees with it.

**Comment by aphillipo** [comment]
Yes, I'm using confirm dialogs for the 'Are you sure you want to loose information?' type stuff.

beforeunload I can actually implement myself easily enough and I suppose that works quite well in my case.  I'll close this!  Thanks again!
