### ISSUE TITLE
Different URL for the same component does not always trigger a remount.

### ISSUE THREAD

**Issue by aphillipo** [rackt/react-router#1703]
<Route name="projects/new/" path="projects/new/" component={ProjectForm} />
    <Route name="projects/edit/:project_id/" path="projects/edit/:project_id/" component={ProjectForm} />

So I click on one of the project URLs and then a "new" url and I do not get the component remounted.  Obviously changing the URL should always remount the new component.

My guess is that you guys are doing a clever check to say if the component is the same at these two points don't re render?

**Comment by taurose** [comment]
Do you mean re-render or re-mount?

You should get a re-render since the props have changed. But unless the component hierarchy changes (in your case it doesn't) you won't get any re-mounts. The rendering itself is done by React; the router simply assembles the route components and their props, and triggers re-renders whenever necessary (like any other stateful react component with a complex render function).

If you really want your components to re-mount you can use React's `key` functionality by hooking into `createElement` similar to [here](https://github.com/rackt/react-router/issues/1694#issuecomment-130085791). However, this will also cause your entire DOM to be re-rendered and all your component's state to be reset.

**Comment by aphillipo** [comment]
The second bit is exactly what I am looking for.  When changing from editing a project to creating a new one the dom should be rerendered.

**Comment by aphillipo** [comment]
I'd much prefer it if you could specify createElement on a route by route basis.

**Comment by ryanflorence** [comment]
> My guess is that you guys are doing a clever check

Nope, this is React being clever. If you want remounting then add keys.

**Comment by AGMETEOR** [comment]
@ryanflorence this saved me. I spent a day looking for a solution. kudos!
