### ISSUE TITLE
Client sided routing only works once 0.13.x

### ISSUE THREAD

**Issue by Teaflavored** [rackt/react-router#1769]
I'm having an issue where after i call router.run on the client after the page loads, only the first click that changes the url will fire the callback, the subsequent clicks do not fire the callback.

//routes.jsx
```
<Route handler={App} path="/">
    <Route name="test" path="/test/:id" handler={Test} />
    <Route name="tests" path="/test" handler={Tests} />
    <DefaultRoute name="home" handler={Home} />
</Route>
```
I'm using fluxible as well so on the client I rehydrate my app first, app.getComponent() is the route object since I create it with the routes
    var app = FluxibleApp( { component: routes } )
//client.js
```
    app.rehydrate(dehydratedState, function (err, context) {
		if (err) {
		}
		
		Router.run(app.getComponent(), Router.HistoryLocation, function (Root, state) {
			var RootComponent = fluxibleAddons.provideContext(Root,{
				getStore : React.PropTypes.func.isRequired,
				executeAction: React.PropTypes.func.isRequired
			});
			React.render(React.createElement(RootComponent, React.__spread({}, state, { context : context.getComponentContext()  })), document.getElementById(app.uid));
		});
	});
```

**Comment by taurose** [comment]
Never used fluxible, but I think your problem is that you're wrapping the router-provided `Root` component in a **newly created** HoC (`RootComponent`) each time the run callback fires. Due to React reconcilation, it'll re-mount the router component every time (and also re-create the whole DOM..). Since the router automatically stops when unmounted, this would explain why you're not getting any more calls. If I'm right, [this line](https://github.com/rackt/react-router/blob/0.13.x/modules/createRouter.js#L541) should be executed the second time you render.

Unfortunately, the 0.13 API doesn't really make it easy to fix this. Since the `Root` (component) argument is actually identical every time, one solution could be to create the HoC only on the first run.

```js
var RootComponent = null;
Router.run(app.getComponent(), Router.HistoryLocation, function (Root, state) {
  if (!RootComponent) {
    RootComponent = fluxibleAddons.provideContext(Root, {
      getStore : React.PropTypes.func.isRequired,
      executeAction: React.PropTypes.func.isRequired
    });
  }
  React.render(React.createElement(RootComponent, ...), ...);
});
```

**Comment by Teaflavored** [comment]
Thanks taurose, I will try this later and get back with results.

**Comment by Teaflavored** [comment]
I figured it out. Thanks to taurose, the Root component must be persisted so the router won't be stopped. Instead of providing the context at the root route level, I provided it in my main app handler
```
//app.jsx
var App = React.createClass({
	render: function () {
				return (
						<div> 
							<Navbar />
							<div id="mainContent" className="container" style={appCSS.mainContent}>
								<RouteHandler {...this.props}/>
							</div>
						</div>
					);
			}
});

App = fluxibleAddons.provideContext(App, {
        executeAction : React.PropTypes.func.isRequired,
        getStore : React.PropTypes.func.isRequired
    }
);
```

then in my route handlers, I define contextTypes to keep on grabbing the executeAction and getStore methods.
