### ISSUE TITLE
[1.0] Access router.transitionTo() outside component

### ISSUE THREAD

**Issue by cgrossde** [rackt/react-router#1895]
Is there a way to trigger `transitionTo` without being in a component? 

**Use-Case:** I'm currently writing a nw.js app which has a tray menu. This tray menu is created with nw.js and not part of the React UI. I want to show and switch to a specific part of my React App from my tray menu but I need access to the transitionTo method. I could export it out of a component somehow but that seems like a hack. Or should I just use `window.location.href`?

**Comment by ryanflorence** [comment]
added a doc :)

https://github.com/rackt/react-router/blob/95094769caca201b8e9afe68ff3d6cb4ff280fac/docs/advanced/NavigatingOutsideOfComponents.md

**Comment by cgrossde** [comment]
Thank you! :)

**Comment by levbrie** [comment]
I think it would be really nice to be able to still call transitionTo outside of components.  What was the reasoning behind removing it?  Perhaps I'm missing something, but to me, it seems reasonable that you might want to transitionTo (or replaceState as it's now called) from within any number of non-component services, but perhaps I'm missing something.  Either way, it might also be nice to be able to access the history lib from within react-router rather than having to install it as well, especially since it's already there and since if you wanted to configure it in some way it would certainly be for the purposes of routing.  In any case, this aside, the new release is looking really awesome!

**Comment by CreativeManix** [comment]
Followed as per the document, the URL changes to new url, however the UI is not updated!, When I use <Link/> everything is good
