### ISSUE TITLE
Please clarify usage with ES6 classes

### ISSUE THREAD

**Issue by robotvert** [rackt/react-router#1904]
Trying out 1.0.0-rc1 and as many others I'm running into the "how to use transitionTo now?" issue.

Up until now, using classes you'd get the router from the context and call transitionTo on this:

```javascript

class Dummy extends React.Component {
  constructor(props, context) {
    this.router = context.router;
  }
  
  someFn() {
    this.router.transitionTo("/some/path");
  }
}

Dummy.contextTypes = {
  router: React.PropTypes.object.isRequired
};
```

I don't know whether it's the proper way or not but it worked so far and was simple enough.

It *seems* the new way is "simply use the History mixin!" but AFAIK you can't use mixins with ES6 classes, can you?
If react-router is not compatible with ES6 classes IMHO it should be the very first line of the README.

**Comment by gaearon** [comment]
I think checking out [the source of HistoryMixin](https://github.com/rackt/react-router/blob/bb645ee84e6e84936d5fe12ee6e0e4b01243a3f3/modules/History.js#L5-L9) should give you a good idea. Now `history` is what's in context, instead of `router`. For ES6 classes, you can either keep using `context` (but with `history`) or [keep history in a singleton outside components](https://github.com/rackt/react-router/blob/master/docs/advanced/NavigatingOutsideOfComponents.md).

**Comment by ryanflorence** [comment]
https://github.com/rackt/react-router/blob/fe9358adc864c556afff6fd472476ab84ce2d7d9/docs/api/History.md#but-im-using-classes

**Comment by ryanflorence** [comment]
> If react-router is not compatible with ES6 classes IMHO it should be the very first line of the README.

:laughing: 

```
# THIS LIBRARY USES MIXINS

## React Router
```

That would be hilarious.

**Comment by robotvert** [comment]
Thanks for the swift docs update.

cc #1798 & #1841 people.
