### ISSUE TITLE
Lifecycle Mixin (transitions example)

### ISSUE THREAD

**Issue by vn38minhtran** [rackt/react-router#1930]
I thing when i click `ok` on `Confirm Box` or click on the dashboard link without input (empty string) it will transition to 'Dashboard' but nothing happen.

**Comment by ryanflorence** [comment]
![image](https://cloud.githubusercontent.com/assets/100200/9851896/936e1724-5ab8-11e5-9ac0-bafb076a1451.png)

confirmed ... wonder what's wrong ...

**Comment by ryanflorence** [comment]
Looks like this line of code is bailing out of the transition for some reason:

https://github.com/rackt/history/blob/master/modules/createHashHistory.js#L92-L93

**Comment by vn38minhtran** [comment]
I tried with `BrowserHistory` but still do not work.

**Comment by ryanflorence** [comment]
same bail out there too: https://github.com/rackt/history/blob/master/modules/createBrowserHistory.js#L64-L65

**Comment by taurose** [comment]
> Looks like this line of code is bailing out of the transition for some reason:

That line is fine. It returns early for POP, because POP transitions change the URL immediately. For PUSH&REPLACE we need to change the URL manually once the transition finishes.

As far as I can tell the problem is here: https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L214 . `state` reflects the old location in contrast to what the comment suggests. With transition hooks, `match` doesn't get to the point where it updates `state` since it uses `partialNextState` (https://github.com/rackt/react-router/blob/master/modules/useRoutes.js#L42).

My guess is that that branch should update `state` as well:

```js
  function match(location, callback) {
      if (partialNextState && partialNextState.location === location) {
        // Continue from where we left off.
        finishMatch(partialNextState, function (err, nextLocation, nextState) {
              if (nextState)
                state = nextState
              callback(err, nextLocation, nextState)
            });
      } else { ... }
```

**Comment by mjackson** [comment]
The goal was for `useRoutes.match` to be a pure function, but `useRoutes.listen` would be the one to mutate state.

**Comment by bunkat** [comment]
Is there any workaround to this?  I'm unable to get `history.pushState`, history.replaceState`, nor `history.transitionTo` to actually load the component at the new url.

**Comment by jeremejevs** [comment]
I had to downgrade to `beta4`.

**Comment by jasonlfunk** [comment]
This is happening for me too. :(

**Comment by jasonlfunk** [comment]
I've found that wrapping the `pushState` call in a timeout seems to fix the problem. I'm not sure why, but so far so good.

```
window.setTimeout(function() {
    this.props.history.pushState(null, '/protected');
}.bind(this), 500);
```

**Comment by jquense** [comment]
hit this as well. any work around, or idea where the issue is to PR?

**Comment by jasonlfunk** [comment]
As far as I can tell... the issue comes in when you attempt to do a transition in the middle of a state change loop. I've wrapped my transitions in a `setTimeout` when I need to transition in lifecycle methods and it seems to work for now. It's definitely a hacky work-around though.

**Comment by jquense** [comment]
I didgged in as much as I could and @taurose seems to be right on the money, `partialNextState` is never actually processed into `state`

**Comment by bunkat** [comment]
Is there going to be an rc2 soon that includes this fix?

**Comment by schnerd** [comment]
@mjackson your fix looks good, but there might an unintended side effect.

Server rendering currently utilizes `useQueries.match`, and since that no longer mutates state, calls to `history.isActive` on the server will no longer return the correct value (hence [server rendering - renders active Links as active](https://github.com/rackt/react-router/blob/master/modules/__tests__/serverRendering-test.js#L96) failing in current build). One potential fix for this might be to transition the memory history to the correct location in `match`, as I've done here https://github.com/schnerd/react-router/commit/01bd815e893950c3be6345686ffadd648ecd525f. If that looks good, or if you have other ideas on how this might be solved, let me know and I can submit a PR.

As a quick aside, the removal of null arguments in [be37196](https://github.com/rackt/react-router/commit/be3719661b5714a15d3e70f50503450caddc3ee8#diff-58118d23f5f2a5fe2011781eb16cb7f2L55) also breaks the test [server rendering - sends null values when no routes match](https://github.com/rackt/react-router/blob/master/modules/__tests__/serverRendering-test.js#L108). 

thanks for all your work on the router

**Comment by rubencodes** [comment]
Was this fixed? I think I'm running into this issue (R-R 1.0.3, using createBrowserHistory) where I attempt to transition state using this.history.replaceState(null, '/myPage') and the URL updates but the app state doesn't...

**Comment by earaujoassis** [comment]
I guess I'm running after the same issue described by @rubencodes :(
