### ISSUE TITLE
onLeave rc-1

### ISSUE THREAD

**Issue by boyswan** [rackt/react-router#1938]
I'm calling a function on the client to render data before the next route. This worked in previous versions, however doesn't seem to using 'onLeave' in the latest rc-1.

Router:
`````javascript
export default (renderRoute) =>
	<Route component={App}>
		<Route path="/" component={Home} onLeave={renderRoute}/>
		<Route path="page1" component={Page1} onLeave={renderRoute}/>
		<Route path="admin" component={Admin}  onLeave={renderRoute}/>
	</Route>
`````

Client:

`````javascript
const initState = immutifyState(window.__INITIAL_STATE__)
const history   = createHistory();
const logger    = createLogger({level: 'info', collapsed: true });
const store     = applyMiddleware(thunkMiddleware, logger )(createStore)(reducer, initState);

const route = renderRoute((nextState, transition, done) => {
 // nextState returns 'undefined' using 'onLeave'
  fetchComponentData(store.dispatch, nextState.routes.map(b => b.component), nextState.params)
  .then(() => done())
  .catch(err => console.log(err))
})

ReactDOM.render(
  <Provider store={store}>
    <Router children={route} history={history}/>
  </Provider>,
  document.getElementById('app')
)
`````

It works correctly if I use 'onEnter', however 'onLeave' returns undefined for the renderRoute arguments. Has the onLeave prop changed?

**Comment by ryanflorence** [comment]
why would you do this in `onLeave` instead of `onEnter`?

**Comment by ryanflorence** [comment]
But yes, `onLeave` is no longer asynchronous since the only valid use-case is to prevent navigation, which is a synchronous operation (its identical to `onBeforeUnload`)

You should be able to just do an `onEnter` of your root route, seems like the right place anyway.

**Comment by Traviskn** [comment]
One reason to do this in an isomorphic app is to avoid making duplicate data fetching calls on the server.   I found this approach originally recommended in [this tutorial](https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4) and found it fairly reasonable.  I'm fairly sure that @boyswan's example was also inspired by the linked tutorial.

As far as I understand, if you make a request for data in an onEnter hook on the server (or the component's componentWillMount method) it won't work because the response gets sent back to the client before the asynchronous request can finish.

To solve this problem on the server we do as recommended in react-router's advanced server rendering docs and use the renderProps.components to find each component's data requirements, load the data, and only reply with the server rendered route once the data comes back. Here's a pseudo code example (see the comments):

```javascript
import { renderToString } from 'react-dom/server'
import { match, RoutingContext } from 'react-router'
import routes from './routes'
import store from './store'
import fetchComponentData from './store/utils'

serve((req, res) => {

  match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
    if (error) {
      res.send(500, error.message)
    } else if (redirectLocation) {
      res.redirect(302, redirectLocation.pathname + redirectLocation.search)
    } else if (renderProps) {
      // fetchComponentData will loop over the components looking for static load methods
      fetchComponentData(store.dispatch, renderProps.components, renderProps.params)
        .then(() => {
        // Now our data is loaded into our store and our components can render properly, plus we can hydrate the state
         const initialComponent = renderToString(<RoutingContext {...renderProps} />)
         const initialState = store.getState()
         const HTML = `
          <html>
             <head>
                <script>window._state = ${initialState}</script>
             </head>
             <body>
                <div id=app>${initialComponent}</div>
             </body>
         </html>`
         res.send(200, HTML)
        })
        .catch(err => res.send(500, err))
    } else {
      res.send(404, 'Not found')
    }
  })
})
```

Now the problem is that we don't have anything in place to call our component's static load methods on the client.  Even if I isomorphically render route A with all the required data, when I navigate client side to route B it will be empty of its data.  It would be great to put our fetchComponentData method into our route's onEnter hooks to call our component's static load method, except that it would cause duplicate data fetching calls on the server, which doesn't seem clean.

We know for sure however that a route's onLeave hook will never get called on the server and only on the client, so it is actually a perfect place to fetch data for the next component client side as shown in @boyswan's example.

Another solution is to put data requests into the componentDidMount method which we also know will not get called on the server.  However, this means that I will have a static load method and a componentDidMount method with duplicate code, which doesn't seem ideal.

Relay will of course help solve the problem of isomorphic rendering and declarative data requirements on the component, but not everyone is ready to implement a GraphQL server.

I hope my explanation makes sense, I'm still struggling a bit figuring out how to write universal apps.  Do you have any recommendations?  It seems we need to fetch data on the server one way, and then implement data fetching on the client another way.  In both client and server cases, the router seems like a perfect place to do it all if the API will let us.

**Comment by taion** [comment]
It really depends on e.g. which Flux framework you're using - they'll generally have different recommendations for how to structure data fetching. In general you have to do something like the example or use a render loop to make things work on the server, but making this work without repeating code on the client is really more a function of the patterns available to you for structuring your code to call the same logic from multiple places.

**Comment by Traviskn** [comment]
In my case I happen to be using [Redux](https://github.com/rackt/redux).  Regardless of which flux implementation you use, there is still the issue of duplicate data fetching requests.

When I server render a page the route's onEnter hook will get called on the server and then again on the client.  Both calls are unnecessary as I've already fetched the data server side as shown in my example.

The componentDidMount hook will also get called as soon as react code bootstraps itself on the client, which is also an unnecessary request.

But I still need some kind of lifecycle hook to load data while I am navigating to new routes on the client that won't be server rendered.

The only hook that won't result in duplicated data requests is the onLeave hook.  Nearly any route could be either server rendered (if it's the user's first request or they refresh the page), or client rendered if the user has already loaded my react app.  When the onLeave hook is called I know that the user is navigating to a new route on the client.  With onEnter and componentDidMount that isn't the case, and for a server rendered page data fetching will be duplicated.

I feel like this is a valid use case for asynchronous data fetching in the onLeave hook.

As I think about it though there are alternatives, like tracking some isLoaded state in my store and then checking in componentDidMount to make sure I'm not duplicating a fetch for data that's already loaded.

**Comment by boyswan** [comment]
I used this as my onEnter function, which prevents it being called twice on page load:

`````javascript
let route = renderRoutes((nextState, transition, done) => 
  nextState.location.action !== 'POP' ?
    fetchComponentData(store.dispatch, nextState.routes.map(b => b.component), nextState.location.pathname)
    .then(()=>done())
    .catch(err => console.log(err))
  : done()
)
`````

**Comment by taion** [comment]
That's not quite right - we don't want to override `onLeave` at this point.

In general async props are a bit tricky - you can take a look at what's been done previously, but blocking the transition completely is not how we want to encourage people to do it, I don't think.

**Comment by Traviskn** [comment]
Yes I agree that we don't want to block the transition on the client because that would result in a non-responsive UI. My component is subscribed to the redux store so we can go ahead and transition before the data fetch finishes, probably show a loading indicator, and when the data gets to the store it will be pushed to the component to re-render.

A slightly adjusted version of @boyswan's function seems to do the trick for me, I hadn't thought to test for the action type 'POP'

```javascript
function onEnter(nextState, transition, done) {
    if (nextState.location.action !== 'POP') {
      const params = nextState.params;
      const components = nextState.routes.map(route => route.component);
      fetchComponentData(store.dispatch, components, params);
    }
    done();
  }
```

But again, why not allow this to be done in an onLeave hook by giving it the nextState argument?  It doesn't even need to be asynchronous to do the trick, it just needs to know the nextState

**Comment by taion** [comment]
Your data fetching in this case is _logically_ tied to entering the new route, not to leaving the old one. You shouldn't model it with a hook that runs on leaving the old route.

**Comment by Traviskn** [comment]
That makes sense, checking for the pop action before loading data seems to be a good solution.  Thanks @taion and @boyswan for your help!

**Comment by ghempton** [comment]
Yes, `onBeforeUnload` is synchronous, but why do we have to enforce parity with that API? In my opinion, using a native confirm dialog is the last resort option. In our case, it is desirable to use an entirely custom dialog.
