### ISSUE TITLE
Default route nested in anonymous route no longer working

### ISSUE THREAD

**Issue by jscheid** [rackt/react-router#1939]
It would be nice if this worked in 1.0:
```js
    <Route path="/(:locale)">
      <Route path="login" component={Login}>
      <Route component={App}>
        <IndexRoute component={Dashboard} />
        /* more routes here */
      </Route>
    </Route>
```
In 0.13 I had it working like so:
```js
    <Route handler={Locale} path="/:locale?">
      <Route name="login" handler={Login} />
      <Route handler={App} path="">
        <DefaultRoute name="dashboard" handler={Dashboard} />
      </Route>
    </Route>
```
But now, path `/en/` gets resolved to `Locale` rather than `Dashboard`.

I've tried various ways of rearranging the routes but can't seem to get it to resolve to `Dashboard` no matter what I try. Perhaps I'm missing something?

**Comment by ryanflorence** [comment]
can you list some urls and which components you expect to be rendered? I can't quite follow what is expected.

**Comment by jscheid** [comment]
I'd expect `/en/` to match the IndexRoute but instead it only matches the outermost route. Essentially it would be nice if it could do a "deep" or "greedy" match, following any anonymous nested routes. Sorry if I'm not explaining this very well, I hope this makes more sense?

**Comment by flocks** [comment]
I think this is the behaviour I was trying to explain in https://github.com/rackt/react-router/issues/2037 

Suppose we have the following layout

![screen shot 2015-09-25 at 17 39 41](https://cloud.githubusercontent.com/assets/944835/10104641/05f64866-63ab-11e5-92e7-38dd1e5dc2c7.png)
the header is always visible. If we go to /login, the content ( with the menu ) disappears, to show the login form.
the route "/" should displays the Content with SubHome1 as default page.

I managed to implement this in react-router 0.13 doing 
```javascript
<Route handler={App} name="app" path="/">
    <DefaultRoute handler={Home} />
    <Route handler={Home} name="home" path="/">
            <Route handler={subHome1} name="subHome1" path="/" />
            <Route handler={subHome2} name="subHome2" path="/subHome2" />
      </Route>
      <Route handler={Login} name="OtherPage1" path="/login" /                
```
But I can't make it work with react-router 1. Is it still even possible ?

Sorry @jscheid if it's unrelated but I think it could be.

**Comment by jscheid** [comment]
It looks like the same issue to me @flocks

**Comment by knowbody** [comment]
@jscheid it seems like you are trying to do similar thing to #2159

**Comment by jscheid** [comment]
@knowbody no, this is different from #2159. I guess the locale part is a bit of a red herring. Instead, the issue seems to be that index routes won't be matched when nested inside anonymous routes (by which I mean routes without a path attribute.)

I *think* the problem is here: https://github.com/rackt/react-router/blob/e738c88a05a537d4b93b5946097eb2629598fa74/modules/matchRoutes.js#L56 which will stop as soon as the path so far matches, which sometimes is too early.

All this being said, I've now worked around the issue by getting rid of anonymous routes (using outer components inside the nested routes instead), so feel free to close this. However, I still think it would be useful if this worked (like it did in 0.13).

**Comment by ekaradon** [comment]
@jscheid, I think that I am facing the same issue. I have something like that: 
```jsx
    <Route path='/' component={App}>
        <IndexRoute component={Authent}
                    onEnter={(location, replaceWith) => authenticated(location, replaceWith)}>
            <IndexRoute component={Dashboard} />
            <Route path='dashboard' component={Dashboard}>
                <Route path='add/?' component={AddWidget} />
            </Route>
            <Route path='account/?' component={Account} />
            <Route path='*' component={NotFound}/>
        </IndexRoute>
        <Route path='login(/:email)' component={Login} />
        <Route path='register/?' component={Register} />
    </Route>
```

However, I do not see the dashboard appearing.

**Comment by jscheid** [comment]
@ekaradon as far as I understand you're not supposed to nest anything inside an `IndexRoute` but yes, if you were to restructure it to use a pathless `Route` it looks like you would run into the same issue.

**Comment by danieljuhl** [comment]
I'm also facing this issue, migrating from 0.13.3 to 1.x.
I'm trying to render 'App > List > Home' for the root of the application ('/').

I've tried to following, with no luck.

```js
<Route path='/' component={ App } history={ history }>
  ...
  <Route component={ List }>
    <Route component={ Home }>
  </Route>
  ...
</Route
```

```js
<Route path='/' component={ App } history={ history }>
  ...
  <Route component={ List }>
    <IndexRoute component={ Home }>
  </Route>
  ...
</Route
```

```js
<Route path='/' component={ App } history={ history }>
  ...
  <Route component={ List }>
    <Route path='/' component={ Home }>
  </Route>
  ...
</Route
```

```js
<Route path='/' component={ App } history={ history }>
  ...
  <Route path='/' component={ List }>
    <Route path='/' component={ Home }>
  </Route>
  ...
</Route
```

**Comment by knowbody** [comment]
This just doesn't make sense... If you want to do that why you just don't put `Home` and `List` inside and `App` component and then have a route like:

```js
<Route path='/' component={ App }>
</Route>
```

**Comment by danieljuhl** [comment]
@knowbody I does make sense, but I might have left too much out.

```js
<Route component={ List }>
  <Route path='/area' component={ Area } />
  <Route path='search' component={ Search } />
  <Route path='/type' component={ Type } />
  <Route path='/' component={ Home } />
</Route>
```

`App` contains the application layout (header, footer, etc) and `List` contains layout for the content part, when it is a list page, which there is several versions of, which only affect a minor part of the whole content.

**Comment by knowbody** [comment]
@danieljuhl now it's a bit more clearer :)

If I understood correctly this is what you look for (quick example):

```js
import React, { PropTypes, Component, ContextTypes } from 'react';
import createBrowserHistory from 'history/lib/createBrowserHistory';
import { Router, Route, Link, IndexRoute } from 'react-router';

let history = createBrowserHistory();

class Navigation extends Component {
  render() {
    return (
      <div>
        <ul>
          <li><Link to='/'>Home</Link></li>
          <li><Link to='/search'>Search</Link></li>
        </ul>
      </div>
    );
  }
};

class Search extends Component {
  render() {
    return <h3>Search</h3>;
  }
}

class Home extends Component {
  render() {
    return <h3>Home</h3>;
  }
}

class List extends Component {
  render() {
    return (
      <div>
        <h3>List</h3>
        {this.props.children}
      </div>
    );
  }
}

class App extends Component {
  render() {
    return (
      <div>
        <h1>App</h1>
        <Navigation />
        {this.props.children}
      </div>
    );
  }
}

export default class Root extends Component {
  render() {
    return (
      <Router history={createBrowserHistory()}>
        <Route component={App}>
          <Route path='/' component={List}>
            <IndexRoute component={Home} />
            <Route path='search' component={Search} />
          </Route>
        </Route>
      </Router>
    );
  }
}
```

**Comment by knowbody** [comment]
also @jscheid and @flocks could you tell me if this issue can be closed, because this issue starting to be like an open ended question...

**Comment by danieljuhl** [comment]
@knowbody Spot on, besides I have a bunch of other routes, so that `path='/'`should be located on the first (and outer-most) route. Hence the `...` in the initial comment.

**Comment by ekaradon** [comment]
@knowbody : I don't think so because it seems today impossible to manage nested default route like below. 

```jsx
<Route path='/' component={App}>
    <Route component={Authent}
                onEnter={(location, replaceWith) => authenticated(location, replaceWith)}>
        <IndexRoute component={Dashboard} />
        <Route path='dashboard' component={Dashboard}>
            <Route path='add/?' component={AddWidget} />
        </Route>
        <Route path='account/?' component={Account} />
    </Route>
    <Route path='login(/:email)' component={Login} />
    <Route path='register/?' component={Register} />
</Route>
```
Here the component *Authent* will never be called. 

For me, the issue is real and the fact that people come here to ask questions comes from that something seems like missing.

**Comment by knowbody** [comment]
@ekaradon I hear you all. and as you can see I'm trying to help you all as well.

First of all instead of just throwing your routes here and saying this does not work for me, doesn't make it easy for me to help you. Please explain what are you expecting to get. Looking on what you showed above my answer is simple as: your route with the `Authent` component does not have a path hence can't be matched and is not being displayed. Although I know that's not the answer you are looking for.

**Comment by knowbody** [comment]
@danieljuhl could you also explain in steps what are you expecting?

something like:
1. navigating to `/` gives me `App`, `List` and `Home` component
2. navigating to `/search` would keep `App`, but will replace...

that will be very helpful for me to understand it properly. Thanks

**Comment by ekaradon** [comment]
Well, what I want to do is having nested components which are activated by default if no routes are specified. 

For example, by default my url will be: my.website.com 
And I Want to activate the following components -> App > UserAuthenticated > HomeUser
But today, I only get -> App -> User_authenticated working only if I am using IndexRoute and which does not support nesting route and so prevent me from rendering HomeUser

**Comment by knowbody** [comment]
@ekaradon no worries :)
I understand that first part, what happens after that, which components should always be mounted which ones needs changing?

**Comment by ekaradon** [comment]
I think that the best way would be to be able to specify a default route to be used when no path is remaining. The default route could be a route without a path. 
```jsx
<Route component={myDefaultChoice} />
```
So while we have a path, we are following it, but as soon as the current path evaluated is empty, we have to look for a default route. If none we stop there, otherwise we continue on the default route. 

For example, with the following URL: 
my.website.com/dashboard/activities

We would first be looking for the master route '/' and next to the Auth Component which ensure the user is authenticated, then to the dashboard. We would then search for the route 'activities' (which could be a module responsible for some menu about activities) and then would go for the default module which just present the last activities. 
 
I think that the following routes should be able to complete this task. 
```jsx
    <Route path='/' component={App}>
        <Route component={Auth}>
            <Route path='dashboard' component={Dashboard}>
                <Route path='activities(/)' component={ActivitiesMenu}>
                    <Route component={LastActivities} />
                    <Route path='other' component={OtherComponent} />
                </Route>
                <Route path='other' component={OtherComponent} />
            </Route>
            <Redirect from='' to='/dashboard' />
        </Route>
        <Route path='other' component={OtherComponent} />
    </Route>
```

A complementary/other solution would be to make Redirect able to interpret blank segment path? Maybe the simplest solution. I am not sure however about this one, still learning the new API from 1.0. :)

**Comment by knowbody** [comment]
@ekaradon in your case, why wouldn't you use `onEnter` for doing the user validation? (see the [auth-flow example](https://github.com/rackt/react-router/tree/master/examples/auth-flow))

**Comment by ekaradon** [comment]
@knowbody Yes, indeed, but I prefer to say that all these roads need to have the user logged in by grouping them below a component (which checks that the user has a valid session) rather than setting the onEnter of each component which require the user to be authenticate.
Imagine I have these routes when logged in:
 - dashboard
 - account
 - messages
 - news
 - activities
I think it is better to create a section login_required rather than calling for each of these routes the event onEnter.

It does not have to modify my URL because it is not bound to an action that the user wants to do. It is just an internal logical rule. So it has to be visible from the developer side, minimizing the risks of giving access to not authorized sections of the website, however it has to be transparent for the user. 

Rephrasing @jscheid we had before the defaultRoute which should be replaced by the Route without a path. It would be a pity to not be able to use the vertical hierarchy layout that xml offers for rights management, no?

**Comment by knowbody** [comment]
but this is what `onEnter` will do for you. You just set it up on your parent Route and no matter if you hitting `/` or `/news` it will trigger the `onEnter`.

**Comment by ekaradon** [comment]
Not sure to understand, how do I avoid this?
```jsx
<Route path='/' component={App}>
    <Route path='login(/:email)' component={Login} />
    <Route path='register/?' component={Register} />
    <Route path='dashboard' component={Home} onEnter={(l, r) => auth(l, r)} />
    <Route path='news' component={News} onEnter={(l, r) => auth(l, r)} />
    <Route path='account' component={EndUserClient} onEnter={(l, r) => auth(l, r)} />
    <Route path='activities' component={EndUserClient} onEnter={(l, r) => auth(l, r)} />
</Route>
```

**Comment by knowbody** [comment]
```js
<Route path='/' component={App} onEnter={(l, r) => auth(l, r)}>
```

**Comment by ekaradon** [comment]
Indeed, the problem is solved but in my case, my auth app is also making appears the user menu with the logout button for example...

**Comment by mjackson** [comment]
@ekaradon You can use a route that doesn't consume any portion of the URL path. Put your `onEnter` on that route.

```js
<Route onEnter={auth}>
  <Route path="dashboard" component={Home} />
  // ...
</Route>
```

**Comment by ekaradon** [comment]
And how do I enter in this route without any path?

**Comment by danieljuhl** [comment]
@knowbody  I expect `/` to use `App > List > Home` and `/search` to use `App > List > Search`. If I can accomplish in another way that's fine, but I can't figure out any method that works.

**Comment by jscheid** [comment]
@danieljuhl I believe you can use the same workaround that I've settled on:

In `Home.render`: `return <App><List>...</List></App>`.
Same for Area, Search, Type.
Basically, collapse the route hierarchy. Once it's flat, IndexRoute should work again.

Not exactly DRY but should do the job... hope this helps.

I think to get the underlying issue recognized, somebody will have to write a test case that demonstrates the problem.

**Comment by danieljuhl** [comment]
@jscheid my problem in your solution is that I have other routes on the route, which does not use the list component. But I could do something like it, by wrapping each of the sub routes with a lost, though not as nice as it could have been and was with 0.13.3

**Comment by ekaradon** [comment]
Okay, I have finally found an ugly hack which allow me to do what I want. I am just misleading route pattern feature. 

Here is what I do:
```jsx
<Route component={TopLevel} onEnter={auth_check}>
    <Route path='(/)' component={CheatingAppWithSomeMenu}>
        <IndexRoute component={RealDashboard} />
        <Route path='/dashboard/'>
            <Route path='add(/)' component={DashboardCanBeExtended} />
        </Route>
        <Route path='/others'  component={Others} />
    </Route>
    <Route path='login(/:email)' component={Login} />
    <Route path='register(/)' component={Register} />
    <Route path='*' component={NotFound} />
</Route>
```
I have noticed that path='' does not exist, but I have also noticed that you can make it optional using "()" operator. 

But this is where the weird thing occurs. Like I am in an optional path, I have to **add the optional path before each of my new routes** in order to make them recognized. Here, it is just the "/", but it could be more like "/home/dashboard/" if you define a path like "(/home/dashboard)".

For example: 
```jsx
<Route component={TopLevel} onEnter={auth_check}>
    <Route path='(/)' component={CheatingAppWithSomeMenu}>
        <Route path='dashboard' />
    </Route>
</Route>
```
The route my.website.com/dashboard can never be reached (while it should be). 

An other solution would be to write your like:
```jsx
<Route component={TopLevel} onEnter={auth_check}>
    <Route path='(/)' component={CheatingAppWithSomeMenu}>
        <IndexRoute component={RealDashboard} />
    </Route>
    <Route path='/' component={CheatingAppWithSomeMenu}>
        <Route path='/dashboard/'>
            <Route path='add(/)' component={DashboardCanBeExtended} />
        </Route>
        <Route path='/others'  component={Others} />
    </Route>
</Route>
```
This will also works. 

However, I think that all these workaround look like bugs themself (at least the need to duplicate the CheatingAppWithSomeMenu part). And I think that it is not the proper way to solve the initial issue which is the disappearing of DefaultRoute. Furthermore, write path='(/)' is really clumsy.
But well, until now, this is the only solution I have found.
