### ISSUE TITLE
Docs for 0.13

### ISSUE THREAD

**Issue by scothis** [rackt/react-router#1942]
The docs for 0.13 seem to no longer be published. The old location redirects into the the github repo for 1.0 docs.

Please give me something better than http://webcache.googleusercontent.com/search?q=cache:ES06hJ6AhaQJ:https://rackt.github.io/react-router/+&cd=1&hl=en&ct=clnk&gl=us

**Comment by mjackson** [comment]
For now, you can find these docs [on GitHub in the 0.13.x branch](https://github.com/rackt/react-router/tree/0.13.x/doc). It's not the prettiest format, because these docs were never intended to be browsed using GitHub's interface. But all the content is there.

In the 1.0 push, we decided to kill the website and just rely on GitHub for publishing our docs. We definitely could have made a better effort to preserve our old website URLs, though. I'd welcome a PR to the `gh-pages` branch that just sets up a bunch of redirects to the corresponding URLs on GitHub.

**Comment by crisward** [comment]
That branch doesn't exist anymore. Trying to update an old app and it's proving a bit difficult without the old docs. Thanks.

**Comment by YasserKaddour** [comment]
You can found the docs here https://github.com/ReactTraining/react-router/tree/v0.13.6/doc

**Comment by crisward** [comment]
Many thanks!

**Comment by ESTEBANMURUZABAL** [comment]
Hello guys! Could you show me how did you upgrade your react-router 0.13 code please? I am trying to do the same like this: 
Router.run(app.getComponent(), req.originalUrl, async function (Handler, state) {
to 
ReactDOM.render(app.getComponent(), req.originalUrl, async function (Handler, state) {

but I am getting this error: Target container is not a DOM element.
Could you point me out please what I am doing wrong?
