### ISSUE TITLE
Whole application re-renders on every route transition?

### ISSUE THREAD

**Issue by BreakitMedia** [rackt/react-router#1995]
Using Fluxible (fluxible.io) and the modified eample over here https://github.com/jeffreywescott/flux-examples/tree/upgrade-to-react-router-1.0/react-router - I notice that changing between "Home" and "About" keeps re-rendering the whole application.

I'm experiencing the same issue in my own application after migration from 0.13 -> 1.0.0-beta3 (I don't know if this is the case in RC-1, since I rely on the Router.run to work). How can it be avoided / what am I doing wrong? This was not the cause using the `<RouteHandler/>`.

**Comment by taurose** [comment]
I think the problem is here: https://github.com/jeffreywescott/flux-examples/blob/upgrade-to-react-router-1.0/react-router/create-element.js#L8

`provideContext` creates a new (HoC) component every time it's called. Since `createElement` is called every time the route components are re-rendered, this will effectively replace the route components on every re-render, thus causing the behavior you described.

I think the solution would be to use `provideContext` on the route components before starting the router, e.g. directly in the routes definition, and then only use `createElement` to pass the additional `context` prop.

**Comment by BreakitMedia** [comment]
You are right, I have modified my code now and switched to `1.0.0-rc1` and it works surprisingly well. Thank you for the feedback; I'll post my solution here in a moment for others with the same issue.
