### ISSUE TITLE
react-router is not displaying correct pages

### ISSUE THREAD

**Issue by vladzzag** [rackt/react-router#2005]
Hello! I have troubles with routing..
```react-router``` version 0.13.3.
Here is my routes:
```js
import React from "react";
import { Route } from "react-router";
import SamplePage from "./components/sample_page";
import SeriesPage from "./components/series_page";
import AnalyzePage from "./components/analyze_page";


let routes = (
  <Route path="/" handler={SamplePage}>
    <Route name="series" handler={SeriesPage} />
    <Route name="analyze" handler={AnalyzePage} />
  </Route>
);


export default routes;

```

And main.js:
```js
import App from "./components/app";
import React from "react";
import injectTapEventPlugin from "react-tap-event-plugin";
import { create, HashLocation } from "react-router";
import routes from "./routes";


window.React = React;
injectTapEventPlugin();


let Router = create({
  routes: routes
});


Router.run((Handler) => {
  React.render((
      <Handler />
  ), document.body);
});

```

So, when I go to page "#/series" or "#/analyze", then "#/" is displayed, not "#/series" and "#/analyze".

**Comment by taurose** [comment]
> So, when I go to page "#/series" or "#/analyze", then "#/" is displayed, not "#/series" and "#/analyze".

Do you mean `#/` is displayed in the page (ie. your `SamplePage` component) or in the URL bar? In the former case, you should know that react-router doesn't map a URL to a single handler like other routers do, but to to a set  of handlers (a branch in your route config). In your case

* `#/` -> `<SamplePage>`
* `#/series` -> `<SamplePage>`, `<SeriesPage>`
* `#/analyze` -> `<SamplePage>`, `<AnalyzePage>`

You have to use `<RouteHandler>` ([docs](https://github.com/rackt/react-router/blob/0.13.x/doc/03%20Components/RouteHandler.md)) inside `<SamplePage>`s render() in order to render the other handlers.

Also see the [overview guide](https://github.com/rackt/react-router/blob/0.13.x/docs/guides/overview.md).

**Comment by vladzzag** [comment]
@taurose thank you for your help! This solved the problem.
