### ISSUE TITLE
Async onEnter's have complicated stack traces

### ISSUE THREAD

**Issue by wonnage** [rackt/react-router#2007]
If you use promises in async onEnter, you wind up having to catch twice, e.g:

```
makeNetworkRequest()
  .then(function() { doStuff(); callback(); })
  .catch(function(err) { callback(err); })
  .catch(function(err) { renderErrorMessage(); })
```

This is because the entire process of rendering is triggered by calling `callback`. Without the second catch, any rendering errors would reject the promise, which you have no further access to since react-router discards it. Hopefully you're using a promise library that tells you of unhandled promise rejections. 

I wonder if this could be made safer - calling `callback` should make the route transition happen, but the subsequent rendering happens in a separate execution context, so that its errors bubble up to the top.

**Comment by taurose** [comment]
I think your example should be

```js
makeNetworkRequest()
  .then(function(){ doStuff() })
  .then(function() { callback(); }, function(err) { callback(err); })
  .catch(function(err) { renderErrorMessage(); })
```

Otherwise, you might end up calling `callback` twice.

I'd say the issue with error swallowing is one of the bigger shortcomings of the promise spec. In some promise libraries you will find `promise.done`, with which you would do

```js
makeNetworkRequest()
  .then(function(){ doStuff() })
  .done(function() { callback(); }, function(err) { callback(err); })

// or
makeNetworkRequest()
  .then(function(){ doStuff() })
  .then(function() { callback(); }, function(err) { callback(err); })
  .done()
```

It's not part of the spec, but I've seen some discussions, e.g. [here](https://github.com/promises-aplus/unhandled-rejections-spec/issues/5). Apparently, they leave it up to the browser to report unhandled, rejected promises.

You could achieve the same with `setTimeout`:

```js
makeNetworkRequest()
  .then(function(){ doStuff() })
  .then(
    function() { setTimeout(function() { callback(); })}, 
    function(err) { setTimeout(function() { callback(err); })}
  )
```


> any rendering errors would reject the promise, which you have no further access to since react-router discards it

I wouldn't say the router discards it. The router provides a nodejs style callback interface, and you're using promises for your async operations which effectively wrap your callback invocations in a silent try-catch block. You would run into the same problems with other libraries that use callbacks. 

Think about it this way: whenever you create a promise, you should either pass it on to some instance that handles its result (can't do that here since the router doesn't use promises), handle and "escape" the promise yourself (eg `setTimeout`), or at least be aware of the repercussions (error swallowing). Otherwise you end up with a hanging promise that no one owns but still carries some valuable information.

**Comment by mjackson** [comment]
Thanks for the detailed answer, @taurose. Please feel free to close these kinds of issues after helping someone if you'd like :)

**Comment by wonnage** [comment]
Thanks, @taurose. Hadn't thought of the setTimeout trick.
