### ISSUE TITLE
Hook parameters

### ISSUE THREAD

**Issue by Spy-Seth** [rackt/react-router#2044]
As I'm rewriting my application to use the last version of react router, I'm facing an issue with the current hook system. 

As you describe in the documentation:

> These hooks are useful for various things like requiring auth when a route is entered and saving stuff to persistent storage before a route unmounts.

Perfect that's exactly what I want to do. In you example, you use a static service to provide the needed auth information. But not every application rely on static service. Mine use a dedicated object instance. 

I've take a look into the current hook implementation and I've see that right now there are no solution to pass arguments into a hook. I've also see that it already exist a `createElement` that allow the user taking the hand on the Router initialization. I'm asking myself if a similar solution could be use to do the same with the hook: `createHook`. I'm pretty sure I not the only one with this kind of issue. The idea is not to allow each hook to have a different parameters but to allow passing the same parameters to all the hook.

If this is ok for you, I can make a try to implement it.

**Comment by shouze** [comment]
:+1:

**Comment by mjackson** [comment]
> there are no solution to pass arguments into a hook

What arguments do you need to pass into your hook? And why? Can't you just keep your auth service in a separate module?

```js
var authService = require('./authService')

function onEnter(nextState, replaceState) {
  if (!authService.auth())
    replaceState(null, '/login')
}

<Route onEnter={onEnter} />
```

**Comment by th0r** [comment]
@mjackson For example, some flux instance. Actually, it's just paraphrased issue about additional `context` parameter in `willTransitionTo` hook from `v0.13.3`.

**Comment by th0r** [comment]
@mjackson Here is one of those issues: https://github.com/rackt/react-router/issues/1274
And here is what @ryanflorence recommends in this case: https://github.com/rackt/react-router/pull/590#issuecomment-111910388

Summing up:
> either recreate your routes (they're just lightweight objects) or use an application container, we aren't going to be an app container.

And this forced me to completely abandon any transition hooks - it's just not acceptable to recreate the whole routes config every single request server side.

But I'll be glad to hear there is some other solution to this problem that I just don't know about)

**Comment by mjackson** [comment]
Ah, yes. I remember this problem. Thank you for jogging my memory, @th0r :)

I *think* you can use `location.state` as your way to "pass an arg" through to your transition hooks, at least in the case of `onEnter`. This would be an ideal place to pass through session data, IMO.

**Comment by timdorr** [comment]
You could also use a higher order function. Here's something I do:
```js
function requireAuth(store) {
  return (nextState, transition) => {
    let { auth } = store.getState()

    if (!auth || !auth.id)
      transition.to(loginPath, { return_to: nextState.location.pathname })
  };
}

const route = <Route path='/' component={App} onEnter={requireAuth(store)}>
```

**Comment by th0r** [comment]
@timdorr Than means you will need to recreate routes config every request server side...

**Comment by timdorr** [comment]
@th0r Routes can be made from POJOs instead of React elements, so they can be very lightweight. You can then assign just the transition hooks as properties on the existing route config without having to rebuild it from scratch. E.g., `routes.childRoutes[0].childRoutes[2].onEnter = requireAuth(store)`

But help me understand why rebuilding the route config is unacceptable. I'm not groking the reasoning why that's an issue. Do you have an extremely large route tree? You can [dynamically load routes](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md) to improve performance.

**Comment by th0r** [comment]
@timdorr Because it's uselessly spending processor time and memory. For simple blogs it's ok, but for highly loaded websites it shouldn't be done this way.

For every request you're not only recreating the whole route tree, but also create all these `requireAuth` functions and other hooks, that depend on flux instance. 

So, IMHO, this approach can be considered as workaround, but definitely not as the right solution.

**Comment by timdorr** [comment]
Route config is really lightweight compared to the route matching operation, which will occur on every full page request no matter what. You have plenty of other stuff that's a potential performance implication for your server side render. Most notably, you have to construct a new Flux store and retrieve any data you're going to populate into it. Route configuration is a small fraction of the work your app server is going to be doing.

**Comment by knowbody** [comment]
seems like it is solved. if not please reopen.
