### ISSUE TITLE
Nested Routes not Matching When Entered Explicitly in Browser

### ISSUE THREAD

**Issue by gsccheng** [rackt/react-router#2070]
Before I dive deeper and post all my code, I was wondering if anyone has any quick suspicions as to why I'm getting these problems with React-Router 1.0.0-rc1. I am trying to model my decoupled app after [this tutorial](https://auth0.com/blog/2015/04/09/adding-authentication-to-your-react-flux-app/) but I need to update it to the new React Router version.

I have this basic nested route structure:
```
let routes = (
  <Router>
    <Route path="/" component={TapFrontendApp}>
      <Route path="login" component={Login}/>
      <Route path="home" component={Home}/>
      <Route path="positions" component={Positions}/>
    </Route>
  </Router>
);
```
The root path loads fine. If I were to explicitly enter a path in the URL of my Chrome browser like `/login` I would get this message displayed 
`Cannot GET /login`
However, if I were to click on a `Link` component that has a `to="login"` prop the nested login component seems to display properly. However, the URL in the browser would not change to the new path name.

So, my questions are:
1) What common reasons would there be for why I am getting `Cannot GET /login`. If I were to see the `router` like
```
let router = createRoutes({routes});
console.log(router);
```
I would get an object of length 1 where I don't see any evidence of other nested routes (but I can be looking at it wrong).
2) Why is the URL in the browser not changing to the new path name when I click on the `react-router` link even though the components are rendered?

Thanks!

**Comment by jazlalli** [comment]
I was trawling through issues looking for some help on something else, but I might be able to help on this. My guess is...

1. Your server does not know how to handle anything that is not `/`. You'll need to create a wildcard route handler on the server, such that it always returns your index.html and static assets. The app will then fire up in the browser and render the right route.

2. This might be because you haven't specified which history to use with the Router. Depending on what you want, there are a few options outlined in [the history docs](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md). Although it should default you to hashed URLs, so that might not be it.

Hope that helps some.

**Comment by vojtatranta** [comment]
Exactly as @jazlalli says.
On server you can do this with Express:
```js
app.get('*', function(req, res) {
    //server side rendering here
})
```

**Comment by mjackson** [comment]
My guess is that you don't have your server configured correctly, @gsccheng. Thanks for the help here @jazlalli and @vojtatranta.
