### ISSUE TITLE
Migration problems

### ISSUE THREAD

**Issue by Dodelkin** [rackt/react-router#2089]
Hi, I need your support.
Look, in this code snippet I did some kind of trick with Utils, which doesn't work after recent Rendering update (from 0.13.3 to 1.0).
```js
import ReactRouter from "react-router";
import RouteConfig from "../../Configs/RouteConfig";

var router = ReactRouter.create({
    location: ReactRouter.HistoryLocation,
    routes: RouteConfig
});

export default {
    makePath (to, params, query) {
        return router.makePath(to, params, query);
    },

    makeHref (to, params, query) {
        return router.makeHref(to, params, query);
    },

    transitionTo (to, params, query) {
        router.transitionTo(to, params, query);
    },

    replaceWith (to, params, query) {
        router.replaceWith(to, params, query);
    },

    goBack () {
        router.goBack();
    },

    run (render) {
        router.run(render);
    }
};
```

So the question is how can I do something like this with a new version?

Regards!

**Comment by johanneslumpe** [comment]
@Dodelkin Instead of using `router`, you will use `history`. If you want the history instance to automatically add query params for you, you have to enhance it using the `useQueries` enhancer. As for `run` - there is no direct equivalent for that. You could try to emulate the previous behavior using `match` - but I'm currently not sure how well that'd work out.

So your updated code would look like this:

```javascript
import { useQueries, createHashHistory} from 'history';
import RouteConfig from "../../Configs/RouteConfig";

export const history = useQueries(createHashHistory());

export default {
    makePath (path, query) {
        return history.createPath(path, query);
    },

    makeHref (path, query) {
        return history.createHref(path, query);
    },

    transitionTo (path, query) {
        history.pushState(path, query);
    },

    replaceWith (path, query) {
        history.replaceState(path, query);
    },

    goBack () {
        history.goBack();
    }
};
```
Notice that you have to export your `history` instance, because you have to pass it to the `Router` component. Every time the state in that instance changes, the router will automatically re-render. There is no need for a `render` callback. If you were using it to fetch data then you will most likely want to emulate the old behavior so you don't have to re-write a lot of things. In that case you might just want to use `RoutingContext` in combination with `match`, as illustrated in the [server-side rendering guide](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md).

I haven't thought about all the details, but this should help you get started :)

**Comment by Dodelkin** [comment]
Nice answer! Thank you so much.
