### ISSUE TITLE
Need to maintain scroll position when back button is pressed using history goBack function

### ISSUE THREAD

**Issue by rosnk** [rackt/react-router#2095]
I have a list of products and when particular product is clicked it opens a detail view page. I am using "this.history.goBack()" which is triggered by a button to go back to list of products. 

**My problem is that every time i hit back button product list opens at the top of the page but i want to maintain previous scroll position.**

I found this in upgrade guide but its of no help: 
*In 0.13.x we had a couple of implementations to restore scroll position, we've realized that we can build a better implementation on top of the router and will be doing that very soon, before the 1.0 final release, but it doesn't need to be baked into routing like it was before.*

I am using version 1.0, so can anyone please help me out in order to achieve this.

**Comment by ccapndave** [comment]
+1

**Comment by knowbody** [comment]
With the current `History` module (v1.12.4) and React Router 1.0.0-rc3 the previous scroll position is being maintained. Just checked and it works fine in my project.

**Comment by CJY0208** [comment]
try this https://github.com/CJY0208/react-router-cache-route

**Comment by CJY0208** [comment]
+1 when I'm using v4.

Component would be unmounted when `Route` was unmatched which lead to **losing data and interaction.**

After reading source code of `Route` I found that using `children` prop as a function could help to control rendering behavior.

**Hiding instead of Removing** may help.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L118-L127
