### ISSUE TITLE
Router change doesn't apply on render

### ISSUE THREAD

**Issue by yuvalsaraf** [rackt/react-router#2163]
Hey,
I tried to do some dynamic routing using your (awesome) router - one before logging in (so the user won't be able to go some other route), and the application itself - after login.
Anyway I have a problem with [my react cordova boilerplate](https://github.com/yuvalsaraf/react-cordova-boilerplate), I'm trying to make my routes dynamic using react-router@1.0.0-rc1:

    if (credentials.valid) {
        component = (
            <Router history={this.history}>
                <Route path="/main" component={wrapComponent(TodoApp, { todos, actions: todoActions })}/>
                <Redirect from="*" to="/main"/>
            </Router>
        );
    } else {
        component = (
            <Router history={this.history}>
                <Route path="/login" component={wrapComponent(Login, { credentials, credentialsActions })}/>
                <Redirect from="*" to="/login"/>
            </Router>
        );
    }
    return component;

[full code](https://github.com/yuvalsaraf/react-cordova-boilerplate/blob/sass/src/containers/AppRoute.jsx), but everytime I login it leaves me in the same page even though the "routing rules" have changed (store updated and forces a rerender).
Reloading / on hot model replacement does change the route.
help?

**Comment by knowbody** [comment]
instead of using those `if else` statements React Router's API provides something called [`onEnter`](https://github.com/rackt/react-router/blob/master/docs/API.md#onenternextstate-replacestate), and this is the good place to check if the user is logged in.

Please check the [auth-flow](https://github.com/rackt/react-router/tree/master/examples/auth-flow) example. And also more in the [documentation](https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteConfiguration.md#enter-and-leave-hooks).

**Comment by yuvalsaraf** [comment]
Thanks! awesome!!
