### ISSUE TITLE
How can I preserve query parameters when changing route?

### ISSUE THREAD

**Issue by pwfcurry** [rackt/react-router#2185]

**Comment by mjackson** [comment]
In your route component:

```js
class Home extends React.Component {
  render() {
    return <Link to="/somewhere/else" query={this.props.query}>go somewhere else</Link>
  }
}
```

**Comment by lpender** [comment]
```
Warning: Unknown prop `query` on <a> tag. Remove this prop from the element.
```

Is there an updated way?

**Comment by omninonsense** [comment]
@lpender `props.to` can accept an object; on it you can define `pathname` and `query` properties. [More info here (for v3)](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#link)

**Comment by shauns** [comment]
For v4, its slightly different, as it uses `search` instead:

```jsx
<Link to={{ pathname: '/somewhere/else', search: this.props.location.search}}>Go</Link>
```

**Comment by tscizzle** [comment]
Is there a way to do this when using `history.push`, instead of `Link`?

I tried
```
history.push({
  pathname: '/app/measurements',
  search: location.search,
});
```
but it causes an issue when, just before that line, an action is dispatched that updates the query params.

This is because at the time of calling `history.push`, `location.search` is one thing (call it A) and if the query string is updated (let's say to B), by some action between when `history.push` is called and when its result occurs, then `.push` incorrectly sets the query string back to A.

**Comment by tbillington** [comment]
Also looking for a solution to this where the params don't get unset automatically. Using it for a console application where the current data set the user is operating on is kept in the url bar eg `?dataset=foo`, lots of sites do this.

**Comment by kanenathan213** [comment]
@tscizzle 
```javascript
history.push('/app/measurements' + history.location.search)
```
