### ISSUE TITLE
Switch chat away from Reactiflux Slack

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2250]
Reactiflux is going away and has been closed to new signups for a while.

Seems like the next best non-IRC options are either to set up a Gitter, or to make a React Router (or Rackt) Slack.

Gitter's UX is awful compared to Slack, but per https://github.com/reactiflux/volunteers/issues/17#issuecomment-147300333, Reactiflux#react-router is already at 1k, which might be an issue.

**Comment by mjackson** [comment]
We tried Gitter for a while but didn't like it. Slack is obviously a no-go.

We do still have a #rackt IRC channel on freenode that has some people in it. Maybe we just point people there for now since at least we know IRC can handle a lot of connections.

**Comment by taion** [comment]
Makes sense. For better or for worse, it'd be easier for people to just hop on and ask questions than it currently is - no account registration step (even if registration were still open).

**Comment by edvinerikson** [comment]
https://github.com/reactiflux/volunteers/issues/17 is flooding with alternatives. I personally think [Hipchat](https://www.hipchat.com/) seems good.

**Comment by timdorr** [comment]
I also like Hipchat. But I would definitely have someone reach out to them before throwing thousands of unpaid users their way :smile:

**Comment by edvinerikson** [comment]
I've sent a mail to the Hipchat support and are waiting for an answer. (Will notify here when I get it)

**Comment by mjackson** [comment]
I don't use HipChat for anything else, so for me personally it would be annoying to have yet another chat client open. The reason we went with Slack in the first place is because it seemed like a lot of people were using it instead of IRC, so it wouldn't be a big deal to just join another Slack channel. But if we went with HipChat, I'd have at least 4 chat programs that I use regularly :(

My vote is to head back to IRC. We registered the #rackt channel about a year ago, and it's still there.

**Comment by mjackson** [comment]
BTW, there's also a great #reactjs channel on freenode with 600+ users in it regularly. It would be great for people to be able to just switch between the two channels easily.

**Comment by knowbody** [comment]
Good old IRC :computer:

**Comment by outpunk** [comment]
IRC didn't die in decades and won't die for decades, too. IRC, please.

**Comment by timdorr** [comment]
Discord is adding an IRC gateway. HipChat has one already. So, you can use your standard IRC clients and optionally layer on the rich clients of those services.

Also, I like HipChat mainly because they've got an honest-to-god, *real* desktop app. Not some half-assed Electron wrapper around their website, but one programmed with blood, sweat, and Objective-C.

**Comment by mjackson** [comment]
Ya, I think IRC is the way to go. Anybody who wants to spin up other services elsewhere can just make sure they have a decent IRC gateway.

**Comment by taion** [comment]
@timdorr Wasn't Slack's thing just an Electron wrapper though?

**Comment by timdorr** [comment]
Yep, and it sucks too :wink:

**Comment by tracker1** [comment]
There's always the [freenode webchat](https://webchat.freenode.net), which even has embed instructions...  It may also be possible to handle one of the IRC web gateways written in node self-hosted somewhere too... like a $5-10 linode or digital ocean server, should be able to handle the load...

All just sticking with IRC, which would be my personal preference... I like slack and hipchat, but feel that given node devs are already in freenode, it'd be a better place to be.
