### ISSUE TITLE
Animation Examples Don't Animate

### ISSUE THREAD

**Issue by preflight** [rackt/react-router#2254]
Are the example for Animations and Transitions supposed to animate/transition? I'm not seeing any of the usual classes/styles for CSSTransitionGroup in `global.css`, so perhaps this is intentional.

Cloned `react-router`, ran `npm install` and `npm start`, pointed browser to `localhost:8080`.

Everything works great except the examples for Animations and Transitions don't animate or transition. I can do a pull request if this is something you'd like to add.

**Comment by deowk** [comment]
Yeah I have the exact same issue, looks like it cannot find the /animations/app.css file - I have tried to add these to the global.css file just to see if it works, but it still doesn't...the classes don't even seem to be getting at all

**Comment by mjackson** [comment]
You can find the CSSTransitionGroup classes in [the animation example's `app.css` file](https://github.com/rackt/react-router/blob/7ba20162edbbb99dd7b921b2ad22fffba4e2e67f/examples/animations/app.css#L7-L23). On my machine this example is working as expected. Please feel free to submit a PR if you'd like to see something cooler.

The transitions example doesn't have anything to do with animation. Rather, it shows how to use transition hooks to prevent a transition to a new route in order to prevent losing form data.

**Comment by knowbody** [comment]
@preflight yeah these examples weren't working properly, but they were fixed by #2269

**Comment by mjackson** [comment]
Thanks @knowbody
