### ISSUE TITLE
Allow function to <Link />'s attributes

### ISSUE THREAD

**Issue by srph** [rackt/react-router#2255]
Here's a basic idea:

```es6
<Link
  to={({ location, routeParams /*, ...otherRouterStuff */ }) => `posts/${routeParams.id}?search=${location.query.q}`}
  query={({ location }) => ({ ...location.query, search: 'yolo' })} />
```

For some reason, I just find it tedious passing down the `location` prop (from the router handler/component) 3~5 levels just for some link. Or maybe I'm just doing the *Smart and Dumb Component* pattern poorly.

**Comment by knowbody** [comment]
you can just use context, something like: `this.context.location`

**Comment by taion** [comment]
Please correct me if I'm wrong, but I think functionally you're looking for something like https://github.com/rackt/react-router/issues/2172?

Otherwise as @knowbody said, you can get `location` from `this.context.location`, though not so much `params` - see https://github.com/rackt/react-router/issues/2278.

I'm going to close this for now unless you think there are concerns not addressed by those.
