### ISSUE TITLE
Suggestion for RoutingContext, server-side rendering and async data

### ISSUE THREAD

**Issue by mmahalwy** [rackt/react-router#2275]
Currently implementing fluxible implementation of flux, and I am having a challenge to dehydrate the data prior to server rendering.

My current routing block:
```
  match({ routes, location }, (error, redirectLocation, renderProps) => {
    debug('Route matched');
    if (redirectLocation) {
      res.status(301).redirect(redirectLocation.pathname + redirectLocation.search)
    }
    else if (error) {
      res.status(500).send(error.message)
    }
    else if (renderProps == null) {
      res.status(404).send('Not found')
    }
    else{
      debug('Pre-render data fetch');
      let context = app.createContext();

      // preRenderData(renderProps.components, context, function() {
        debug('Pre-render data fetch completed');
        const markup = React.renderToString(
          <RoutingContext {...renderProps} createElement={createElement(context)}/>
        );

        console.log(markup);

        const exposed = 'window.App=' + serialize(app.dehydrate(context)) + ';';
        const html = React.renderToStaticMarkup(htmlComponent({
          assets: webpack_isomorphic_tools.assets(),
          context: context.getComponentContext(),
          state: exposed,
          markup: markup
        }));

        debug('Rendering to html');
        res.status(200).send(html);
        res.end();
      // });
    }
```
I got this working with the `preRenderData` which feels a lot like a code smell: 
```
const preRenderData = function(components, context, callback) {
  const preRenderComponent = components.find(component => {return component && !!component.preRender});

  if (!preRenderComponent) {
    return callback && callback();
  }

  let action = preRenderComponent.preRender();

  // TODO: Need to allow for the params to be passed to the actions.
  context.executeAction(action.action, action.payload ? action.payload : null, function() {
    return callback && callback();
  });
};
```
especially given I am handling async data with a `createElement` method that I pass to the router:
```
export default function (context) {
  console.log('Create Element Block');
  return function (Component, props) {
    props.context = context.getComponentContext();

    if (Component.preRender) {
      const action = Component.preRender();

      context.executeAction(action.action, action.payload ? action.payload : null, function() {
        console.log('Create Element Execute Action Finished');
        return React.createElement(provideContext(Component), props);
      });
    }

    return React.createElement(provideContext(Component), props);
  };
};
```

Thoughts on how can I render `RoutingContext` and then when the final component in the tree is rendered (given `createElement` waits for the action and the data to return until it renders the component) before rendering by the server?

Thanks!

**Comment by taion** [comment]
I don't think we can broadly answer this in all cases, because it's really down to integration with the specific paradigm you use to fetch data.

For example, when using Relay, I maintain a specific `react-router-relay` integration that translates route component data dependencies into something that is semantically meaningful in the Relay context.

For most Flux frameworks, using e.g. react-resolver to handle loading nested data dependencies would be a good fit. In your case, I think what you have is not too unreasonable if it suits your requirements, where you first resolve the dependencies, then statically resolve data dependencies per route - it's very similar to how Relay handles it.

In general though I don't think it's possible for React Router to solve this generically - the specific details of how these come up, e.g. whether the data dependencies can be resolved statically at all or whether they can only be resolved as the component is mounted (which would require a render loop) are diverse enough that I don't know that the exists a general solution. At the very least, I see very little in common between e.g. how I handle this for Relay and how I've handled this when using Flux frameworks in the past.
