### ISSUE TITLE
Provide plain routes to JSX routes

### ISSUE THREAD

**Issue by herrstucki** [rackt/react-router#2306]
I couldn't find a way to provide plain routes to JSX `<Route>`s.

This doesn't work because React doesn't like objects as children:

```js
const plainRoutes = [{path: 'foo', component: Foo}, /*...*/];

const routes = <Route path='/' component={App}>{plainRoutes}</Route>;
```

And there is no `childRoutes` equivalent on the `<Route>` component. There is the `createRoutes()` function, but that only works in the other direction.

*Why do I want to do this?* Some routes of a module are automatically generated as plain objects, and I want to expose them to other modules/apps. The consumer of these routes should not be forced to also use plain routes (they may not even know in which form they're exposed).

**Comment by taion** [comment]
What happens if you just specify `childRoutes` as a prop on the `<Route>`?

**Comment by herrstucki** [comment]
That works! :scream_cat: I *thought* I tested that but apparently I didn't. Sorry!

Not sure if it's supported because it's not documented?

**Comment by taion** [comment]
I don't know how well we've explicitly documented these, but libraries like `react-router-relay` depend on all props on the `<Route>` being injected onto the route object.

I don't know that we'd specifically want to document this use case just because, like you've said, it's quite weird and likely to confuse more than clarify people. If we do want to support this pattern, it'd make the most sense just to accept `PlainRoute`s as children on `<Route>`s IMO.

**Comment by herrstucki** [comment]
I dug a bit further: `childRoutes` works as a prop on `<Route>` but more by accident than by design:

- it is not documented
- it's not specified in RoutepropTypes
- it *only* works if the Route doesn't have children (because these replace already existing childRoutes).

For example, this works:

```js
<Route path='/' component={App} childRoutes={plainRoutes} />
```

But this doesn't:

```js
<Route path='/' component={App} childRoutes={plainRoutes}>
  <Route path='bar' component={Bar} />
</Route>
```

The problem with `<Route>{plainRoutes}</Route>` is that React does not allow that. To make that work we'd need to turn the plain routes into JSX routes first. E.g. something like this:

```js
<Route path='/' component={App}>{createJSXRoutes(plainRoutes)}</Route>;
```

**Comment by taion** [comment]
It's not really by accident. It's intentional that we copy all props over onto the route object.

What would it mean if you specified both `childRoutes` and `children`?

React is just fine with `Route` accepting whatever as `children` - there's no restriction that components must use `PropTypes.node` for `children`; it's totally legal and works totally fine if we make `children` accept either a `PropTypes.node` or a `PropTypes.arrayOf(PropTypes.object)`, but I don't think there's a reason to do so.

**Comment by timdorr** [comment]
What about `getChildRoutes`?

**Comment by timdorr** [comment]
Also of note, [we `createRoutes` when using the callback](https://github.com/rackt/react-router/blob/b06d1db7864ba16e36dc7bdae40e18ed86d23907/modules/matchRoutes.js#L10), but [not on the direct prop](https://github.com/rackt/react-router/blob/b06d1db7864ba16e36dc7bdae40e18ed86d23907/modules/matchRoutes.js#L7). That may lead to some inconsistent behavior here.

**Comment by herrstucki** [comment]
Well, unless it's documented and checked by `Route.propTypes`, I have to assume it's a behavior that may break anytime in the future (that's what I meant by "works by accident and not by design"). The same applies for `getChildRoutes`.

And in the case when you set the `childRoutes` prop _and_ have nested routes, the parent route's children will override the ones in `childRoutes`. So this

```js
<Route path='/' component={App} childRoutes={[{path: 'foo', component: Foo}]}>
  <Route path='bar' component={Bar} />
</Route>
```

will match the route `/bar` but not `/foo`. Here's why: https://github.com/rackt/react-router/blob/master/modules/RouteUtils.js#L36-L40

And React _does not_ allow plain objects as children of React elements. It throws this error if you try it:

```
Invariant Violation: Objects are not valid as a React child (found: object with keys {path, component}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
```

**Comment by taion** [comment]
Huh. My bad on the `children` thing.

That said, I believe it's intentional that we forward all props over, including ones not on `propTypes`. Otherwise we could filter away all props not explicitly declared.

Given that routes are ordered, it's not particularly meaningful to specify both `childRoutes` and `routes`/`children`. So no, you can't do both, but what's wrong with just doing `childRoutes` as a prop?

**Comment by taion** [comment]
Let me know if there are any unaddressed concerns. I think passing in `childRoutes` as a prop is correct. I don't know if we want to actively document, though - it might confuse more than enlighten.

**Comment by herrstucki** [comment]
Yeah, I agree. The only drawback (and a potentially confusing one) of the approach with setting `childRoutes` is that they get overridden by a route's children and that there's no obvious way to merge JSX routes with plain ones. So in my case I just resorted to using plain routes everywhere. Thanks anyway!

**Comment by AlastairTaft** [comment]
Can't get this method to work with an `indexRoute`. So I have `childRoutes` specified but then my `indexRoute` prop doesn't seem to apply.
