### ISSUE TITLE
onEnter callback

### ISSUE THREAD

**Issue by kennethaa** [rackt/react-router#2311]
Hi,

I'm trying to upgrade to version 1.0. I used to call the static function fetchData on any route before I rendered with the old version of react-router.

As I now understand the new API, I need to do this on the onEnter hook. The fetchData function inside every route component is returning a Promise. And when I call the callback inside the onEnter hook, it has already continued and called the onUpdate hook. 

```js
onEnter(nextState, replaceState, callback) {
    if (nextState && nextState.routes.length > 0) {
        nextState.routes[nextState.routes.length - 1].component.fetchData(nextState.params)
           .then(() => {
                console.log('fetchData complete');
                callback();
            })
            .catch((err) => {
                console.error(err);
                callback(err);
            });
    }
}
```

**Comment by kennethaa** [comment]
I had to remove the onEnter hook. When I do fetching in the onEnter hook, it causes the router to render null because location will be "null". 

For me this looks like a bug.

**Comment by taion** [comment]
You're doing something very suspect there - `nextState.routes[nextState.routes.length - 1]` will return the same for all of your routes, since `nextState.routes` refers to _all_ active routes for the next state.

This pattern is used elsewhere for server-side loading and as far as I'm aware works fine. Take a look at a few of the other issues and boilerplates floating around.
