### ISSUE TITLE
IE8 support

### ISSUE THREAD

**Issue by AdamGelder** [rackt/react-router#2314]
I recently upgraded the react router from 1.0.0-rc1 to 1.0.0-rc3 which breaks compatibility with IE8 with the following error: 
Invariant Violation: ReactCompositeComponent.getChildContext(): childContextTypes must be defined in order to use getChildContext()

I have had to roll back to 1.0.0-rc1 for the moment.

Any Thoughts?

Many Thanks

Adam

**Comment by taion** [comment]
Do you have any more details on where this error is being thrown?

**Comment by knowbody** [comment]
provide more details and we will reopen. Hard to help with that at the moment.

**Comment by mattydoincode** [comment]
hey guys, I'm at a company that also has to support ie8 (government man...) and I'm 99% sure I know what's going on. Basically you can't do things like https://github.com/rackt/react-router/blob/master/modules/Router.js#L30. where you define static props right on the class, instead you have to do things like this: https://github.com/rackt/react-redux/pull/135/files where you just put the props at the bottom. It's really simple and I can open a PR to fix it. I'll letcha know how it goes! (the problem is that object.defineProperty it un-polyfillable and that particular interaction needs object.defineProperty.

**Comment by taion** [comment]
That's not correct - the code above is actually not valid in any browser; it runs because we transpile it through Babel into legal code.

**Comment by mattydoincode** [comment]
I'm well aware of the transpiler being used. When you use static properties, the transpiler (babel) uses defineProperty, when you don't have static props, it doesn't use defineProperty. Check my PR that I linked for a full discussion.

**Comment by mattydoincode** [comment]
sorry this is the discussion: https://github.com/rackt/react-redux/issues/133

**Comment by taion** [comment]
My bad! I wasn't aware it was a consequence of that specific Babel interaction.

**Comment by taion** [comment]
To clarify - this is broken even when using es5-shim?

**Comment by mattydoincode** [comment]
Yup, Completely broken and unfixable. Class properties are still
experimental (https://babeljs.io/docs/plugins/). I have a PR that I'm about
to setup that removes them completely. Not sure if there is a way to lint
against this though as I couldn't find a static properties type rule...

**Comment by taion** [comment]
@mattydoincode 

I'd drop up to Babel stage 1 from stage 0 if you want to enforce the non-use of class properties.

Although I think Babel 6 moved them up to the stage 1 preset, so worth tacking a note somewhere.

**Comment by taion** [comment]
You can also blacklist the specific Babel transformation if you want to be more explicit.

**Comment by mattydoincode** [comment]
I'm still researching locally to see exactly how ie8 is responding to
everything. Will keep you posted! Just want to make sure I can back
everything up with real world results.

**Comment by gagayang** [comment]
in my project say "setter & getter is not support in this javascript engine" and i try to read your code. i find this is case by "export * from "./xx" some code like this.

**Comment by SimenB** [comment]
https://phabricator.babeljs.io/T7322

**Comment by gagayang** [comment]
hello you mean this can fix the issues? @SimenB

**Comment by gagayang** [comment]
But we refer to the use of the compiled lib file, is that we want to compile the webpack which includes nodo_modules?@SimenB

**Comment by SimenB** [comment]
If that issue is addressed, the router would be compiled in an IE8 compatible way. It's not something you can fix on your end, either the router has to export in some other way, or Babel need to change how it's compiled.

I haven't tried using the router with IE8, but you can probably import directly from `lib/` (unsure how supported it is, so you might want to lock down you version of the router), to avoid the unsupported code in the entry point.

**Comment by gagayang** [comment]
thank you very much for your help. i have try to babel compiled by IE8 way. but it still not work.
 it may be other npm  class libraries made. i think this too many libraries not support Ie8.

i from china ,my english is poor, thanks agan.
