### ISSUE TITLE
Visited links does not become active (there's no active class on them)

### ISSUE THREAD

**Issue by rozetta13** [rackt/react-router#2348]
I have a page where I use links. I use the Link component and set activeClassName value. After visiting link by clicking on it active class is not applied, but after typing route in the address line it works fine.

My route config:
```js
    <Route path="/" component={App}>
      <Route path="systems" component={SystemsPage} />
      <Route path="employees" component={EmployeesPage} />
      <Route path="my-firm" component={MyFirmPage} />
    </Route>
```
and my links:
```js
    <ul>
	    <li><Link to="/systems" activeClassName="active-link">Systems</Link></li>
	    <li><Link to="/employees" activeClassName="active-link">Employees</Link></li>
	    <li><Link to="/my-firm" activeClassName="active-link">My Firm</Link></li>
    </ul>
```
I use react-router v^1.0.0-rc3 if it makes sense.

Am I doing something wrong?

P.S. I am new at this so any help would be appreciated.

**Comment by knowbody** [comment]
have a look in the [docs](https://github.com/rackt/react-router/blob/master/docs/API.md#isactivepathname-query-indexonly)

**Comment by Ferixz** [comment]
I had the same problem.

I've been reading docs for hours, but the problem was not with the `Router` or `Link` component, so the documentation was not helpful. My component was _connected to a redux store_ which prevented it's child components to respond to route changes properly. 

I managed to decouple my navigation component from redux and passed down the URL parameters from its corresponding route component. My code looks cleaner and more organized, but I think it's for the best if this incompatibility is documented somewhere.
