### ISSUE TITLE
Use issue tracker for bug reports and feature requests only?

### ISSUE THREAD

**Issue by taion** [rackt/react-router#2393]
@knowbody brought this up at https://github.com/rackt/react-router/issues/2380#issuecomment-151134176 and I think this is worth having as a separate issue.

Given the amount of traffic here, what do we think about doing what e.g. Babel does and restricting the issue tracker to actual issues? We already have an SO tag and multiple chat channels, and both of those can be better venues for getting help with using React Router than the issue tracker.

**Comment by knowbody** [comment]
thanks @taion

**Comment by mjackson** [comment]
Yes, absolutely. How does Babel handle this? They just close anything that's not an actual issue?

Sometimes I see stuff come through here that doesn't sound like our bug, but I'm not 100% sure. Maybe we can use an `unverified` tag for those that basically means "we're not sure if there's a real issue here or if this is just a question".

**Comment by knowbody** [comment]
or a `Stack Overflow Question` tag ;p

**Comment by taion** [comment]
Here's a few examples of how Babel handle this:

https://github.com/babel/babel/issues/2590
https://github.com/babel/babel/issues/2562
