### ISSUE TITLE
`PatternUtils.formatPattern` replaces encoded space (%20) with +

### ISSUE THREAD

**Issue by coopy** [rackt/react-router#2407]
This line causes a URL parameter to be encoded in a non-reversible way: https://github.com/rackt/react-router/blob/v1.0.0-rc3/modules/PatternUtils.js#L170

We have an IIS server that doesn't correctly resolve URLs because of this behavior.

The change was introduced here: https://github.com/rackt/react-router/commit/d955d7a69052fd649b58d00bd75301a533f67e06

I'd like to know the reason that this behavior was introduced, as it's somewhat unexpected. To quote @mjackson:

> Apparently + is a special character in query strings, but not in the path portion of the URL. 
https://github.com/rackt/react-router/issues/716#issuecomment-71346876

I've not been able to find conclusive evidence in the [URI spec](https://tools.ietf.org/html/rfc3986), but considering that encoding and decoding should be symmetrical operations, this seems wrong. There is some discussion in this [Stackoverflow thread](http://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20).

Example:
```
var placeName = 'Laguna Beach';
var uri = formatPattern('/place/:placeName', { placeName: placeName });
decodeURI(uri);
// -> "/place/Laguna+Beach"
// Expected decoded URI would be "/place/Laguna Beach".
```

**Comment by taion** [comment]
Good catch. Do you want to put together a PR?

**Comment by coopy** [comment]
Sure, not a problem.

**Comment by taion** [comment]
It's interesting that we only call `formatPattern` from `<Redirect>`. You'd think a more consistent API to handle URL parameters in `<Redirect>` would be to just accept a function of params => new path.

**Comment by coopy** [comment]
In our application, we call `formatPattern` ourselves for reasons outlined in https://github.com/rackt/react-router/pull/1850.

**Comment by mjackson** [comment]
You're right, we should be using `%20` in the pathname portion of the URL. We already have [a test](https://github.com/rackt/react-router/blob/e2a979e08fcbb4c253bf351b1b2f0a71fa522bca/modules/__tests__/formatPattern-test.js#L60
) that appears to be testing the wrong thing.

I'd like to use `+` instead of `%20` in the query string. From [the URI spec](http://www.w3.org/Addressing/URL/uri-spec.html):

> Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.

But that logic belongs in the history package (i.e. useQueries), not here.

**Comment by Download** [comment]
I have a route like this:
```xml
<Route path="near/:city" component={StoresNear} />
```
In `StoresNear`, I print the `:city` parameter, like this:

```xml
<h2>Stores near {this.props.params.city}</h2>
```

I enter this URL into the address bar of the browser:

`http://localhost:8080/near/My+City`

I then get this header:

> Stores near My+City

If I change the URL to use a percent-encoded space

`http://localhost:8080/near/My%20City`

it works:

> Stores near My City

**Question:**
Is this expected behavior? I have been reading this bug report, as well as [this old one](https://github.com/rackt/react-router/issues/716) and [this more recent one](https://github.com/rackt/react-router/issues/2426), but I can't figure it out.

I didn't want to create a new issue so I hope you guys don't mind me reviving this one.

To me it feels like a bug that the plus symbol does not get decoded, but it might be a feature? I don't get it though because afaik, all servers will decode it to space...

**Comment by taion** [comment]
This is expected. `+` only gets decoded in query strings, not in URLs proper.

**Comment by Download** [comment]
@taion Ok, thanks for clearing that up. And Merry Christmas :)
