### ISSUE TITLE
history.isActive() not considering optional path segments as optional

### ISSUE THREAD

**Issue by 1000hz** [rackt/react-router#2437]
Given the route `<Route path="/foo(/bar)" component={Foo} />` and link `<Link to="/foo" activeClassName="active" />`, visiting `/foo/bar` does not result in the activeClass being applied to the Link.

**Comment by taion** [comment]
This test case:

```js
describe.only('2437', function () {
  it('is active', function (done) {
    render((
      <Router history={createHistory('/foo/bar')}>
        <Route path="/foo(/bar)" />
      </Router>
    ), node, function () {
      expect(this.history.isActive('/foo')).toBe(true)
      done()
    })
  })
})
```

passes against both master and 1.0.0-rc3. You most likely have something misconfigured on your side.

**Comment by 1000hz** [comment]
My bad, I simplified the example too much. It fails when the route is `<Route path="/foo(/:bar)" />` because it fails the `paramsAreActive(paramNames, paramValues, activeParams)` test.

**Comment by taion** [comment]
Hmm - I'd call that expected, though. Can't you do:

```js
<Route path="/foo">
  <Route path="(:bar)" />
</Route>
```

You'd need the changes from https://github.com/rackt/react-router/pull/2421, though.

**Comment by 1000hz** [comment]
Yeah, that does work. Should that really be necessary though? The fact that those two configurations produce different results would indicate to me there's a bug.

I'm pretty sure the problem is somewhere in `PatternUtils.matchPattern()`

**Comment by 1000hz** [comment]
>Hmm - I'd call that expected, though. 

But also, why would this be expected behavior? From the docs:

> A `<Link>` also knows when the route it links to is active and automatically applies its `activeClassName` and/or `activeStyle` when it is.

That's clearly not the case with the first config.

**Comment by taion** [comment]
It's because the parameters don't match. In this context, `/foo` means the route `/foo(/:bar)` with `bar` not specified. That route is in fact not active. Broken out, `/foo` becomes the parent route, which then is active.

**Comment by 1000hz** [comment]
Sorry, I promise I'm not trying to be a dick, but `/foo` and `/foo/bar` map to the same `<Route/>`, which is active.

**Comment by taion** [comment]
Sure, but in your revised example, so would `/foo/baz`. In this context, `/foo` is more like `/foo/baz` than like `/foo/bar`.

**Comment by 1000hz** [comment]
And `<Link to="/foo" />` should be active for all three.

`<Link to="/foo/bar" />` should only be active for `/foo/bar`. Same for `/foo/baz/`.

**Comment by taion** [comment]
It's exactly as you've noted earlier - because the parameters don't match. That's just how we've chosen to define "active" in the context of routes, and you can get the behavior you want by e.g. treating the route with the `(:bar)` path as an optional child.

This is just how we've chosen to define "active".

**Comment by 1000hz** [comment]
I've been thinking over this some more and I think you're right. Thanks for your patience, @taion.

**Comment by nickdima** [comment]
Are you guys sure about this behaviour for the optional parameters? I'm currently transitioning an app from rr 0.13 to 2.0 and I have some problems related to this.
Here's an example according to @taion 's recommendation:

```jsx
<Route path='/inbox' component='Inbox'>
  <Route path='messages' component='Messages'>
    <Route path=':page' component='Messages'>
  </Route>
</Route>
```

Here you can see that both `/inbox/messages` and `/inbox/messages/2` point to the same component as they do the same thing, the only thing that changes is which page of messages it needs to fetch.
That could be ok, but now imagine that you have static methods on your components for fetching the data via your API and you call all this methods on your matched routes on the server in order to have the data before rendering. 
What will happen here is that the fetch method will be called twice for the component `Messages` and it's not what we want. Unless we add more logic to avoid calling the same method multiple times, but it seems like a lot of overhead and it's prone to errors.

Also, it's kind of a strange behaviour that with
```jsx
<Route path='/inbox' component='Inbox'>
  <Route path='messages(/:page)' component='Messages' />
</Route>
```
`isActive` returns false for both of this:  `/inbox/messages`, `/inbox/messages/2` with `indexOnly` set to true.
Both of them match the same route, but none of them is active.

**Comment by nickdima** [comment]
Hmm, after thinking about it I think the best way to do it is having the routes like this:
```jsx
<Route path='/inbox' component='Inbox'>
  <Route path='messages' component='Messages' />
  <Route path='messages/:page' component='Messages' / >
</Route>
```
This makes it more clear on what to expect from `isActive` and it also solves the problem of data fetching. Maybe we could document this in relation to the optional url parts, so other people don't get false expectations?
