### ISSUE TITLE
goBack() not working when followed by transiionTo

### ISSUE THREAD

**Issue by chetankothari** [rackt/react-router#2449]
I have 2 components say `C1` and `C2`.

I Transition from `C1` to `C2` using the `transitionTo` method, but when I want to navigate back from `C2` to `C1` I have to call `goBack` twice.

I am using the [Proxy calls to router](https://github.com/rackt/react-router/blob/0.13.x/docs/guides/flux.md) way of navigating from on component to another. 

I am doing all this in my component. 

I checked out that calling `window.history.go(-2)` works fine.

**Comment by taion** [comment]
0.13.x is no longer supported - we might cut one more release for React v0.14 support, but there aren't going to be any more changes on that line. Otherwise, for questions and support, please visit [our channel on Reactiflux](https://discord.gg/0ZcbPKXt5bYaNQ46) or [Stack Overflow](http://stackoverflow.com/questions/tagged/react-router). The issue tracker is exclusively for bug reports and feature requests.

**Comment by chetankothari** [comment]
@taion Thanks for the quick response. Will checkout the resources you mentioned. And also will try to upgrade to v1.0.x.
