### ISSUE TITLE
unexpected behaviour with routerWillLeave and child routes

### ISSUE THREAD

**Issue by haustraliaer** [rackt/react-router#2556]
From what I posted in Discord in case anyone else is struggling with this...

so I have something like:

```js
<Route path="/" component="Parent">
    <Route path="betterroute" component="BetterRoute" />
    <Route path="leaveme" component="LeaveMe">
        <Route path="1"  component="1" />
        <Route path="2"  component="2" />
        <Route path="3"  component="3" />
    </Route>
</Route>
```

on `LeaveMe` I am using:

```js
  mixins: [ Lifecycle ],

  routerWillLeave(nextLocation) {
    return ';...;'
  }
```
Expected behaviour is that it should throw the alert if I navigate to `/` or  `/betterroute` from `/leaveme`, or any route that is a child of `/leaveme`.

What actually happens is I enter on any of the following routes:
```
/leaveme/
/leaveme/1
/leaveme/2
/leaveme/3
```
And it will register `LeaveMe`'s lifecycle hook (because the component is technically mounted)... 

Then, if I navigate to literally any route (including child routes) it will run and de-register the mixin.

My current solution is to not use the mixin at all and instead use History directly on `LeaveMe` like so:

```js
  componentWillMount() {
    this.unsubscribeToHistory = this.props.history.listenBefore(this.routerWillLeave)
  },

  componentWillUnmount() {
    this.unsubscribeToHistory()
  },

  routerWillLeave(nextLocation) {
    if(nextLocation.action === 'PUSH') {
        if(nextLocation.pathname.split('/')[1] !== 'leaveme') {
          return ';...;'
        }
    }
  },
```

Which does the trick.

**Comment by timdorr** [comment]
This is the correct behavior. When router moves between routes, it does not do a diff between the two states, but instead builds a fresh route tree for the next state. So, in this way, it acts a little unlike React itself, where it will do a minimal set of operations on the DOM. This helps router maintain consistent behavior. 

For example, you may want to perform some animation at the `LeaveMe` component's level when moving between those child routes. If we had inconsistent behavior and conditionally fired off that hook, it would actually be harder (maybe even impossible) for you to implement that kind of animation.

It's understanding confusing since this doesn't jive with normal React-isms, but it does make sense for the API to behave like this. I can see about some better documentation to clear this up a bit.

**Comment by taion** [comment]
@timdorr 

Are you sure? I didn't have a chance to look at this in depth, but it looks like `transitionHook` is at least attempting to calculate the `leaveRoutes` and only invoke the leave hooks for those: https://github.com/rackt/react-router/blob/v1.0.0/modules/useRoutes.js#L119

**Comment by timdorr** [comment]
NEVERMIND! :smile:

**Comment by taion** [comment]
Sorry - I'd wanted to leave a comment but I was going to wait until I found some time to dig through the confirming navigation stuff in a bit more depth and maybe add some tests and confirm the original report.

**Comment by taion** [comment]
This doesn't reproduce against our transitions example for me. I'm not sure what specifically is happening in your case, but this appears to work correctly for me.

**Comment by Yhaojing** [comment]
why confirming navigation  appears two times
