### ISSUE TITLE
RouteHandler vs. this.props.children, what's next?

### ISSUE THREAD

**Issue by blandinw** [rackt/react-router#2618]
Removing `<RouteHandler />` and having Router generate `this.props.children` caused 2 issues when passing props to nested Route components:
- we cannot use `propTypes .isRequired` in any Route components
- we have to use `React.cloneElement`, which adds code complexity + performance cost

What is the plan to address those?
Are we just saying that passing props is bad anyway?
Let's imagine a parent view and 3 tabs, each tab having to a different URL.
What's the idiomatic way to pass props from the parent's state to each tabbed view?

**Comment by taion** [comment]
In general, passing props across route boundaries is not the first-best way to do anything, because it reduces the flexibility available in changing around your routing structure, and implicitly couples route components to where they live in a route hierarchy.

In general for good implementations of patterns like async props, it's actually more or less required that your route components not be functions of e.g. injected props, because otherwise you have no way of avoiding request waterfalls.

The idiomatic way to handle this in React is in fact to use `cloneElement`. I'm not sure how familiar you are with React, but `cloneElement` is approximately free next to anything of interest you might do, since it's essentially just a couple of `Object.assign` calls (make sure you're not trying to profile stuff in dev mode - this is a common cause of confusion).

This is really the most idiomatic React approach in general, since the router is essentially just getting out of the way and rendering for you e.g.

```js
<Parent>
  <Child1>
    <Child2 />
  </Child>
</Parent>
```

Otherwise, if you need help, feel free to reach out on Stack Overflow or Reactiflux.
