### ISSUE TITLE
Routes rendered by a component?

### ISSUE THREAD

**Issue by olance** [rackt/react-router#262]
I've literally spent hours on that and I've come to believe what I want is not (yet?) possible.

I probably have a bit of an uncommon setup: I am using React within a Rails application using react-rails and browserify-rails to get things working together.

Before trying to use react-router, I had the following setup (a sample/simple blog app):
```
<App>
  |__<div>
         |__ <h1>
         |__ <PostsList>
```
The App component would initialize an app context, register a PostStore and dispatch an `initial_state` message to fill the store with posts fetched on the server when rendering the page.  
Using react-rails, all of this would render on the server and then be picked up by the React UJS script, simply by calling the `react_component('App', {initialState: @app_state})` view helper in my Rails layout.

Now, I want to display a `<PostShow>` component instead of my `<PostsList>` when the user clicks on a post title. I chose to try react-router to handle the route changes and UI updates implied after talking to @mjackson on IRC ^^

Because I am using react-rails, what I'd like to do is keep this unique entry point through my App component and the `react_component` call.  
So I have renamed `App` to `AppRouter` and changed the render code of this main component to draw my routes instead:

```javascript
render: function () {
        return (
            <Route path={RouteHelpers.root_path()} handler={App}>
                <DefaultRoute handler={PostsIndex} name="root"/>
                <Route path={RouteHelpers.post_path.spec()} handler={PostShow} name="post" />
            </Route>
        );
    }
```
(I originally had a parent `<Routes location="history">` but have removed it after reading #40... not sure that was the right thing to do?)

The new `App` component uses `activeRouteHandler` to display `<PostsIndex>` or `<PostShow>` depending on the active route.

I really, really thought the would work out nicely, but I keep getting this error:
```AppRouter.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object```

Apparently, `<Route(s)>` isn't a React component. Is it not??!  
The codebase is quite large but I did find that `Routes = React.createClass(...)` so why would React tell me it's not a ReactComponent?

What have I missed? Is there a way to achieve what I've described here?

**Comment by olance** [comment]
Thanks for the link @gaearon, it should help me out :)

I have read about it, but what I'm trying to achieve would be much nicer with a simple wrapper.

>Because I am using react-rails, what I'd like to do is keep this unique entry point through my App component and the react_component call.

Using react-rails implies using the `react_component(componentName, stateObject)` view helper. This helper outputs some markup that'll be picked up by React Unobtrusive JS script to render whatever is needed to be rendered. `componentName` here is a string, I cannot (and wouldn't) put JSX/virtual DOM there to have my routes at the top level.  
That's why I'd rather keep my `App`/`AppRouter` top-level object that could then render the router, depending on other stuff like declared routes on my Rails app and so on.

I'll try to get back at testing all this during the week and see what happens! ^^

**Comment by rpflorence** [comment]
With 0.11.x you can do it like this now: http://jsbin.com/duyaxa/1/edit?html,js,output

**Comment by gauravtiwari** [comment]
thanks @rpflorence! Will this work server side as well together with react-rails gem ?

**Comment by rpflorence** [comment]
I don't know why it wouldn't, but I don't know anything about the react-rails gem.

**Comment by attrck** [comment]
Works well with react-rails gem! :) 

If you use something like `react_component('App', {initialState: @app_state})`, then you can delegate the state to other components like this: 
```jsx
return Handler ? <Handler initialState={this.props.initialState} /> : null;
```
And then deeper in the route hierarchy in similar fashion:
```jsx
<RouteHandler initialState={this.props.initialState} />
```

**Comment by GabKlein** [comment]
@attrck Could you explain a bit more how you implemented it? A gist would be awesome!

**Comment by stefanRitter** [comment]
@GabKlein @attrck pre-rendering doesn't work, because context is lost. also react_ujs breaks it on the client.
I think we'll have to file an issue with react-rails - When testing it with @ryanflorence 's setup it works: http://jsbin.com/venofuqabi/1/edit?html,js,output

**Comment by stefanRitter** [comment]
Actually sorry it's not an issue with react-rails. The issue is that we want to render the app before we created a router. Like in this case where the initial state already has a handler: http://jsbin.com/mirajedadi/1/edit?html,js,console

@ryanflorence do you have an idea how to easily render the app before the router is run?

**Comment by GabKlein** [comment]
The problem would be to generate the proper `href` attribute for `Link`. Without the router enable I don't how the mapping can take place.

**Comment by mpereira** [comment]
> @ryanflorence: With 0.11.x you can do it like this now: http://jsbin.com/duyaxa/1/edit?html,js,output

I tried to build off your example but navigation doesn't seem to work. Clicking the `Link`s result in no transition. Maybe I'm doing something wrong?

http://jsbin.com/tapelidezi/1/edit?html,js,console,output

**Comment by bbnnt** [comment]
it is funny to see how server side rendering is important for some (rails ones),
and out of this world for others (js ones)

problem is, I started with rails long time ago
i'd like to get into react but my mind won't let me go further without
a clean routing AND server side rendering

Anyone got though all the problems the could have appeared in this discussion ?

**Comment by bbnnt** [comment]
@attrck is that just me or the react-rails-router's README examples are very unobvious ?

**Comment by attrck** [comment]
@bbnnt I don't know react-rails very well because I only have done frontend development in our project. 

We only pass the initial state to React app with react-rails. Code snippet from @rpflorence solved the problem with that. We haven't tried pre-rendering yet. Actually I didn't notice earlier that this conversation was about server-side rendering :smile:

**Comment by mohansandesh** [comment]
This is how I have react-router working with react-rails. With react-rails helper, pre-render 'StaticRoute' component with an additional path prop. React-router will take care of rendering the right handler in execjs.

```javascript
var StaticRoute= React.createClass({
  render: function(){
    var RouteHandler = Router.run(routes, this.props.path, function(){});
    return (
          <RouteHandler {...this.props} path={undefined} />
      );
  }
});
```

After reviewing the code I noticed Router.run returns the router instance with the current handler, which can be used to render the actual component, keeping the router context intact. The callback function in run is needed for location change setup. Which is not needed for server side rendering.

Even though SEO works well, the down side of this approach is, when react runs in the browser it gets confused because it is expecting 'Router' component, not the 'StaticRoute' component in dom. react-rails-ujs does the setup of this pre-rendered component. So before I run react-router in the browser, I remove all HTML from container, and let react do everything from scratch.
