### ISSUE TITLE
Bring back bower support

### ISSUE THREAD

**Issue by paulmillr** [rackt/react-router#2764]
What was the reason to remove the Bower support? Was it merely a "maintainers convenience"?

There are many folks who are not using the webpack stuff out there. Neither ES modules are a standard ("real, supported by browsers"). Why are we forced to download the library by hand now and run a shell script?

**Comment by taion** [comment]
https://github.com/rackt/react-router/issues/1864

**Comment by paulmillr** [comment]
@talon this does not answer my question.

> Besides, npm is a far more capable tool

Subjective and not everyone could / wants to use NPM.

**Comment by paulmillr** [comment]
>Then we can stop checking in pre-built files

Still seems like a maintainers convenience.

**Comment by ryanflorence** [comment]
We have bower support:

`bower install react-router=https://npmcdn.com/react-router@1.0.3/umd/ReactRouter.js`

We dropped `bower.json` because it doesn't actually do anything useful.

Side note: as a [bower organization owner](https://github.com/orgs/bower/people?utf8=%E2%9C%93&query=ryan), its development is completely dead and nobody is stepping up to keep it alive because it provides marginal value to a project.

> Still seems like a maintainers convenience.

Absolutely :100:

If you think a bower.json is going to make this library easier to consume with bower, then go ahead and create one of those "shim" repos. If not, then I guess we agree on how we'd rather spend our time.

**Comment by kajmagnus** [comment]
Hi,  I didn't know that one could do: `bower install --save react-router=https://npmcdn.com/react-router@1.0.3/umd/ReactRouter.js`. I think it'd be good to have that documented in the readme. I actually started attempting to build react-router myself, when I noticed that Bower support had been removed (or so I thought), but ... that wasn't needed I know now after having found this issue.
