### ISSUE TITLE
extra layer of abstraction

### ISSUE THREAD

**Issue by naw** [rackt/react-router#2767]
Perhaps I'm a bit naive, but it seems fundamentally a react-based router component needs only two properties:

1. A `currentLocation` property for the router to parse and display correct component accordingly.
2. A `changeLocation` function for `<Link>` to call to request a route change from whatever object (not necessarily a history object) "owns" that data as the single source of truth.

How the `currentLocation` property changes (i.e. set somehow by a parent component) need not be the concern of the `Router` per se, and need not come from an actual `history` object.

The current implementation assumes you want to interact with a `history` object, but I believe there could be benefits to an extra layer of abstraction. You could still have the old identical behavior with a `HistoryRouter` wrapper like this:

    <HistoryRouter history={history}>

    class HistoryRouter extends Component {
      constructor(props) {
        this.state = { changeLocation: history.push };
        props.history.listen((location) => {
          this.setState({ currentLocation: location });
        });
      }
      render() {
        return <AbstractRouter currentLocation={this.state.currentLocation} changeLocation={this.state.changeLocation}/>;
      }
    }

This would enable routed applications that don't want to use a `history` object as the source of truth to consume `AbstractRouter` directly rather than trying to interact with a `HistoryRouter` through a "fake" history object. 

My original motivation was to make a `redux` store drive the router, rather than just "syncing" with the router, which led me to give `react-router` a wrapped `memoryHistory` that I can control rather than giving `react-router` a real `browserHistory`. See here: https://github.com/rackt/redux-simple-router/issues/138

Thoughts?

**Comment by taion** [comment]
That's actually exactly how things are set up right now. Your "HistoryRouter" corresponds very closely to `<Router>`, while your "AbstractRouter" corresponds quite closely to `<RouterContext>` (`<RoutingContext>` in the current release).

**Comment by taion** [comment]
To clarify a bit, the logic you're talking about is probably more in `createTransitionManager`/`useRoutes`. That it's called `history` - it doesn't really matter, right? All it needs to have are `listen` and `push`.

**Comment by taion** [comment]
And the reason we do this is because `history`, like Redux, is not React-specific!

**Comment by naw** [comment]
Thanks for your feedback @taion 

I agree it doesn't matter that it's called `history`; what matters is what API has to be implemented in order for `react-router` to be able to consume it.  So conceptually, what API does `react-router` actually _need_?   

My pre-supposition is that a routing component need not be _coupled_ to the _actual_ URL in the address bar of the browser.

Therefore, my idea is to expose a high-level `Router` component whose interface is the _minimal_ API necessary for `react-router` to operate as a component that renders the right sub-component for a given URL and can render links to change the URL. 

As a convenience, wrappers could be exposed that take a higher-level object with a larger surface area and translate it into the minimal API that the `Router` expects (i.e. my `HistoryRouter` example).

I suppose another way of stating it is: the full API For `history` is larger than `react-router` needs, so at first glance, it seems `Router` is unnecessarily coupled to the full `history` API.  At a conceptual level, routing doesn't need to know anything about history or the address bar --- it just needs a `Location`.

Note: The full API for `history` is pretty large:

    type History = {
      listenBefore: (hook: TransitionHook) => Function;
      listen: (listener: LocationListener) => Function;
      transitionTo(location: Location) => void;
      push(location: LocationDescriptor) => void;
      replace(location: LocationDescriptor) => void;
      go(n: number) => void;
      goBack() => void;
      goForward() => void;
      createKey() => LocationKey;
      createPath(location: LocationDescriptor) => Path;
      createHref(location: LocationDescriptor) => Href;
    };


It sounds like you're saying is that the minimal API that `react-router` consumes from `history` is _actually_ smaller than it appears --- the "history" object supplied to `react-router` only needs `listen` and `push` (actually, it needs `createHref` too).

So I think that's great news, and I appreciate you pointing that out!

However, even `listen` is a larger and more complex API than conceptually necessary (i.e. as opposed to a `currentLocation` property), since `react` can already take care of "pushing" updated props out to children.

Also, it seems `createHref` is coupled to how a URL is "translated" into something in the browser address bar, which I'm pre-supposing is higher-level than a router's core responsibilities.

So ultimately, what I'm suggesting is that some refactoring could allow `react-router` to expose a more abstract interface (i.e. to a component that that performs "core" of the routing functionality), whereas the integration with a real history object is a separate (optional) piece that could be moved into a wrapper component. I believe this would make the system as a whole less tightly coupled to `history`, and thereby more useful.   (Note: `RouterContext`, is _much_ lower level than I'm talking about).

I'm not sure if you disagree there is benefit to such an approach at all, or if you see the benefit, but feel the benefit is too small compared to the cost of change?

**Comment by taion** [comment]
Let's go through these one by one:

- `listenBefore`: This is required for transition hooks for confirming navigation. We may also use this for async transitions in the future.
- `listen`: Required, obviously.
- `transitionTo`, `push`, `replace`, `go`, `goBack`, `goForward`: These reflect different methods of doing navigation - the router at some level might only need a subset of these, but people building websites often want to implement things like a "go back" button that actually does `history.goBack()`, or interact with the history stack in any number of other ways
- `createKey`, `createPath`: These are used internally - the router doesn't use them, but they have to be exposed because of how history inheritance works
- `createHref` needed to create links

You should think of `history` v `<Router>` in the same way perhaps that you'd separate a Redux `store` from a `<Provider>` and relevant friends.

It's not about whether what React can or cannot do - for various purposes like doing server-side rendering, we actively want to separate out bits of matching logic from React's rendering loop anyway, because route matching e.g. isn't synchronous/whatever.

I think you have the kernel of an interesting idea, but that you're not aware of the scope of use cases that we need to support. You can see quite clearly what the router actually uses - the rest is for users.

**Comment by taion** [comment]
Long story short, you can pass in as minimal a `history` as you want to the router. However, I think your approach is not going to work with things like allowing transition blocking. Also, the separate `listen` API pays its way by letting us support async transitions/routes and server-side rendering much more nicely.

**Comment by naw** [comment]
> but that you're not aware of the scope of use cases that we need to support.

Yes, definitely true, and you've pointed out some of those use cases that you want to support. I suppose what's not obvious (to me) is whether those use cases are actually mutually exclusive with my suggestion, but since you have greater knowledge of the use cases as well as the intricacies of the code, I'll assume for now that I've just missed something.

I appreciate your patience and thorough replies.

**Comment by taion** [comment]
To elaborate a bit more, the issue is that the actual matching process in the router itself is asynchronous, which is why the React-style API from `history` wouldn't be especially helpful, since we don't actually necessarily re-render immediately upon a `history` update, but instead only upon completion of route matching. This is also why `match` takes a callback for SSR.

I've dropped a comment outlining the main caveats I have with your approach on your RSR issue - it'll be interesting to see how things shake out there, but as it stands the reasons I've outlined in the above paragraph lead us pretty strongly to make the "React" integration point be roughly where it is (i.e. after route matching).
