### ISSUE TITLE
Make history a regular dependency?

### ISSUE THREAD

**Issue by Pomax** [rackt/react-router#2777]
NPM3 doesn't do peer dependencies anymore, but it also changed how depencencies are installed. Owning projects now get all dependencies installed flat, so if the project requires react-router, which requires, history, it'll just install both of those "top level", as `node_modules/react-router` and `node_modules/history`, rather than nesting the latter as `node_modules/react-router/node_modules/history`.

This means it's much better at deduping, solving the problem of needing to "manually" install what used to be peer dependencies: just make what you need regular dependencies, and npm will happily skip over it if it's already used by something else, too, as it all lives at the same depth.

**Comment by taion** [comment]
This is already happening.

Also, npm3 still does peer dependencies just fine.

**Comment by Pomax** [comment]
Nice, looking forward to the README update, then, which currently says **"Note that you need to also install the history package since it is a peer dependency of React Router and won't automatically be installed for you in npm 3+."**

**Comment by timdorr** [comment]
We have that message on the README on master because it's the most visible part of our documentation and the current released version (1.0.3) still has the peer dep. Most people reading it aren't aware of the internal changes coming in the code base, they just want to get started using something right now.

**Comment by taion** [comment]
Peer dependencies are _not_ deprecated in npm3. It is true that npm3 will not automatically install them for you, but it will warn you if you have an invalid configuration. Given the issues people have had with npm2's peer dependencies, it's probably all for the best.

Just to reiterate:
# Peer dependencies are NOT deprecated in npm3. Please don't say they are. It's incredibly confusing to anybody who might come across this later on.

**Comment by Pomax** [comment]
dude, no need for the font size 250%, just link to the official NPM docs that state that it's not deprecated. I'm just reading back to you what *you* said to me via your own README.md, don't take that out on me.

**Comment by ryanflorence** [comment]
Sorry @Pomax, we get probably one issue like this per day, and its getting incredibly frustrating for us. Perhaps you misunderstood @taion's gigantic font for yelling, I think he was just trying to make it impossible to miss in this thread. I kept a bit of gigantic font, but not the whole thing :)

Also, I opened this a while ago because this is getting ridiculous: https://github.com/npm/npm/pull/10846

**Comment by taion** [comment]
:+1: thanks @ryanflorence
