### ISSUE TITLE
Problems with rendering routes server side.

### ISSUE THREAD

**Issue by perjg** [rackt/react-router#2818]
I'm trying to set up server side routing with react-router according to this documentation:
https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ServerRendering.md

This does not appear to work correctly together with Route and IndexRoute.
(Running react-router 2.0.0-rc3, but same problem happens with 1.0.3)

I am using this code based on the example code:

```
import React from 'react';
import ReactDOM from 'react-dom';
import ReactDOMServer from 'react-dom/server';
import { IndexRoute, Route, match, RouterContext } from 'react-router';

// UI Components
import Blog from './blog';
import Home from './home';
import NoMatch from './nomatch';

function test(url) {
	const App = React.createClass({
			render: function () {
				return (
					<div>
						{this.props.children}
					</div>
				);
			},
		}),
		routes = (
			<Route path='/' component={App}>
				<IndexRoute name='home' component={Home}/>
				<Route path='blog' component={Blog} />
				<Route path='*' component={NoMatch} />
			</Route>
		);

	match({ routes, location: url }, (error, redirectLocation, renderProps) => {
		let html = ReactDOMServer.renderToString(<RouterContext {...renderProps} />);
		console.log(html);
	});
}
```

test('/');

This renders the Home component correctly:
<div data-reactid=".1s4d3gcxds" data-react-checksum="1923750606"><div data-reactid=".1s4d3gcxds.0">HOME</div></div>

test('/blog');

This doesn't render any route:
<div data-reactid=".izc0i6ng8w" data-react-checksum="-20771659"></div>

The reason is that this.props.children is null.

(Note: The same error happens on 1.0.3, the only difference is that RouterContext is called RoutingContext).

A more complete working example for server side rendering would be helpful.

**Comment by timdorr** [comment]
Note that 1.0.0 doesn't have named routes, so that prop is ignored on `IndexRoute`.

However, I'm not seeing anything obvious. And we want to make sure that the GitHub issue tracker remains the best place to track bug reports and feature requests that affect the development of React Router. Could you post this question to Stack Overflow with the tag #react-router? https://stackoverflow.com/questions/ask?tags=react-router That will get more appropriate visibility.

We also have an active and helpful React Router community on Reactiflux, which is a great place to get faster help. You can join at https://discord.gg/0ZcbPKXt5bYaNQ46.
