### ISSUE TITLE
Setting Page Title

### ISSUE THREAD

**Issue by zackify** [rackt/react-router#2844]
I came up with a way to easily set the page title on route changes, but I'm wondering if there is a more "correct" way. My route objects looks like: 

```js
module.exports = {
  path: 'login',
  title: 'Login',
  getComponent(location, cb) {
    require.ensure([], (require) => {
      if(typeof document != "undefined") document.title = this.title
      cb(null, require('../../views/account/login.jsx'))
    })
  }
}
```
I'm setting the title here, and when using `Link` the title will change inside of the require.ensure, seems to be the best way to do it right now, although it feels like a huge hack. 

When I server render, I grab the title from:

```js
let title = renderProps.routes[renderProps.routes.length - 1].title
```
This doesn't feel right, is there no way to grab the current route object from `renderProps`?

Is there any way to do these two things better?

**Comment by jimbolla** [comment]
I use https://github.com/nfl/react-helmet

**Comment by taion** [comment]
Yeah - your route components get a `routes` prop that contains all the matched routes. Put the title information on there, then use React-Helmet or something equivalent (from some high-level route).

**Comment by PierBover** [comment]
Isn't there a best way of defining the title yet?

Something such as: `<Route path="login" title="Login" component={Login}>`?

**Comment by taion** [comment]
And if more than one route defines `title`?

We want to be opinionated, but at some point it would be unreasonable.

Use a router middleware and process your routes there if you want.

**Comment by PierBover** [comment]
Ok.

Just in case... the title is for setting the name of the page that appears on the list when you hold and press the back button of the browser, right?

**Comment by johnfn** [comment]
...and if more than one route defines `title` you could declare a function that returns a string for title.

It shouldn't require an add-on to the router to do something as simple as setting a document title.

**Comment by PierBover** [comment]
I agree @johnfn .

I don't know why `react-router` is so unpractical. Vue Router in comparison is a joy to use.

**Comment by zackify** [comment]
First, can't believe I even asked this a year ago, second, React router is not impractical. Just set page titles inside of your components that are rendered on specific routes. Not a big deal.

**Comment by PierBover** [comment]
The problem is not setting the page title (as in the title that appear in the tab of your browser), but the title that is sent to the history API. In other words, the title that appears in the browsing history when you long press the back button in your browser.

Since the router is the one interacting with the history API it makes sense that it should be its responsibility to do that.

**Comment by timdorr** [comment]
I would bring that up in [the history repo](https://github.com/ReactTraining/history). That's where the solution is going to live.

**Comment by zwhitchcox** [comment]
@taion

Could you provide some code on how you would set up that middleware?

Like how exactly do you add middleware to react-router? Or is it like @timdoor said, you're supposed to add middleware to the history object?

My ideal solution would be something like other people have suggested

`<Router exact path="/" title="hello" component={Cmpt} />`

Is there a way to add middleware where I could just say

```js
router.onChange(route => {
  document.title = route.title
})
```

Multiple routes could still call the same function though, but that would be ok, because the last rendered route would be the furthest nested route, which means that the most inner route, which would be the most specific route would decide the title.

Or perhaps there could be a situation where you want to concatenate different routes. For example, if you have a user page and a sign in page, you could have the routes nest like this:

```js
router.onChange((route, path) => {
  /^\/user/.test(path)
  document.title = document.title + " - " + route.title
})
```

So, `/user` would set the title to "User", but the nested route would add "User - Sign in". That way you could also have a global title that is on every page like the main page of your app.

So, you could say something like for your home page, if you have a layout:

`<Route path="/" component={Main} title="App Name" />`

Then in the `Main` component, you have

`<Route path="/" exact component={Home} title="Home" />`

Then, for your middleware, you have

```js
router.middleware((path, route) => {
  if (path === "/" && route.title !== "Home")
    document.title = route.title
  else
    document.title = document.title + " - " route.title
})
```
