### ISSUE TITLE
IndexRedirect not passing query

### ISSUE THREAD

**Issue by gabrielenosso** [rackt/react-router#2930]
In an example like the one below, the IndexRedirect is ignoring the "query" prop:

```javascript
<Router history={history}>
   <Route path="/" component={App}>
     <Route path="events" component={EventsPage} />
     <Route path="masterdata" component={MasterDataPage} />
     <IndexRedirect to={'/events'} query={{ player: 23 }} />
   </Route>
</Router>
```
Moreover, it would be maybe more consistent to use for both Redirect and IndexRedirect the same way to pass the new path to the Link components (using Location describer: {
   pathname: '/events',
  query: { player: 23 }
})

**Comment by taion** [comment]
Using a pattern like `<IndexRedirect to="/about" query={{ the: 'query' }} />` works just fine for me. Possibly something wrong with your history setup? (Try this w/e.g. the active-links example.)

We can't really use location descriptors in `to` for `<Redirect>` because of the specific semantics there around merging `location.query`/&c. with `route.query` when specified. In the more general redirect case, I think it's generally desired to forward those; if needed, you can always write a custom redirect component that suits your specific needs.

**Comment by gabrielenosso** [comment]
The strange thing is that the Link component works completely fine: it adds the query params in the URL after the '?'.
With IndexRedirect nothing happens.

I'll try to find out why :)

**Comment by gabrielenosso** [comment]
Maybe I found out why it doesn't work: I'm using redux-simple-router and it seems that it's not passing query params at all.

Thank you anyway :)

**Comment by taion** [comment]
This was the same as https://github.com/rackt/react-router/issues/2917, BTW. Fixed on master of history.
