### ISSUE TITLE
Only render with matching Route

### ISSUE THREAD

**Issue by dcramer** [rackt/react-router#651]
When pulling react-router into an existing project it'd be ideal to not have to recreate 100% of the application, or alternatively to add complex logic, just to use routes.

Ideally this would look something like:

- Build your react application as you would (with react-router)
- Run RouteHandler, if it matches, Router.run() (or whatever the equiv is)
- If no match is found, no-op (i.e. assume the page is already doing what its supposed to do)

**Comment by rpflorence** [comment]
closing since this is a question, but happy to engage in a conversation.

Is this an existing react app you have? Or are you bringing react into it? If you're bringing react into it, then just create routers on the pages that are in react. When two "sibling" parts of the app are rewritten, bring them together, the router makes this incredibly easy.

**Comment by dcramer** [comment]
This actually turned out to not be a concern. react-router handles it exactly as I'd want (<a> tags dont get intercepted)
