### ISSUE TITLE
How to use Scrolling mixin?

### ISSUE THREAD

**Issue by Radivarig** [rackt/react-router#671]
I am trying to save scroll position in react components so when I go back/forward in history that scroll positions load to where they were last. I tried getting window.scroll myself to save it in localStorage and load later but it is always (0,0). Can someone give me example of proper usage of Scrolling mixin?

**Comment by gaearon** [comment]
Router does this by default.

**Comment by gaearon** [comment]
Maybe it's not happening because by the time of transition the data has not loaded, and window height is smaller? If you cache data, scroll position is preserved on Back/Forward transitions.

**Comment by Radivarig** [comment]
How would I do that? Component is simple list just to get something to scroll, don't think this should be too much to handle to create a delay. Can you link me to where I can see that is default please?

**Comment by gaearon** [comment]
This is how default scroll begavior works:
https://github.com/rackt/react-router/blob/master/modules/behaviors/ImitateBrowserBehavior.js

You can supply your own via `scrollBehavior` option in `Router.create`. In your strategy, you can set a delay before updating scroll position.

But this won't be bulletproof because you don't know how long it might take to re-fetch the data. Much better to cache it so Back/Forward is instant. Flux architecture is handy for implementing this kind of caching.

**Comment by Radivarig** [comment]
From your link, what happens if the case is PUSH? 
 `
...
switch (actionType) {
      case LocationActions.PUSH:
      case LocationActions.REPLACE:
        window.scrollTo(0, 0);
        break;
...
`

**Comment by gaearon** [comment]
It's falling through so same as REPLACE: scroll to top.

**Comment by mjackson** [comment]
@Radivarig Can we close this?

@gaearon Thanks for your help! :)

**Comment by Radivarig** [comment]
Give me few days please. I'll close it

**Comment by rpflorence** [comment]
closing because my mom says a few is 3-4 and several is 5-7 and its been 6 days :P Let me know if we should reopen.
