### ISSUE TITLE
Inconsistent behavior of param decoding between server and client

### ISSUE THREAD

**Issue by BerkeleyTrue** [rackt/react-router#702]
* Be on server
* Be the router
* See request for `/posts/new%20title`
* Match to Route `/posts/?:id?` 
* Create state with `state.params.title = 'new%20title'`
* Be on client
* Be the router
* See request for `/posts/new%20title` 
* Match to Route `/posts/?:id?`
* Create state with `state.params.title = 'new title'`
*  Watch dev question life itself.

**Comment by BerkeleyTrue** [comment]
Narrowing it down, it seem to be an issue with passing the `req.path` directly to router.run, while on the client I am using History Location which decodes the path internally. 

Is this the desired effect? 

If not it seems that adding `location = path.decode(location)` after https://github.com/rackt/react-router/blob/master/utils/createRouter.js#L175 would solve this issue.

My workaround is to call decodeURI in the req handler before passing on the location string to Router.run i.e. `Router.run(routes, decodeURI(req.path), cb)`

**Comment by tcoopman** [comment]
I would love to have this fixed as well. I believe there is a similar problem where `state.params.title` would be `new+title`.

example

`<Link to='page' params='new title'>New title</Link>` will have 'new+title' in the url. Going to `/page/new+title` gives as params: `new+title` instead of `new title`

**Comment by mjackson** [comment]
The router expects you to give it a decoded path. Inside the router, it makes things a lot easier if we just assume that every path we see is already URL-decoded. That way we don't have to guess and risk double-decoding a URL.

@BerkeleyTrue For now I'd say your "workaround" is the way to go server-side. If you're using a framework that gives you decoded paths, you're all set. If not, you'll need to wrap it in a `decodeURI` as you're doing. Of course, you don't have to worry about this client-side because the router takes care of it for you.

@tcoopman The problem you're describing was fixed earlier today in 20c2c9b6fd5797504b0ff9ba37261173a9164571. Now, spaces in path names is properly encoded as `%20` instead of `+`, and decoded as a space.

**Comment by BerkeleyTrue** [comment]
maybe docs and examples using express should document this to prevent further confusion, for example here https://github.com/rackt/react-router/blob/master/docs/guides/server-rendering.md
