### ISSUE TITLE
path params with '+' in them being replaced with a space, breaks path

### ISSUE THREAD

**Issue by kellyrmilligan** [rackt/react-router#716]
I traced it down to utils/Path, 

Path.decode
Path.js:41 function (path) {
	    return decodeURI(path.replace(/\+/g, ' '));
	  }

HistoryLocation.js puts the url in the history object with the + sign intact. 

in 

function notifyChange(type) {
  var change = {
    path: getWindowPath(),
    type: type
  };

this calls Path.decode which mangles my url that has a slug in it. 

examples: 

Path.encode(path)
"/places/second-bar-+-kitchen-201-congress-ave-austin-tx"

Path.decode(window.location.pathname)
"/places/second-bar- -kitchen-201-congress-ave-austin-tx"

I end up making an XHR request for this path, and it inserts %20, which is not correct. 

I'm using server rendering, and when I load this same page server side, express keeps the + sign in the url param, so it works.

**Comment by kellyrmilligan** [comment]
Is there something that would break if we did this in historylocation.js?

function getWindowPath() {
  return window.location.pathname + window.location.search;
}

?

**Comment by rpflorence** [comment]
if you've got some time, can you send a PR with a failing test case? This is incredibly helpful.

**Comment by kellyrmilligan** [comment]
Will try, it's only failing on the other side of the equation for my use.

**Comment by mjackson** [comment]
A location's `getCurrentPath` method should always return a *decoded* path. Once we're inside the router, we don't want to worry about whether or not paths are URL-encoded or not. We just assume all paths are decoded. So removing the `Path.decode( ... )` from `getWindowPath` would break things.

Similarly, a location's `push`, and `replace` methods should always expect their path argument to be decoded since it's coming back out of the router. Thus, they need to `Path.encode( ... )` before handing URLs over to the DOM (i.e. `window.location = ...;`)

There was a double-encoding bug that I fixed earlier today in fe5ec395f98e1d063539dd2211b590dd0840de59. I'm not sure if it had anything to do with your use case, but you might try running your code on master to see if it still exhibits the problem.

**Comment by mjackson** [comment]
ok, I figured out what's going on here. Apparently + is a special character in query strings, but not in the path portion of the URL. Gonna push a fix shortly.

**Comment by kellyrmilligan** [comment]
Awesome, hah sorry I didn't have time today to provide more info. Yeah that is exactly it! I'll look for the push to npm and switch back to using paths from the router
