### ISSUE TITLE
Setting activeClassName based on the root?

### ISSUE THREAD

**Issue by OscarGodson** [rackt/react-router#736]
We have a persistent sidebar on the left with top level page links and on the right we have the app content. activeClassName appears to only work if the URL is exactly the same so using an email client as an example, if you have an "inbox" link in the left sidebar and go to `/inbox` it lights up (good!) but if you click into an email and go to `/inbox/:id` then the activeClassName goes away. Is there an option or something to get it to match even on `/inbox/:id` or deeper?

**Comment by insonifi** [comment]
I've just was dealing with the problem, and turns out it already works like this. My mistake was, that when I generated links for my navigation I provided *paths* to `Link`. If you use *names* it works out-of-the-box.

Here's my code:
```javascript
render: function () {
        var routes = this.getRoutes()[0].childRoutes,
        return <div className='nav'>
            <ul className='nav-layout'>
                {routes.map(function (route) {
                    console.log(route.path, isActive(route.path), path);
                    return <li key={route.path} className='nav-layout-unit'>
                        <Link to={route.path} className='nav-item'>{route.name}</Link>
                    </li>
                })}
            </ul>
        </div>
    }
```
Notice this line:
```javascript
<Link to={route.path} className='nav-item'>{route.name}</Link>
```
I you put `{route.name}` instead of `{route.path}`, and it works now. Apparently, if you use *path* it triggers *Path.isAbsolute* in *State.isActive*, which then goes for exact comparison. If your route isn't absolute it will iterate over currently active routes and activate all parents. See [StateContext.js
] (https://github.com/rackt/react-router/blob/005f55487814328413e8009deb570813e47793a7/modules/StateContext.js#L71)

**Comment by OscarGodson** [comment]
@insonifi hm. Pretty sure thats what I have. My code:

```js
        <Link to={this.props.url} className="__link" activeClassName="__link--active" onClick={this.navAnalytics}>
          <i className={iconClassList}></i>
          <span className="__title">{this.props.name}</span>
        </Link>
```

Then I have an array of nav items, say, like this:

```js
  navItems: [
    {
      name: 'Settings',
      url: 'settings',
      icon: 'settings'
}
```

And my route for it is:

```
    <Route name="settings" handler={Settings} addHandlerKey={true} />
```

I believe thats what you have, right?

**Comment by rpflorence** [comment]
You'll need to introspect the routes, use the `State` mixin and look for the routes that matter in `this.getRoutes()`. If you find what you're looking for, add a class to your nav item.
