### ISSUE TITLE
Async webpack chunks support

### ISSUE THREAD

**Issue by Schniz** [rackt/react-router#751]
[Like they use on Instagram](https://www.youtube.com/watch?v=VkTCL6Nqm6Y). it looks awesome.
Wrote a simple component as a POC: https://gist.github.com/Schniz/7096536612e8a2151d81

could be great to get this as a react-router feature. However, seems like it breaks the server rendering. so..

**Comment by gaearon** [comment]
Note `transition.wait` is gone and you should use a callback now.

I don't think it needs to be in core (especially because it's specific to Webpack), and as you showed it's easily implemented!

How does your code work before require is ready? I think React allows returning null from render, not undefined.

You should probably proxy willTransitionFrom as well. 

Another thing I would change in your example is that you ignore that nested route handler may want to delay the transition on its own. I'll post an example that does that (and works with current router's version) soon.

**Comment by gaearon** [comment]
Here's what I'm using:

https://gist.github.com/gaearon/fbd581089255cd529e62

It fixes problems I described above and works with RR 0.11.x.

**Comment by gaearon** [comment]
I thought more about it and realized that if I proxy `willTransitionTo`, I won't ever get to “not ready” state in `render`. So your example is more correct in that respect than mine.

I amended my example to reflect this:

```js
function createAsyncHandler(getHandlerAsync, displayName) {
  var Handler = null;
 
  return React.createClass({
    displayName: displayName,
 
    statics: {
      willTransitionTo(transition, params, query, callback) {
        getHandlerAsync().then(resolvedHandler => {
          Handler = resolvedHandler;
 
          if (!Handler.willTransitionTo) {
            return callback();
          }
 
          Handler.willTransitionTo(transition, params, query, callback);
          if (Handler.willTransitionTo.length < 4) {
            callback();
          }
        });
      },
 
      willTransitionFrom(transition, component, callback) {
        if (!Handler || !Handler.willTransitionFrom) {
          callback();
        }
 
        Handler.willTransitionFrom(transition, component, callback);
        if (Handler.willTransitionFrom.length < 3) {
          callback();
        }
      }
    },
 
    render() {
      return <Handler {...this.props} />;
    }
  });
}
```

However, this is not very good by itself, because we give no feedback to the user at all. I wonder if there's a way to both show loading feedback *and* have `willTransitionFrom/To` behave as expected for async handlers.

**Comment by edygar** [comment]
What if your Handler was an LoaderComponent which renders the loading feedback and, when it did mounted, 'require.ensure' is done?

**Comment by geekyme** [comment]
@gaearon Thats interesting. What is that ```getHandlerAsync``` that you are using and how does it get webpack modules?

**Comment by gaearon** [comment]
Oh, it's basically the same as the OP wrote (using `require.ensure` under the hood). I'm just using a promise-returning function because sometimes you need to do something else after getting a module (for example, if it exports several components).

**Comment by geekyme** [comment]
If its not a trouble could you update your gist with usage examples of using a promise? https://gist.github.com/gaearon/fbd581089255cd529e62

**Comment by geekyme** [comment]
Also does your implementation break server side rendering like OP mentioned? o.O

**Comment by rpflorence** [comment]
I want to make this easier, please follow the discussion on #755

**Comment by gaearon** [comment]
>Also does your implementation break server side rendering like OP mentioned? o.O

Well it doesn't have to. Just don't use `require.ensure` on server and instead return module synchronously.

**Comment by gaearon** [comment]
@geekyme I added usage example: https://gist.github.com/gaearon/fbd581089255cd529e62#comment-1385047
