### ISSUE TITLE
Make record/replay possible

### ISSUE THREAD

**Issue by gaearon** [rackt/react-router#757]
Record/replay is possible with Flux: just serialize all payload and later run the serialized actions one by one. However this wouldn't work with React Router. You can't integrate it into Flux cleanly because `Router.run` callback gives you `Handler` which is not serializable. You can't “record” handlers and play them back.

It *would* be possible if we could store `state` returned by `Router.run` in Store and somehow construct the `Handler` on our own in this Store's changed handler. Something like

```js
Router.run((Handler, state) => {
  RouterActions.change(state); // our Flux action
});

var Root = React.createClass({
  mixins: [createStoreMixin(RouterStore)], // our Flux Store

  getStateFromStore() {
    return {
      routerState: RouterStore.getRouterState()
    };
  },

  render() {
    var { routerState } = this.state;
    var Handler = somehowMakeHandlerFromSavedRouterState(routerState); // ?????
    return <Handler {...routerState} />;
  }
})
```

I also have a feeling this may enable other use cases I can't think of right now, as it's just a more generic approach.

Does this make sense?

**Comment by tcoopman** [comment]
To me this makes sense, I have been playing with a similar idea but don't have any real code yet.

A `somehowMakeHandlerFromSavedRouterState(routerState)` method would be nice, because my idea doesn't go so far at the moment yet, I mostly use my idea to store and fetch query parameters at an end node compoment so I can link to it with saved query parameters: `<Link to={route} query={RouterStore.getQueryParamsFor(route)}>custom route</Link>`.

I have been taking about a more general use case, but haven't gotten to it yet.

**Comment by rpflorence** [comment]
this is a great idea.

**Comment by gaearon** [comment]
Another issue is `state.routes` being unserializable due to `handler` function references. If we want to implement this, we need to make sure `somehowMakeHandlerFromSavedRouterState` works even if we strip them handlers out.

**Comment by mjackson** [comment]
The main reason we create and give you the `Handler` is because React will blow away the DOM if you don't re-use the same handler each time, which *I think* means that we would need a way to return *the same object* from `somehowMakeHandlerFromSavedRouterState` for a given router state.

**Comment by gaearon** [comment]
> React will blow away the DOM if you don't re-use the same handler each time

This is correct but we can make `somehowMakeHandlerFromSavedRouterState` be a router method, no? Kinda like `Router.getHandler()`. It would be the same handler, but there's no need to hand it out to the client code in callback.. I think.

Please correct me if I'm not thinking straight

**Comment by rpflorence** [comment]
For clarity:

```js
var Handler = React.createClass() { render () { return <div>hi</div> } };
var Handler2 = React.createClass() { render () { return <div>hi</div> } };
React.render(<Handler/>, document.body, () => {
  React.render(<Handler2/>, document.body);
});
```

Since the class is different, the DOM is not reused so `somehowMakeHandlerFromSavedRouterState` would depend on some internal, non-serializable state.

**Comment by gaearon** [comment]
Isn't Handler returned by router in run callback just the router instance?

I don't really see what information Handler carries at this point, it seems like you can just put return value of Router.create in there.. Or not?

**Comment by mjackson** [comment]
@gaearon I've been doing a lot of thinking about this issue ever since you posted it, and I'm pretty sure that the `state.routes` array is the only thing preventing us from being able to do this right now. We can work around everything else, but `state.routes` is not (and probably won't ever be) serializable.

Just thinking about this some more, one thing we do have is `router.match`, which currently returns a `Match` object for a given path. Since the `path` is serialized to the state, if you need to get an array of routes from a router you could always just use that. So, basically slim down the state to only contain stuff that is serializable and provide methods to get the pieces that you may need that aren't.

Sorry for the brain dump..

**Comment by gaearon** [comment]
I haven't thought much about it, but I still don't understand why we need to carry `routes` in `state`.

Record/replay should be perfectly possible between two same versions of the app if router keeps `routes` private. When replaying, app will initialize just like it does normally, meaning `Router.create` will be called with same parameters, and thus route config will be the same.

Does `routes` really need to be exposed in `state`? Can't router just figure it out based on route config and current path? That's how it generates it in the first place.

**Comment by mjackson** [comment]
> Does routes really need to be exposed in state?

No, it doesn't. You should be able to generate the same array with `router.match(state.path).routes`. So it seems the top-level API just needs a little work.

**Comment by ryanflorence** [comment]
pretty sure we can do this now, let me know if it doesn't @gaearon
