### ISSUE TITLE
`RouteHandler.routeParamsTypes` static

### ISSUE THREAD

**Issue by ryanflorence** [rackt/react-router#759]
Like `propTypes` but for route handler params, that converts stings to numbers and stuff.

Idea c/o @petehunt

**Comment by gaearon** [comment]
But they will have runtime behavior, right (converting)?
As opposed to `propTypes` which have no effect other than warning.

Can/should we somehow articulate that?

**Comment by mjackson** [comment]
AFAIK `propTypes` doesn't actually do any conversion. It just checks existing types which, in the case of params, are all going to be strings. Also, we already do two levels of param checking when:

1. we check to make sure nested route paths have all params their parents require and
2. we use the pattern we generate to match on the path

So I guess I don't really see the point.

**Comment by mjackson** [comment]
Related: mach's [`Message#getParams` method](https://github.com/mjackson/mach/blob/2a3ecae63ff75868c7a1e20fff4409ab38e89b7d/modules/extensions/server.js#L23-L77) "filters" request parameters based on a conversion function.

**Comment by rpflorence** [comment]
> So I guess I don't really see the point

@petehunt what's the point? :smile:

**Comment by tgecho** [comment]
To me, the main point is the ability to specify the desired type (string as the default, with integer as the most common alternate) at the boundary rather then needing to post process params everywhere to ensure they're the right type. Often Javascript's auto-coercion sloppiness lets you get away with this until it doesn't.

As reference, Flask allows you to specify urls with embedded conversion information:
`"/users/<int:user_id>"`. This affects both matching and conversion. In theory I'd be happy with just conversion, though that could throw an error if the route matches an unconvertible string.

**Comment by ben-davis** [comment]
We had a need for this today. We have a url scheme that looks like this (for YPlan an events startup in London)

    // event url
    /:city/:slug-:eventId/

    // collection url
    /:city/:collectionId // collection

Examples might be `/london/myevent-123/` for an event and `/london/my-collection` where the only way to differentiate the two is the event url ends with a numeric id, whereas the collection slug can never end with a numeric value. Having the router only match the event handler if `:eventId` is `[0-9]` would solve this.

Any chance I'm missing a different solution to the problem? Happy to make the change if this would be useful to others and a syntax for type declaration can be decided.

**Comment by conatus** [comment]
+1

**Comment by conatus** [comment]
Hey @ryanflorence - is the issue here being handled elsewhere hence the closure?

**Comment by lelandrichardson** [comment]
@ryanflorence I'm also curious as to whether or not this is being handled anywhere else, or just closed. It's a feature I'd very much be in favor of.

I had the following scenario the other day which this would have been very helpful for:

1. I had a "page" param that was (in practice) of integer type, and was 1-based
2. The "page" param was optional, and if omitted, defaulted to "1" (ie, the first page)
3. I had a 3rd-party pager component that was expecting a 0-based index, thus I was commonly needing to do +1 or -1 arithmetic on the param value.

This required the following to be used in a couple of places:

```js
(+this.getParams().page) || 1
```

Rather than the much friendlier and less error-prone:
```js
this.getParams().page
```

These 3 contexts led to very ugly type coercion code that would have been great to be avoided if:

1. routes could define parameter types and type coerce them properly
2. parameters could optionally define default values when not in the route


I would be very much in favor of adding this as a feature to react-router. 

As an additional reference, ASP.Net MVC route definitions have this capability and handle it quite well in my opinion. An equivalent JS api would maybe look like the following:


```js
Route("foo/{bar}") // bar is a string, and required
Route("foo/{bar?}") // bar is a string, and optional
Route("foo/{bar:int}") // bar is an int, and required
Route("foo/{bar:int=2}) // bar is an int, and optional (default is 2)
Route("foo/{bar=baz}" // bar is a string, and optional (default is "baz")
```
An additionally powerful feature is the ability to define common route constraints:

```js
Route("foo/{bar:int:min(2)}") // bar is in int, required, and must be > 2
Route("foo/{bar:maxlength(4)}") // bar is a string, required, and must have length <= 4
Route("foo/{bar:}")
```

And even be able to define custom constraints:

```js
// defining the "min" constraint as an example...
Route.constraints["min"] = function (option) {
  // `option` is the string which was passed in to the constraint (ie, "2" for "{bar:int:min(2)}")
  // we must return a predicate function which is passed in the string value of the param it's
  // constraining (note, could pass in the typed value instead....)
  return param => (+param) >= (+option);
};
```

**Comment by tylerbwilliams** [comment]
This would be a great feature to have.  However, rather than creating a whole new URL scheme, it would be great if we could just use an Express-style RegEx to run against the param.

The most common case I would see this is for numeric id's:

```javascript
<Route path="/products/:id(\\d+)" handler="ProductSingle" />
```

I figure the port from Express would be simple enough to install.

**Comment by lelandrichardson** [comment]
@tylerbwilliams agreed we wouldn't want to dramatically change the syntax in place. Backwards compatibility is ideal.

That said, for me getting default values and type coercion was the more important piece of this puzzle (rather than just regex constraints).

Since we're already using jsx, we actually don't have to invent a new path syntax... what if we did this instead:

```
<Route 
        path="/foo/:id/:slug" 
        defaults={{ slug: "default-slug" }} 
        types={{ id: Number }}
        handler={Foo} />
```

**Comment by tylerbwilliams** [comment]
@lelandrichardson  I do think using JSX ( or just vanilla React, if that's your flavor ) is probably a better solution than embedding the match directly into the path string.

But I would still suggest allowing developers to have the option to use a prototype ( like Number, Boolean, etc ) to type check, or utilize their own RegEx.  If the whole param has to match a specific type, if fails to handle cases like @ben-davis above, or if there are other constraints.

If embedding RegEx is still a rough sell, I would just go for allowing a function that takes the param and returns true or false depending on whether it matches that particular route.  We could use any synchronous pattern matching we'd like then (and skip the route if all validations don't pass, naturally).

I know it's an example, but I'd be interested in knowing how those defaults are intended to work?

**Comment by lelandrichardson** [comment]
@tylerbwilliams 

I am liking the idea of using additional props on the `<Route />` as well, instead of inventing more syntax for the route.

There are three design goals here:

1. Constraints: specify certain conditions that a parameter might need to meet
2. Type coercion: specify a type that the route ought to coerce a param into (if constraints are met)
3. Default values: allow some params to be optional in the route, and if omitted, use a default instead.

Often times 1 and 2 go hand in hand (ie, must be an integer, and should coerce into a number). It would be nice if we could specify an interface that handled them both in generality.

One such interface could just be a function which returns a non-falsy converted value (provided it meets the desired conditions):

```js
var range = (lower, upper) => {
  return value => /\d+/.test(value) && +value >= lower && +value <= upper && +value;
}
...
<Route 
    path="/foo/:id" 
    types={{ id: range(1,10) }}
    handler={Foo} />
```

This has an issue where it wouldn't work if a "falsy" returned value is a valid "pass" for the function. This seems like a legitimate situation, especially for the cases `false`, `0` and `""`

We could narrow down the interface such that the only return value that means "fail" is `undefined`.

Thus, the above would become:

```js
var range = (lower, upper) => {
  return value => /\d+/.test(value) && +value >= lower && +value <= upper ? +value : undefined;
}
```

In this case you could also allow the use of the primitive prototypes as valid "type" values, but we could check for them in the code (would probably only want to check for `Number` and `Boolean`). For instance, in the checking code we could do something like:

```js
function buildMatcherFunction(passedIn) {
  switch(passedIn) {
    case Number: return builtInTypeCheckerForNumber;
    case Boolean: return builtInTypeCheckerForBoolean;
    case undefined: return (x=>x);
    default: return passedIn;
  }
}
```

Also, you asked about the default params. My intention would be for them to work like this:

Let's say we have the route:
```jsx
<Route 
    path="/foo/:page" 
    defaults={{ page: "home" }} 
    handler={Foo} />
```

The following routes/urls should resolve as follows:

```
"/foo/some-page" => Foo({ params: { page: "some-page" } })
"/foo/other-page" => Foo({ params: { page: "other-page" } })
"/foo" => Foo({ params: { page: "home" } })
"/bar" => NotFoundRoute()
```

**Comment by oncletom** [comment]
I see the issue is closed but has it been solved/implemented?

OpenAPI schemas are quite good to define routing so if there is anything to do, maybe there is some inspiration to take from there (might help creating bridges).

**Comment by kristiandupont** [comment]
Was this closed because it was deemed out of scope? Or is there some workaround that I am not aware of?
