### ISSUE TITLE
Question: component handling multiple routes.

### ISSUE THREAD

**Issue by nw** [rackt/react-router#782]
I am probably handling the component lifecycle incorrectly, looking for clarity.

Say I defined two different routes that are handled by the same component.

```jsx
   <Route path="/" handler={Component} />
   <Route path="/something/:id" handler={Component} />
```
When the component loads I'm using the flux pattern (fluxxor) to trigger an action to fetch data. Right now I have this living in `componentDidMount`

```js
  componentDidMount: function() {
     this.actions.fetch(this.props.params.id);
  }
```

This works great.  However, if I navigate from '/' to '/something/:id' or in reverse it doesn't work. I realize that the componentDidMount is not called since it already is mounted. I have to do a hard refresh for the page to properly refresh.

What is the best practice to handle this in the lifecycle?

Thank you.

**Comment by ryanflorence** [comment]
Using the same handler for two routes is usually not a good idea, you end up branching a bunch. Share some code with a mixin.

~But~ if you insist. The hook you're looking for is `componentWillReceiveProps`, because it stays mounted, you won't get `componentDidMount` on that transition (you'll still need `componentDidMount`, too).
