### ISSUE TITLE
passing props with transitionTo

### ISSUE THREAD

**Issue by trungpham** [rackt/react-router#797]
Is it possible to set the props when calling transitionTo? This way my component does not have to special case between normal rendering with props vs. using getParams() with react-router.

Thanks.

**Comment by colinmegill** [comment]
+1 - I was like, good lord this component is not complicated enough for {...this.props} to have mysteriously stopped working

**Comment by Schniz** [comment]
:+1:

**Comment by gaearon** [comment]
>This way my component does not have to special case between normal rendering with props vs. using getParams() 

Sounds like an anti-pattern. Why not have a component that uses props and a separate route handler that passes params to it? Something like `<Component {...this.getParams()} />`.

Yeah two components is more verbose but then you don't need to complicate the router and get nice clean separation of route handler and the actual component. This wouldn't work well anyway: what if your component has `to` prop? It would be impossible to specify from `Link`. If we go for `<Link props={{ prop: something }}>`, what if you specify some prop that is *already* specified by the parent route handler with `<RouteHandler prop={somethingElse}>`? Who wins? When edge cases break so easily, it's a good indication that design isn't solid. Since there's a very simple workaround, I'm closing this, but please let me know if I missed something!
