### ISSUE TITLE
Calling component's static methods from Router.run() callback

### ISSUE THREAD

**Issue by knivets** [rackt/react-router#813]
So I'm trying to call a static method from a callback, but it says that there is no such method:

```
Router.run(routes, (Handler, state) => {
   var data = Handler.staticMethod(); // Handler should be my component, right?
                                      // But .prototype shows that it is Route. Why?
    React.render(<Handler data={data}/>, document.getElementById('main'));
});
```

I've seen async-data example, but I need to do extra step of filtering through `state.routes` to find my route handler. And when I find it, `Handler == state.routes[my-route-index].handler` returns `false`, why? It seems to be the same thing.

**Comment by taurose** [comment]
Unless you don't nest routes, your routes are always matched to multiple handlers; that's why `state.routes` is an array and you need to filter through it if you want to get a specific handler component. 
You can use `state.routes[0].handler` to get the topmost handler, or `state.routes[state.routes.length - 1].handler` for the innermost one.
I'm not sure which one you'd expect to be `Handler`, but currently `Handler` is actually the same as the return value from `Router.run` and `Router.create`. I think this isn't official API though, and you should only be concerned with using `Handler` for rendering your matched list of router handlers.

**Comment by knivets** [comment]
OK, I see. Thanks for the explanation!

**Comment by kimmobrunfeldt** [comment]
Now I know I can access the static methods with:

    state.routes[state.routes.length - 1].handler.staticMethod()

Is there a way to access staticMethods to the Handler passed for **Router.run** callback?

**Comment by knivets** [comment]
@kimmobrunfeldt from what I've understood, `Handler` is a `Route` instance and not a react component. Also multiple routes (hierarchy) are almost always matched (e.g. root and child handlers), that's why you need to filter them first.

**Comment by kimmobrunfeldt** [comment]
Ah I see. In my case, I only need to get reference to the innermost handler, but I understand that might vary between use cases

**Comment by gaearon** [comment]
Seems solved so closing. Let us know if you have further comments!
