### ISSUE TITLE
Bring back dist on NPM

### ISSUE THREAD

**Issue by jbraithwaite** [rackt/react-router#839]
This was a breaking change from 0.11 to 0.12.

Can you please bring back the compiled assets (`dist/react-router.js` and `react-router.min.js`) when installing from NPM?

**Comment by mjackson** [comment]
@jbraithwaite I guess I just figured that everyone installing react-router via npm was using CommonJS to require the router. `dist` was only ever for people using the global build.

**Comment by jbraithwaite** [comment]
My use case: I'm building an isomorphic app and use CommonJS on the server and for the client, using the files in `dist`, I build a minified version of my plugins (React, React Router, etc) to a separate file.

**Comment by gaearon** [comment]
>using the files in dist, I build a minified version of my plugins (React, React Router, etc) to a separate file.

What build tool do you use? You can use CommonJS on client with Webpack or Browserify and let them uglify your dependencies.

**Comment by Dashed** [comment]
Ugh. I hate dist files on npm. Just publish to bower, and make people who want compiled builds to use that channel.

**Comment by mjackson** [comment]
@jbraithwaite You can get a much more compact build by letting Browserify/Webpack resolve your `require`s. If you're using both the global build of React and ReactRouter, you're loading duplicate code on the client.

Or, if you really want the global build, we already publish it to bower, so you can use that channel if you'd like. But I'd prefer to keep our global build out of npm, since it's specifically for CommonJS code.

**Comment by jbraithwaite** [comment]
@gaearon, I'm using Webpack with React Router listed in `externals `, so there is no duplicate code.

@mjackson Why not provide more options to developers instead of taking them away? Facebook also expects you to use React via CommonJS but include the compiled / uglified assets in a `dist` folder on NPM.

I'm building a boilerplate for [React + React Router](https://github.com/jbraithwaite/react-boilerplate/) apps and I'm trying to keep it as lean / unopinionated  as possible. It would be ideal to not require Bower.

**Comment by Dashed** [comment]
@jbraithwaite I glanced a bit at the gulpfile. Here's my thoughts.

`webpack externals + gulp minify step = webpack code splitting`

See: http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code

If you keep to using npm/commonjs versions of the libraries, you can have webpack organize vendor libraries in a separate js file. 

This is better than externals, because you have extra UMD (https://github.com/umdjs/umd) boilerplate code that each library have in their build files. The minify step cannot remove this.

**Comment by gaearon** [comment]
Using React as an external causes problems. There are (admittedly, not very common, but still valid) cases when you *need* to reach out into some internal React module. This is trivial with CommonJS. By making React an external in production, you're taking away the developer's freedom to do what Webpack already offers by supporting CommonJS. As @Dashed notes, the right solution is to use code splitting.

**Comment by mjackson** [comment]
> I'm using Webpack with React Router listed in externals, so there is no duplicate code.

@jbraithwaite The router requires certain core React modules that are also required by React itself. If you use the standalone build of the router + the standalone build of React you'll get duplicate copies of the modules that both of them depend on.

**Comment by gaearon** [comment]
Also, putting everything into some kind of `vendor.js` is overrated IMO. You can't start your app without those deps, and it's healthy to update deps at least once a month so there's no real long term caching benefit.

**Comment by jbraithwaite** [comment]
I truly appreciate the time put into all of your responses. I'll tweak my code to use `webpack code splitting`

**Comment by jbraithwaite** [comment]
I implemented `webpack code splitting`, it now takes 14 seconds to compile & uglify my application vs. 670 ms before. The file size for my `external.min.js` did reduce from 197 KB to 194 KB.

**Comment by Dashed** [comment]
That's pretty long. Are you sure you didn't forget to put `exclude: /node_modules/,` in your loaders?

**Comment by jbraithwaite** [comment]
@Dashed, still have the long compile times (~16 seconds) https://gist.github.com/jbraithwaite/4099acf911062fd9ec22#file-gulpfile-js-L99

**Comment by gaearon** [comment]
Do you do production builds often? If you do, you might want to use incremental builds by adding `watch: true` to config. First build will still be slower, but subsequent ones will take ~2 seconds.

On a side note, you should use 

```js
        new webpack.DefinePlugin({
          'process.env': {
            'NODE_ENV': JSON.stringify('production')
          }
        }),
```

for production builds so Uglify compiles React in production mode.

**Comment by toddlucas** [comment]
I'm late to this thread but I'd like to second the request of @jbraithwaite. Not everyone follows the same conventions. This is a fast moving space, with multiple approaches to building, minifying, packaging, modularizing, etc. The react NPM package itself contains dist builds. I also use Browserify, but I like to keep vendor libraries external, to the degree possible. This allows browser caching the things that don't change as frequently and helps me keep my app build small, since that is what changes most often. Thanks.

**Comment by pedrodelgallego** [comment]
+1
