### ISSUE TITLE
Animation w/ Dynamic Segments

### ISSUE THREAD

**Issue by atwoodjw** [rackt/react-router#846]
According to the [documentation](https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#important-note-about-dynamic-segments), when using Dynamic Segments, a transition from /users/123 to /users/456 does not call getInitialState, componentWillMount, componentWillUnmount or componentDidMount. Instead, you need to implement componentWillReceiveProps.

So how do you use TransitionGroup's to animate the transition? For example, I'd like to use the fade effect from the animations demo, but with the master/child demo... perhaps sliding in the selected Contact component rather than simply updating it. I'm not quite sure how to go about this.

**Comment by TheSavior** [comment]
Perhaps if you use a key on the Handler of the id, then it will mount a second node and let you use a TransitionGroup. Try taking a look at the animation example: https://github.com/rackt/react-router/blob/master/examples/animations/app.js

**Comment by johanneslumpe** [comment]
You could have a wrapper component, which uses a `ReactCSSTransitionGroup` to display the `RouteHandler`. Instead of the route name, you'd then apply the dynamic segment as key.
```javascript
// We assume that we have all the required variables
// in scope here
var Handler = React.createClass({

  mixins: [Router.State],

  render: function() {
    var name = this.getParams().id;
    return (
      <div>
        <ReactCSSTransitionGroup transitionName="some-transition">
          <RouteHandler key={name} />
        </ReactCSSTransitionGroup>
      </div>
    );
  }
});
```

This way, whenever the dynamic segment changes, you will get an animation from the old to the new segment. Of course you could also compare the segment with some internal state in `componentWillReceiveProps`, then set a new state if the segment changed and only refer to `this.state` in your render function. The key here (pun intended) is to use the dynamic segment as `key` for your transition group child.

**Comment by johanneslumpe** [comment]
Argh, didn't see that there was an answer already, somehow it didn't show up until I posted this.

**Comment by TheSavior** [comment]
:+1:

**Comment by ryanflorence** [comment]
yep, use a key
