### ISSUE TITLE
How to break up the routes for multiple entry points?

### ISSUE THREAD

**Issue by volkanunsal** [rackt/react-router#850]
I just realized that I cannot require a webpack entry point from the router. I'm curious how I should design my routes in a React + Webpack app where there are several entrypoints. Otherwise, the routes package is a default catchall , and I assume wouldn't let me modularize my assets.

**Comment by taurose** [comment]
Strictly speaking, you don't want to break up your route definitions since they are needed to generate links, among others. What you  probably want to do is split up your route handlers. Follow #755 for this (there's also a [working solution](https://gist.github.com/gaearon/fbd581089255cd529e62)).

From there, if you wanted, you could create multiple entry points using webpack in order to save the http request for the first handler at the cost of less caching.
