### ISSUE TITLE
How to provide Routes with data from Flux Stores? Multiple Controller-Views?

### ISSUE THREAD

**Issue by TheSavior** [rackt/react-router#851]
I'm trying to figure out how to give my Route the data it needs to render itself from the Flux Stores it cares about.

Imagine you have the following routes:

```jsx
<Route name='root' path='/' handler={App}>
  <Route name='post' path='/post/:postId' handler={Post} />
  <DefaultRoute name='intro' handler={Intro} />
</Route>
```

And `App` is a Controller-View listening to PostStore and has a render function that is:
```jsx
return (
  <div className="container">
    <PostList posts={this.state.posts} />
    <RouteHandler/>
  </div>
);
```

The `Post` handler will be able to get the postId by using `this.getParams().postId`, but how will it get the details to render the actual post?

It seems like it either needs to be passed the full object it needs to render as a prop, or be a Controller View itself and also listen to the store and look up the details of the post. 

The nested Controller-View option seems more correct since the `DefaultRoute` (`Intro`) doesn't need to know anything about the list of posts. However, it would mean that when the `PostStore` updates, it would cause `Post.render` to be called twice and thus causing the issues that are stated in the Flux documentation.

http://facebook.github.io/flux/docs/overview.html#views-and-controller-views
>Be aware, however, that controller-views deeper in the hierarchy can violate the singular flow of data by introducing a new, potentially conflicting entry point for the data flow. In making the decision of whether to add a deep controller-view, balance the gain of simpler components against the complexity of multiple data updates flowing into the hierarchy at different points. These multiple data updates can lead to odd effects, with React's render method getting invoked repeatedly by updates from different controller-views, potentially increasing the difficulty of debugging.

What is the right approach here?

In the react-router-async-props example by @ryanflorence it looks like he goes the approach of multiple Controller-Views.

**Comment by TheSavior** [comment]
I guess `Post` could just request the data from the store, but not actually listen for changes to the Store. That would mean that the component would only render once but it would need to guarantee that it was only ever rendered underneath a component that WAS listening to PostStore. 

That seems like it would make the component fragile and non-reusable though.

**Comment by mark-bradshaw** [comment]
@TheSavior 

FYI, I'm a complete newbie to react router, so...

I just ran into this issue too.  I didn't want to hard code data load for all the various route permutations.  My preference is to have data requirements driven from the react components themselves.  Doing this keeps my data needs right with the component, and avoids having to have a big fragile setup that duplicates all the routing.  Each component knows what data it needs, and nowhere else in code is that knowledge needed.  It has the side benefit of making my server side code not need to have any special knowledge of the app.  It gets me closer to 100% isomorphic.

Basically my approach looks like this:

```
// ES6 syntax
let flux = new Flux();
Router.run(routes, request.path, (Handler, state) => {
    prepopulateData(flux, state, () => {
        let markup = '';
	React.withContext({flux}, () => markup = React.renderToStaticMarkup(<Handler />));
       // ... serialize data then push markup and data into a reply from the server
    });
```

prepopulateData is a function like this:

```
import Async from 'async';

export default (flux, state, callback) => {
	Async.each(state.routes, (route, aECallback) => {
		if (!route.handler.prototype.prepopulateData) {
			return aECallback();
		}

		route.handler.prototype.prepopulateData(flux, state, aECallback);
	}, (err) => {
		callback();
	});
}
```

The idea is to go through the list of handlers/components that will be active for this request (which react router tells me), and give them each a chance to prepopulate the data they need.  This only happens on the server.  The client side will have this data serialized for its own benefit.

Each route.handler is a react component object, so for each one that has particular data needs I add a function called prepopulateData to the component.  If the component has that function, the function will be called.  When the function determines that it has the data loaded it needs it calls back to the main prepopulateData method.  The callback doesn't return the data in my implementation, because that is kept in my flux store.  It just signifies that it's ready to go.  

How the component prepopulates data is up to it.  Implementation details don't matter on the big picture.  I'm using a flux architecture, so basically this fires off flux actions that end up loading the required data.  I listen to the stores and when I see they have my data I callback and let the rendering proceed.  When all components have signaled that they are ready then I get passed back up to the top Router.run method for rendering.

I don't know if this is a good idea or not, but it seems appropriate and gives me a way to have each component separate handle data loading and signaling readiness without having some big switch statement somewhere that basically duplicates the router.

**Comment by TheSavior** [comment]
@mark-bradshaw I really appreciate the time you put into responding to my question. It's great to see that kind of response in this community. We are all trying to figure out the best ways to do things. :)

You definitely have some ideas in there that I need to explore.

I'm concerned about async routing. I've seen these examples in a couple of different places and I haven't been able to get on board with it. It seems like we shouldn't be waiting to get the data before navigating to the new page. 

I figure the new page and it's sub components should handle what to do while they don't have data. This would give faster perceived performance. Also, if you have like a .3 second animated transition between pages, if you transition before your data is loaded, you are pretty much giving the code a free .3 seconds to hear back from the server or whatever it needs.

**Comment by mark-bradshaw** [comment]
@TheSavior I'll just clarify that the async stuff is only done on server side, for the initial isomorphic render.  Once that's all delivered client side I stop all such shenanigans.  

I think maybe I misunderstood your question.  I thought you were looking for ideas on how to get all the data loaded before the server did a render.  That's what I was working through and I read your question wrong.  It seems you are talking about client side data fetch, and getting things correctly.

I agree that you wouldn't want a delay in moving on client side.  What I'm doing is when a transition is needed, say a user clicks a button, I ask react router to transition to the new location and simultaneously kick off a flux action that corresponds to what the button is asking for.  RR puts all the components in place that I need on the page, and simultaneously the action hits the right store(s) and starts the data load.  When the stores get the data it then filters back down to the components listening to the store.

With a fast api it's basically imperceptible.  I'm thinking I'll need to eventually deal with what happens if I transition to a new section of my app, but the data never arrives.  I think I'll need to catch the error and set an error message in a UI store that can be used to display that error.

Sorry for the rabbit trail earlier.  Hopefully I didn't derail anyone.

**Comment by TheSavior** [comment]
@mark-bradshaw Heh, yeah. I'm just talking about client side stuff for now. 

I guess my concern is specifically with having multiple components at different levels having to listen to stores and re-render with that data. That would cause components to potentially be re-rendered multiple times for a single store changing (bad). However, it seems like I'm seeing more and more examples and recommendations by people at Facebook that have multiple nested Controller-Views (components listening to stores). @fisherwebdev, do you have any thoughts on this?

**Comment by nichoth** [comment]
Also trying to figure out best practice for fetching data for a route. I see two algorithms: 

You can fetch data in the `Router.run` callback, pausing the transition until async request completes. This is like [the example in the Router.run API docs](https://github.com/rackt/react-router/blob/master/docs/api/run.md#examples-1). Also similar to @mark-bradshaw 's example, putting a static function in the React component.

Or you can render the component straight away, and also start an async request. The component would listen to a store, and the async request would create an action when it completes. Check out the [thread actions](https://github.com/ianobermiller/nuclearmail/blob/master/src/js/ThreadActions.js#L53) in the [nuclear mail](https://github.com/ianobermiller/nuclearmail) app:

```js
function archive(threadID: string) {
  Dispatcher.dispatch({
    type: ActionType.Thread.ARCHIVE_STARTED,
    threadID,
  });

  // dispatch an action when the request completes. This could go in the Router.run CB.
  ThreadAPI.archive({threadID}).then(() =>
    Dispatcher.dispatch({
      type: ActionType.Thread.ARCHIVE_COMPLETED,
      threadID,
    })
  ).catch(error =>
    Dispatcher.dispatch({
      type: ActionType.Thread.ARCHIVE_FAILED,
      threadID,
      error,
    })
  );
}
```

The component would need to start listening to the store in a hook. This would go in a controller (top-level component):

```js
// component.js
getInitialState: function() {
  return {};
},
componentWillMount: function() {
  // call setState in case our data has already loaded
  this.setState( {someState: MyStore.getState()} );
  MyStore.addChangeListener(this._onStoreChange);
}
```

The store then triggers a change event when the `ARCHIVE_COMPLETE` action is dispatched.

I haven't found a need for multiple controller-views within one component hierarchy. In the original example, if we pass all data as props, then `PostList` would get a prop like:

```js
[
  {id: 1, title: "post title"},
  {id: 2, title: "another post title"},
  {id: 3, title: "title 3", details: { /* ... */ },
]
```

And your sub-views would need more logic to know how to render things. **Re-rendering the entire hierarchy from the controller view is ok because of React's diff'ing algorithm**? 

Async data flow is something I would like to refine more in the React + Flux pattern. This discussion makes it clear that there is still a good cognitive load & lack of convention. 

Thoughts on this?

**Comment by jingc** [comment]
I'm not too familiar with react-router, so apologies if I misunderstood anything here. It seems like the main question is something like "How do we avoid rendering a component twice if both the component and its parent listen for updates from the store?" Is that accurate?

If so, we typically use ReactUpdates with Dispatcher to make sure there's one render in a single dispatch round: https://github.com/facebook/react/blob/master/src/core/ReactUpdates.js

This typically looks like:

    ReactUpdates.batchedUpdates(() => {
      // dispatch action
    });

Then I believe updates within the dispatch all get batched to the end. Parent components will render first, so child components won't get rendered more than once. @fisherwebdev may also be able to confirm.

**Comment by TheSavior** [comment]
@jingc, Thanks for that. Very interesting. That does explain away some of my concern. This is being done by default in the core? Or something developers need to do manually? I see from Pete Hunt's RAF example that users can manually change the strategy, what happens by default?

And if this is done by default, can you elaborate more on the warning message in the React Docs: http://facebook.github.io/flux/docs/overview.html#views-and-controller-views

> Be aware, however, that controller-views deeper in the hierarchy can violate the singular flow of data by introducing a new, potentially conflicting entry point for the data flow. In making the decision of whether to add a deep controller-view, balance the gain of simpler components against the complexity of multiple data updates flowing into the hierarchy at different points. These multiple data updates can lead to odd effects, with React's render method getting invoked repeatedly by updates from different controller-views, potentially increasing the difficulty of debugging.

**Comment by jingc** [comment]
I believe developers have to do this manually by calling ReactUpdates.batchedUpdates around a dispatch, to tell ReactUpdates where to start and stop the batch.

As for the Flux docs - ReactUpdates makes this case more performant by not rendering the same component multiple times for the same pass, but that case can still be confusing and make the app more difficult to debug.

**Comment by ryanflorence** [comment]
don't mean to be a party pooper, but the `Router.run` API allows us to put data loading in your hands, you can see my opinion on the matter with https://github.com/ryanflorence/react-router-async-props

I'm closing the issue, but feel free to keep talking though.
