### ISSUE TITLE
Silent transitionTo? i.e. just change the URL but don't trigger Router

### ISSUE THREAD

**Issue by topmindinc** [rackt/react-router#871]
Is there a way to change the URL without triggering the Router? E.g. similar to how Backbone.js's navigation  can define an option not to change the URL without trigger its router http://backbonejs.org/#Router-navigate. Thanks!

**Comment by gaearon** [comment]
Not really, as it would put router in an inconsistent state.

You should be able to call `router.stop()` and then call `pushState` or change `location.hash` without having router re-render: but in this case router won't be running at all.

If you *really* want to have more control over this you can supply router a custom `location` object that behaves as you'd like. Since this is possible, I'm closing, but let me know if I missed something.

**Comment by topmindinc** [comment]
Okay, thanks for the feedback.

**Comment by Fyre91** [comment]
Did you find out a solution @tzheng11 ?
