### ISSUE TITLE
Remove RouteHandlerMixin

### ISSUE THREAD

**Issue by mjackson** [rackt/react-router#872]
With the move to using ES6 classes for all our components, we can no longer use the `RouteHandlerMixin`, so we need to get rid of it and put its functionality back into the `RouteHandler` component.

@natew This is probably going to mess with some stuff you're doing. A few workarounds I can see right now are:

- Can you subclass `RouteHandler` instead of using the mixin?
- Maybe we could just provide a bag of methods you could manually assign to one of your component's prototypes?

Any other ideas?

**Comment by ryanflorence** [comment]
how'm I gonna do this then? https://github.com/ryanflorence/react-router-async-props/blob/master/modules/index.js#L41-L64

**Comment by mjackson** [comment]
@ryanflorence subclass `RouteHandler` ... ?

Maybe we need a different way to think about this.

**Comment by johanneslumpe** [comment]
@mjackson why do you *have* to get rid of the mixin? As you suggested to @natew in your 2nd bullet point - wouldn't that be kind of the same thing as a mixin? I had a talk with @ryanflorence about this one or two days ago.

Wouldn't this work without issues:

```javascript
import {RouteHandlerMixin} from 'react-router';

class Something extends mixin(React.Component, RouteHandlerMixin) {
/* ... */
}
```

Or even more clear:

```javascript
import {RouteHandlerMixin} from 'react-router';

class Something extends React.Component {
/* ... */
}

mixin(Something.prototype, RouteHandlerMixin);
```

To me, the 2nd example looks clearer.

**Comment by natew** [comment]
Yea, there's a post in react-future somewhere that shows those two ways of doing mixins now. Also, in 0.13 you can use mixins no problem, so maybe we should wait until 0.14, there may be more clear ideas on how to replace them by then?

**Comment by johanneslumpe** [comment]
I think we should provide both. Since for now, as @natew said, mixins are still no issue. They even stated, I quote:
> The classic React.createClass style of creating classes will continue to work just fine.
And that was not limited in any way like "until 0.14 comes out". By providing both a new solution could be worked on, but the mixins could be kept for backwards compatibility. As long as react supports them keeping the mixins in addition to a new, recommened way of doing things, will be an advantage I think.

**Comment by taurose** [comment]
Maybe we can remove RouteHandler altogether? I think that with the 0.13 changes to refs and cloning we could replace most of RouteHandler's functionality by passing `ref: router.setRouterComponentAtDepth.bind(router, depth)` from the router directly.
We could change the API to

```js
// currently
<RouteHandler />
<RouteHandler myProp=".." />

// changed
{this.props.children}
{React.cloneElement(this.props.children, { myProp: ".." })}
```

Note that unlike `cloneWithProps`, `cloneElement` will apparently be part of the standard API, and it will not throw away our ref, unless ref is overwritten. Referencing a child handler is currently not really well supported either though.

Also, I feel like passing props to child handlers is mostly used to pass some kind of context to all route handlers, since we don't provide an easy way to inspect child routes. Perhaps this could better be covered by some form of context object bound to the router and passed as props or react context? Could be the same as the transition context (#590).

**Comment by ryanflorence** [comment]
higher order component, and then wrap a component `createRouteHandler(Component)`

**Comment by owais** [comment]
Won't removing the mixin make stuff like this impossible to do? http://stackoverflow.com/questions/27864720/react-router-pass-props-to-handler-component/28180620#28180620

**Comment by owais** [comment]
@ryanflorence I was just getting started with react-router. I need RouteHandlerMixin to pull off something like this, 
```
var Index = React.createClass({
      mixins: [RouteHandler],
      render: function () {
        var handler = this.getRouteHandler({ myProp: 'value'});
        return (
            <div>
                <header>Some header</header>
                {handler}
           </div>
        );
  }
});
```

Now that it is gone, is there an alternative?

**Comment by gaearon** [comment]
In 1.0 (the upcoming release with breaking changes) there won't be the need for handlers. You'll just get regular `this.props.children`, which you can clone to pass additional props if you'd like.

**Comment by owais** [comment]
@gaearon Cool! Any preferred way to install beta/dev version or should I just fetch the latest master. The thing I'm building is not supposed to be prod ready for quite some time so I could easily use dev version.

**Comment by gaearon** [comment]
@owais The work is in `next` branch but you'd need to compile `src` yourself to build against it. Also, it's not documented yet so I'd wait out a bit. It's going to be released in a week or two.

**Comment by owais** [comment]
Got it. I suppose 1.0 will let me choose the props I want to pass to child RouteHandler depending on the active route? More details here. https://github.com/rackt/react-router/issues/1175

Thanks a lot for clearing things up @gaearon I'll give it a shot next weekend

**Comment by mjackson** [comment]
This is gonna be gone in 1.0 in favor of just using `this.props.children`. Closing.
