### ISSUE TITLE
passing state passes it to all Handlers

### ISSUE THREAD

**Issue by thomasmattheussen** [rackt/react-router#873]
I went from this
```
render: function() {
        return (
            <div className="wrapper">
                <Header />
                <Pages>
                    <Page active pageId="newmessage">
                        <MessagePost />
                    </Page>
                    <Page pageId="allmessages">
                        <Feed messages={this.state.messages} />
                    </Page>
                    <Page pageId="searchmessages">
                        <MessageSearch />
                    </Page>
                </Pages>
            </div>
        );
    }
```

to this (now using react-router)
```
render: function() {
        return (
            <div className="wrapper">
                <Header />
                <Pages>
                    <Page>
                        <RouteHandler {...this.state} />
                    </Page>
                </Pages>
            </div>
        );
    }
```

I read that passing state should supposedly be done this way...

A question I started asking myself was that I now transfer the state to ALL pages instead of just to  <Feed>. Wouldn't that be considered some sort of violation against separation principles? Since <MessagePost> and <MessageSearch> have no business with this.state.messages, they probably also shouldn't know about it?

Or am I talking gibberish here? :)

**Comment by taurose** [comment]
> `<RouteHandler {...this.state} />`

This doesn't make much sense in my opinion. You've probably seen this:

```js
router.run(function(Handler, state){
  React.render(<Handler {...state} />, document.body);
});
```

Here, we're simply passing the current router state object as props to the top level route handler. It's not much different from writing `<Handler routeState={state} />`, except that you can simply write `this.props.params` instead of `this.props.routeState.params` to get the current params inside the handler.

You can then pass on that state to lower level router handlers using `<RouteHandler {...this.props} >` or `<RouteHandler routeState={this.props.routeState} />`.

As an alternative to passing the route state as props, you can also use the State mixin (soon to be deprecated, but its replacement will work the same way).

I think it's best practice to limit that router state to your route handlers though, i.e. don't write `<PageTitle routeState={routeState} />`, but only give it the information it really needs, e.g. `<PageTitle title={somehowGetTitleFromState(this.props.routeState)} />`. That way, you can better reuse your components that aren't route handlers, and you'd mainly need to rewrite your route handlers if you ever wanted to switch routers.

**Comment by ryanflorence** [comment]
Closing this since its just an app design question, but happy to keep discussing.

@thomasmattheussen if feed is the only view that cares about the messages, why does it not own that state?

**Comment by thomasmattheussen** [comment]
Hmm, good question.

I think I made that decision because I am using feed somewhere else in the app in a slightly different context, so I wanted to make Feed as simple as possible: just a component that displays messages in a list.

A little more in depth:

I am using Feed as a list of all messages in my app. 
But I am also using a Feed component beneath a search-input.
Both display a list of messages, but the first one gets updated whenever a new message is posted, the latter displays all messages based on a search-query. 

So that's why in my point of view the logic for both lives one level higher.

Does that make sense? :)
