### ISSUE TITLE
Create transition from componentDidMount

### ISSUE THREAD

**Issue by gregeinfrank** [rackt/react-router#876]
I'm pulling data from the server in componentDidMount, and when that fails I want to redirect to "/login". Since I don't have a `transition` object at this time (since I'm in `componentDidMount` and not `willTransitionTo`) is there a way to create a transition to "/login" so that when "/login" finishes, it can do a transition.retry() to go back to the last transition?

Thanks

**Comment by gaearon** [comment]
You can either pull data in `willTransitionTo` or you can probably save transition object somewhere (in a static property on component?) and use it in `componentDidMount`.

Am I missing something?

**Comment by gregeinfrank** [comment]
@gaearon I don't think I can pull data on `willTransitionTo` since I need to set the response data on the state, which I don't believe is available yet when `willTransitionTo` is called (is that not correct?)

Your second suggestion *could* work, but doesn't seem like the most elegant solution

**Comment by gaearon** [comment]
>since I need to set the response data on the state, which I don't believe is available yet 

You can lift the state out of the component in something like Flux store, and have component subscribe to it. In this case it won't matter whether component is available or not.

**Comment by taurose** [comment]
> or you can probably save transition object somewhere (in a static property on component?) and use it in componentDidMount.

I don't think that will work for two reasons:

1. transition aborts are only handled by the router after the transition hooks are finished and before run callback is called. Only retry works after that
2. causing a transition and thus a rerender from within react render hooks is bad

In my opinion the router is a bit lacking in this situation. Making willTransitionTo work would be the best solution. A (not so elegant) workaround that should work would be to pass a `redirectAfterRender` prop callback from your run callback down the hierarchy, and then manually call `router.replaceWith(..)` for the redirect after the initial render is done. You'd need to be careful about what to render before the redirect though, since the user may see it if you're triggering any async transition hooks.

**Comment by gaearon** [comment]
>transition aborts are only handled by the router after the transition hooks are finished and before run callback is called. Only retry works after that

I thought `retry` is what @gregeinfrank is after:

>so that when "/login" finishes, it can do a transition.retry() to go back to the last transition?

**Comment by taurose** [comment]
Sorry about that :smile:

If I'm finally understanding this right, there are actually two problems:

1. Transitioning to `/login` if some data fetching within `componentDidMount` fails
2. Transitioning from `/login` to the previous route after logging in

Have you looked at the auth-flow example? It does exactly that, except the part where you want to transition from `componentDidMount` instead of `willTransitionTo`. I'd also suggest trying to make it work like that, since you can't abort an ongoing react render call, and you won't be able to use `componentDidMount` server-side.

**Comment by gregeinfrank** [comment]
@taurose I think you understand the problem correctly, however how can I load data in `willTransitionTo` without being able to set a state from within `willTransitionTo`?

**Comment by ryanflorence** [comment]
you can transition to absolute paths, so just save off the path, our auth flow example doesn't use `transition.retry` anymore (I think we all kinda want to get rid of that). We put the path to return to in the query:

`https://github.com/rackt/react-router/blob/master/examples/auth-flow/app.js#L51-L55`

**Comment by ryanflorence** [comment]
I forgot to finish my thought: so instead of getting the path from `transition.path` you can get it from `this.context.router.getCurrentPath()` and intsead of `transition.redirect` you use `router.replaceWith` same signature.
