### ISSUE TITLE
Router breaks when using the NPM build of React Router

### ISSUE THREAD

**Issue by eriklharper** [rackt/react-router#903]
See my original Stack Overflow on this issue: http://stackoverflow.com/questions/28818286/react-router-typeerror-oldelement-store-is-undefined/28841423#28841423

Not sure if this is something to do with my specific setup, but I thought I would draw your attention to this, if it helps anybody else.  Thanks for the excellent work on this!

**Comment by gaearon** [comment]
Any chance you had a duplicate `react` installed in `node_modules/react-router/node_modules/react`? Two Reacts on a page would conflict.

**Comment by jmodjeski** [comment]
It is a duplicate `react` issue.  I'm not sure what is actually at fault, but I'm getting one `React.js` and a second `react.js` loaded in the browser.  Browserify doesn't seem to want to shim the `require('react')` inside of react-router.

**Comment by eriklharper** [comment]
Actually, I did not have a duplicate react installed in `react-router` or any other NPM dependency, I just checked.

Here's what my npm-installed react-router looks like in my project: 
![image](https://cloud.githubusercontent.com/assets/821864/6488451/87b44ef8-c24c-11e4-95c0-fcc0b5d94abc.png)

**Comment by gaearon** [comment]
Can you share your project, or at least the failing part so we can repro?

**Comment by tjwebb** [comment]
fwiw, I'm using react-router with npm + browserify without issue.

**Comment by jmodjeski** [comment]
Bottom line, don't mix your package managers.  In my case it was a combination of using bower to load a global react, and browserify-shim to supply the require result from the global.  I just bit the bullet and only use npm and browserify, and skip over the bower step.

The root issue was my browserify output was as large as 4MB before uglify.  Which is why I was trying to use the global React and ReactRouter.

**Comment by ryanflorence** [comment]
4MB?!

Out of curiosity, what does your package.json "dependencies" entry look like?
