### ISSUE TITLE
documentation: auth flow example for react 0.13 without mixins

### ISSUE THREAD

**Issue by fczuardi** [rackt/react-router#913]
I am trying to create a component that shows only for authenticated users, the example in https://github.com/rackt/react-router/blob/0.13-compat/examples/auth-flow/app.js uses a mixin that adds a willTransitionTo to the "statics" attribute of a component, and I think it would be automatically be called whenever that component is passed as the ```<Handler/>``` in a route callback...

I have tried to create such a "willTransitionTo" function manually, without the use of React.CreateClass or mixins on the:

- root component (app) and in the handler component (dashboard)
   - inside the constructor() as this.willTransitionTo
   - inside the constructor() as this.statics.willTransitionTo
   - inside the constructor() as this.context.willTransitionTo
   - as a willTransitionTo() method
   - as a statics() method that returns an object containing a willTransitionTo method

The code inside the function never gets to run just by entering the # url manually. Is this the expected behavior? How would an auth example without mixins look like?

**Comment by taurose** [comment]
If I understand you correctly, you're asking how to setup the hooks for ES6 components? I think it should work like this:

```js
class MyRouteHandler extends React.Component {
  render() {
    ..
  }
}

MyRouteHandler.willTransitionTo = function (transition, params, query) {..};
MyRouteHandler.willTransitionFrom = function (transition, component) {..};
```

**Comment by fczuardi** [comment]
yes @taurose !! that seem to work, thanks :)

**Comment by fczuardi** [comment]
Another detail regarding this auth flow example, for the Login element, to use it without the State mixin, you have to do:

    MyRouteHandler.contextTypes = {
        router: React.PropTypes.func
    }

And instead of using **this.getQuery()** use **this.context.router.getCurrentQuery()**

**Comment by ryanflorence** [comment]
thanks for the push to do this, hope it helps :)

**Comment by lemonCMS** [comment]
I tryed this, but it didn't work for me. Ig have an Login.js component

    class Login extends React.Component {
        render() { ... }
    }

    Login.willTransitionTo = function (transition, params, query) {
        console.log('willTransitionTo');
    };

    module.exports = Marty.createContainer(Login, {});

As you can see i am using martyjs, perhaps that is the problem?

**Comment by handleunavailable** [comment]
@lemonCMS if you're using MartyJS you can do something like this : 
```
class Login extends React.Component {
    render() { ... }
}

MartyContainer = Marty.createContainer(Login, {});

MartyContainer.willTransitionTo = function (transition, params, query) {
    stuff();
};

module.exports =  MartyContainer;
```
It's less than ideal. But it works.

**Comment by lemonCMS** [comment]
@handleunavailable  thx.

The issue was also reported at martjs and they came with an other solution that also works.
I post it here for future reference.

    class Login extends React.Component {

      static willTransitionTo(transition,params,query,callback) {
      }
      render() { ... }
    }

    module.exports = Marty.createContainer(Login, {
     statics: {
        willTransitionTo: Login.willTransitionTo
      },

      fetch: { ...  },
      pending() { ...  },
      failed(errors) { ...  }
    })

**Comment by praveen-ti** [comment]
I have a react component like this;

export default class Customsurvey extends React.Component {
// body
}
and I added ES6 hook for that component like;
Customsurvey.willTransitionTo = function (transition, params, query) {
  if(!AuthStore.getState().isLoggedIn) {
      transition.redirect('/login');
  }
};

It is working fine for me when AuthStore.getState().isLoggedIn has false value (not logged in).
The problem is when isLoggedIn is to set to true (logged in now), and if I refresh the same page then I got errors like this;

Unhandled aborted transition! Reason: [object Object]

Any idea what cause this issue?

**Comment by praveen-ti** [comment]
I have a react component like this;

export default class Customsurvey extends React.Component {
// body
}

and I added ES6 hook for that component like;

Customsurvey.willTransitionTo = function (transition, params, query) {
  if(!AuthStore.getState().isLoggedIn) {
      transition.redirect('/login');
  }
};

It is working fine for me when AuthStore.getState().isLoggedIn has false value (not logged in).
The problem is when isLoggedIn is to set to true (logged in now), and if I refresh the same page then I got errors like this;

Unhandled aborted transition! Reason: [object Object]

Any idea what cause this issue?
