### ISSUE TITLE
Multiple route definitions in an app

### ISSUE THREAD

**Issue by jdlehman** [rackt/react-router#921]
Is it possible to define multiple route definitions in an application?  Essentially I have multiple components that I want to individually react to a route change.  For example, both my `Header` and `Footer` components need to individually change based on the route.  The main content does not change.  (It may sound weird, but think of my header and footer as tool bars that provide contextual options based on where the user is in the app).

Currently I am not using a router and just calling explicit actions (using Flux) that update stores to tell these components which view they need to render.  This isn't great as I can't use browser routes as a way of sharing what state the app is in, or having nice things like the ability to go back.

An alternative that would work using react-router would be to define a handler for each route, but this would result in repetition of my main content in each handler because that is not changing.  This seems silly because the react-router guide shows that it is trying to avoid the repetition that you might get from using another router.

Essentially I am wondering if there is an idiomatic way to go about doing something like this with react-router (keep in mind I am using Flux so that could definitely play into a solution). To make my question more clear I have written up some working gists that demonstrate what I described in words.

This naive use case would look something like this. https://gist.github.com/jdlehman/2c4a3b1ec30917069ebb#file-naive-use-js

The following gist is my attempt using react-router.  It works on the initial render and route change, but is buggy on additional route changes. https://gist.github.com/jdlehman/2c4a3b1ec30917069ebb#file-multiple-route-defs-js

**Comment by daralthus** [comment]
+1

**Comment by johanneslumpe** [comment]
What is the error you are experiencing? Your react-router version works fine, except for the fact that react complains about a failure to reuse markup, because you are rendering your `Header` and `Footer` components inside your `App` component. You don't need to do that, because you are already rendering into the elements with the ids `header` and `footer` after you rendered your app.

After adding two links and changing the routes everything worked as expected. What you need to take care of though is the fact that if you have a route inside your header routes, which you do not have inside your footer routes and you transition to it, then your footer will either show nothing or your defined `NotFoundRoute`.

**Comment by jdlehman** [comment]
Thanks for looking this over @johanneslumpe. Removing the `Header` and `Footer` components from inside my `App` component got rid of the warnings as well as bugs I was experiencing.  This was a React issue (me using it poorly for that matter), not a react-router issue.

I still think it would be nice if react-router had documentation to support this use case, something like how [react-router-component](https://github.com/STRML/react-router-component) allows you to define a route handler in multiple components if you so desire.

Closing this as the workaround works. I may open a PR at a later date when I have time to investigate this use case in more detail.

**Comment by jdlehman** [comment]
Gist with working solution for anyone who comes across this thread later: https://gist.github.com/jdlehman/b662cac8b8607abf51a6
