### ISSUE TITLE
<Link> loses context when the component is rendered manually with jquery

### ISSUE THREAD

**Issue by tjwebb** [rackt/react-router#922]
I created this project (https://github.com/tjwebb/react-kendo) to use Kendo UI with React.js. It works great, and so does react-router. Kendo UI has a templating mechanism for customizing the way grid rows and such appear; you just write a function that returns an html string. This works great with every component I've tried, except for `<Link>`, which throws `missing from context` errors. I've also tried manually hacking in a component with mixes in `Navigation` with no luck.

This isn't exactly a bug report, but I'm looking for some guidance on how to work around this.

**Comment by taurose** [comment]
I believe you could make this work by not cloning the component (is there even any reason to do so without changing the props?), or using the upcoming `React.cloneElement`, in which cases the context will be preserved.

However, I don't think this would work for too long because of the switch to parent-based contexts (https://gist.github.com/jsfb/0eb6e61f300a8c1b2ce7). From what I understand, calling React.render like this takes away the parent and thus the (parent-based) context. 

Maybe there's some way to manually inject the context. You could create a wrapper that injects the router instance, but I'm not sure if it's possible to do that dynamically with arbitrary context.

Also keep in mind that RouteHandlers rely on context as well. So rendering them (or a parent) like this might cause problems as well.

**Comment by ryanflorence** [comment]
> Maybe there's some way to manually inject the context. You could create a wrapper that passes down the router's context

should work.

check out the code in https://github.com/rackt/react-router/issues/982#issuecomment-86065078
