### ISSUE TITLE
nested route history proliferation

### ISSUE THREAD

**Issue by tjwebb** [rackt/react-router#923]
Nested routes are the greatest thing ever, but Linking between and among nested sibling routes can cause the History to become filled with these actions. e.g.

```
<Route handler={App}>
  <Route name='foo' handler={Foo} />
  <Route name='bar handle={Bar} />
</Route>
```
Clicking `<Link>`s to foo and bar in the app causes the history to look like 
- /foo
- /bar
- /foo
- /bar
- /foo

and so on. So you might have to hit back 50 times to *actually* go back. Is there some way to easily remove duplicates like this? I'm using `HashLocation`

**Comment by taurose** [comment]
Well, that's how browser histories work :smile: I usually wouldn't consider that a problem unless, perhaps, when building for another environment.

Some ideas though:

* don't put the state into the url to begin with if you don't want it to affect browser history
* use replaceWith instead of transitionTo
* build your own Location object (or wrap HashLocation) to turn push actions into replace actions based on the current and the next url
* wrap router.transitionTo to compare the current and next state, and pass it via props to your handlers

**Comment by tjwebb** [comment]
> build your own Location object (or wrap HashLocation) to turn push actions into replace actions based on the current and the next url

Ok I'll into this. Thanks for the insight.

**Comment by ryanflorence** [comment]
Every time this comes up I tell people that I would merge a `<ReplaceLink to="..."/>`
