### ISSUE TITLE
isActive method

### ISSUE THREAD

**Issue by mega-cache-money** [rackt/react-router#974]
I'm trying to check whether a route is active, irrespective of the query parameters. 

I've tried `isActive('/someroute')` from the `State` mixin, but it always returns false. 

I'd need my example to return true, even if the actual route is `/someroute/anotherroute`. Using string processing of `getPathname()` seems messy...

What's the canonical way of accomplishing this?

**Comment by johanneslumpe** [comment]
If you pass an absolute path, i.e. a path beginning with `/`, the router will only check whether the current path is equal to that path. What you could do instead: pass a route name to `isActive`. If you do that, the router will check all active routes, whether one of those matches the name you provided. This way you can easily check whether a route is active or now.

Also: please use `this.context.router.isActive` instead of the `State` mixin, as it is deprecated.

**Comment by ryanflorence** [comment]
^ yep `isActive(routeName)` is what you want

multiple routes could start with `/someroute` but we can't know with just the path which are actually active, we need name for that.

```xml
<Route>
  <Route path="/someroute">
    <Route path="/someroute/foo"/>
  </Route>
  <Route path="/someroute/bar"/>
  <Route path="/someroute/baz"/>
</Route>
```
