### ISSUE TITLE
Idiomatic App using react-router

### ISSUE THREAD

**Issue by netgusto** [rackt/react-router#997]
Hello,
I'm building an idiomatic app presenting React-related technologies here : https://github.com/netgusto/IdiomaticReact

It uses react-router, and so it would be awesome if you ever find the time to review it; the aim is to make it the simplest yet functional implementation of a React/Flux app.

Thank you for the awesome work.

**Comment by gaearon** [comment]
This looks good. Needs updating to RR 0.13 though :-)

**Comment by tcoopman** [comment]
Looks good!

Some small remarks/questions. Most are personal, so this doesn't mean you should change it.

* Any reasons you don't use FluxComponent to subscribe to store updates in TodoList? This removes the need for the `getTodos()` in the store (see https://github.com/acdlite/flummox/blob/master/docs/react-integration.md)
* I would use `const TodoList = React ...` instead of `let ` or `export default React.createClass...` instead of `module.exports` as you already use ES6 and ES6 modules for imporintg.
* React.addons.classSet is deprecated (http://facebook.github.io/react/blog/2015/03/10/react-v0.13.html)

**Comment by ryanflorence** [comment]
feel free to keep talking about this here, but I'm going to close the issue. Thanks :)
